### PR TITLE
[gnc-ui-balances.c] better wording for balance limits

### PR DESCRIPTION
**Pull request by christopherlam**
Bikeshedding requested please. @nomis @fellen @Bob-IT 
https://code.gnucash.org/logs/2023/06/04.html#T10:10:04

### CODE REVIEW

**Comment by dawansv** [comment]
> Bikeshedding

I love the irony of this PR removing the obscure word _subceed_ while I had to google _Bikeshedding_ as I wasn't clear what it meant in this context ;-)

**Comment by Bob-IT** [comment]
I think I would just go with 'above set limit' and 'below set limit'

**Comment by dawansv** [comment]
"above higher balance limit of..." sounds odd to me. Shouldn't it be "upper balance limit"? As in "upper limit" not "higher limit"?

Interesting how English uses lower for the opposite of both higher and upper. In French (and probably other languages) we have different words for both: "supérieur/inférieur" for upper/lower (what we would use in this case, talking about the limits) and "plus haut/plus bas" for higher/lower.

**Comment by christopherlam** [comment]
Hence, bikeshedding. "higher balance limit" and "lower balance limit" are the actual option names in the account properties dialog. Any further votes? Or simply "above/below set limit"?

**Comment by nomis** [comment]
The current version repeats "balance" twice, which I feel is unnecessary.

e.g. "above higher limit" and "below lower limit"

**Comment by jralls** [comment]
What fun! I prefer "upper limit" to "higher limit"; it's much more common usage at least in American English. I agree with @nomis that "balance" is redundant. The template can be better still though: "%s balance of %s is above the upper limit %s" and "%s balance of %s should be 0".

**Pull request merged**
