### PR TITLE
Try to fix AS_SCRUB_INCLUDE when 'cpp' is not invokable

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by jralls** [comment]
Please explain in a bit more (meaning "excrutiating") detail what is the problem you're trying to fix and why this is only "Try to fix" instead "fix"; also why autotools needs fixing and CMakeLists.txt doesn't.

**Comment by hasufell** [comment]
> Please explain in a bit more (meaning "excrutiating") detail what is the problem you're trying to fix 

It's basically like hardcoding `cc` in Makefiles instead of relying on the `$CC` variable. On distros where `cpp` must not be invoked directly, but an architecture specific thing like `x86_64-pc-linux-gnu-cpp` this fails hard.

> and why this is only "Try to fix" instead "fix";

The proper fix would be to just remove remove that sed hackery, but I don't care enough to look for the side effects of that.

> also why autotools needs fixing and CMakeLists.txt doesn't.

I don't understand. This is an autotools macro, not a cmake macro.

**Comment by jralls** [comment]
Hmm, OK. I'm actually inclined to just remove the macro altogether like [gstreamer did](https://lists.freedesktop.org/archives/gstreamer-bugs/2013-September/110455.html) to no apparent ill effect.I'm curious, though: What distro is failing hard over this? It's been this way for over 10 years and nobody's had a problem with it before.

My original thought about cmake was that we're maintaining two build systems now and anything wrong with one of them tends to be wrong in both. This is likely an exception.

**Comment by hasufell** [comment]
> Hmm, OK. I'm actually inclined to just remove the macro altogether like gstreamer did to no apparent ill effect.

I tried that locally already and it worked. But I really have no idea if that might screw up some corner case for you.

> What distro is failing hard over this? It's been this way for over 10 years and nobody's had a problem with it before.

Well, it depends on how strict this is enforced. On gentoo it's a QA issue that might get noticed, on exherbo it's fatal. Autotools already gives sufficient control over the toolchain. Hence this was a "leak".

> My original thought about cmake was that we're maintaining two build systems now 

IMO you should decide on one and trash the other. It can be painful to properly maintain two build systems and make sure they don't get out of sync.

> and anything wrong with one of them tends to be wrong in both. This is likely an exception.

I'd rather say that's unlikely, since they are fundamentally different, at least when it's about such exotic failures. CMake has different problems.

**Comment by jralls** [comment]
>>Hmm, OK. I'm actually inclined to just remove the macro altogether like gstreamer did to no apparent ill effect.

>I tried that locally already and it worked. But I really have no idea if that might screw up some corner case for you.

The corner case is AFAICT gcc-3.x, which is so obsolete that I'm not going to worry about it.

>IMO you should decide on one and trash the other. It can be painful to properly maintain two build systems and make sure they don't get out of sync.

Mine too, and we'll probably drop autotools for 2.8.

**Comment by jralls** [comment]
I've pushed b905c4a, which removes AS_SCRUB_INCLUDES altogether. Thanks for pointing it out.

**Comment by hasufell** [comment]
thanks

**Pull request closed without merging**
