### PR TITLE
qofclass uses stl and ~qofchoice.cpp

### PR DESCRIPTION
**Pull request by christopherlam**
although the qof_choice param lists were being populated, they were never queried.

### CODE REVIEW

**Comment by jralls** [comment]
Don't waste time converting QOF to C++, we want to replace it with SQL.

**Comment by christopherlam** [comment]
I'd though it'd be easier to remove layers piecemeal?

**Comment by jralls** [comment]
It depends on the layers. To implement [Roadmap:Database and QOF](https://wiki.gnucash.org/wiki/Roadmap#Database_and_QOF):
1. Write xml<->sql backend with in-memory SQLite db. 
2. Replace all QofQuery calls with SQL queries.
3. Remove QofQuery and the parts of QOF that don't directly support QofSession, QofInstance, and QofCollection. AFAICT QofClass exists only to provide access to engine objects for QofQuery.

I'd like to get that done for GnuCash 6. The big payoff for users is
4. Write a report where the SQL query terms are part of the report options. No more need to write custom reports in Scheme ([Roadmap:Reports](https://wiki.gnucash.org/wiki/Roadmap#Reports)). It would be really sweet to have a drag-and-drop UI for constructing queries like Microsoft Access and formatting the results, but that's a major project all on its own. 

That's the easy part. The more difficult next step is to replace accessing QofCollections with SQL queries. Once that's done we can stop loading the whole DB into memory and lose the rest of QOF. At that point GnuCash is a real SQL app. We can implement record-level locking in the MySql and Postgresql backends and allow simultaneous user access.

**Comment by christopherlam** [comment]
Ok let's remove qofchoice.cpp at the very least.

**Comment by jralls** [comment]
> Ok let's remove qofchoice.cpp at the very least.

Yes please. Cruft removal is encouraged, I'm just trying to keep you from rewriting future cruft into C++.

**Pull request closed without merging**
