### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
Thanks!
@6e2f61 still one issue:
```
msgfmt -c --check-accelerators="_" --statistics po/pl.po
po/pl.po:30137: w msgstr brakuje skrótu oznaczenia klawiszowego „_”
msgfmt: znaleziono 1 błąd krytyczny
3884 przetłumaczone komunikaty, 1095 tłumaczeń budzi wątpliwości, 544 nieprzetłumaczone komunikaty.
```

**Comment by 6e2f61** [comment]
I think there is plethora of those issues in polish translation. Hope I'll fix them in some foreseeable future. Stay tuned!

**Comment by fellen** [comment]
> I think there is plethora of those issues in polish translation. Hope I'll fix them in some foreseeable future. Stay tuned!

That was the only active error, but perhaps there are more in the fuzzy translations.

**Comment by 6e2f61** [comment]
Out of curiosity, what is difference between this fuzzy and regular translation and how I can recognize this on weblate page?
I'm asking because [this](https://wiki.gnucash.org/wiki/Translation#Fuzzy_Flag) I can't wrap my head around.

**Comment by fellen** [comment]
> Out of curiosity, what is difference between this fuzzy and regular translation and how I can recognize this on weblate page? I'm asking because [this](https://wiki.gnucash.org/wiki/Translation#Fuzzy_Flag) I can't wrap my head around.

https://www.gnu.org/software/gettext/manual/gettext.html#Fuzzy-Entries
(link added to the wiki page)

in short "needs review by the translators" and the user will  see the untranslated message.

**Pull request merged**
