### PR TITLE
add account examples for zh_TW.

### PR DESCRIPTION
**Pull request by brianhsu**
Translate account hierarchy examples for zh_TW and teak them suitable for normal use case in zh_TW.

### CODE REVIEW

**Review by fellen — COMMENTED** [review]
Hi, I think you should mark all accounts, which are no leaves [Edit] of your account tree [/Edit] as placeholder. When I select all templates in the new account hierary assisntent, a few are not marked.

Can you review and improve or explain?

**Comment by fellen** [comment]
@Bob-IT In my test run I got a bunch of 
`(gnucash:30736): Pango-WARNING **: 06:40:48.306: Invalid UTF-8 string passed to pango_layout_set_text()`
Do you have an idea abou the cause?

**Comment by brianhsu** [comment]
> Hi, I think you should mark all accounts, which are no leaves [Edit] of your account tree [/Edit] as placeholder. When I select all templates in the new account hierary assisntent, a few are not marked.
> 
> Can you review and improve or explain?

Hi @fellen. You are right, those accounts should be marked as placeholders. I've updated them, thanks.

**Comment by jralls** [comment]
> (gnucash:30736): Pango-WARNING **: 06:40:48.306: Invalid UTF-8 string passed to pango_layout_set_text()

@fellen can you run in the debugger and see what is the string and where in GnuCash it's being passed to pango (probably by way of being set on a GtkWidget)?

**Comment by fellen** [comment]
> Hi @fellen. You are right, those accounts should be marked as placeholders. I've updated them, thanks.

There is still the business template. Can you review it, too?

**Comment by fellen** [comment]
> > (gnucash:30736): Pango-WARNING **: 06:40:48.306: Invalid UTF-8 string passed to pango_layout_set_text()
> 
> @fellen can you run in the debugger and see what is the string and where in GnuCash it's being passed to pango (probably by way of being set on a GtkWidget)?

Perhaps later. Today I watched the console closer:
Starting the New File assistant results in 11 occurrences
Step 2, tab 3: 1x
On Finish, which starts save as: very many.
The rest of the assistant seems OK

**Comment by brianhsu** [comment]
> > Hi @fellen. You are right, those accounts should be marked as placeholders. I've updated them, thanks.
> 
> There is still the business template. Can you review it, too?

Besides added / remove some leaf accounts, I didn't touch the non-leaf account of business template. Most of them are copied from the template inside data/accounts/C and are expense accounts.

Since I'm not a professional accountant, I'm not sure the leaf accounts of these parent accounts are comprehensive. I thinks it's better keep it as the usual.

Those accounts and their corresponding name in English are:
```
+ 費用 (Expense)
 |
+---- 保險 (Insurance)
+---- 修理 (Repair)
+---- 專業費用 (Professional Fees)
+---- 旅行和娛樂 (Travel and Entertainment)
+---- 水電費 (Utilities)
+---- 汔車 (Autos)
+---- 稅費 (Taxes)
```

**Comment by brianhsu** [comment]
> Perhaps later. Today I watched the console closer:
> Starting the New File assistant results in 11 occurrences
> Step 2, tab 3: 1x
> On Finish, which starts save as: very many.
> The rest of the assistant seems OK

Just for your information, not sure if helpful or not.

On my system the pango library version are 1.48.5.

I built the latest code in the maint branch by the following command:
```
$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt
$ make
$ make install
```

After that I tried may time with the following command:

```
LANG=<locale> ~/opt/bin/gnucash --nofile --log "=debug" --log "qof=debug" --log "gnc=debug" --logto stdout 2>&1 | grep 'Pango'
```

'<locale> I've tried are ca_AD / en_US / de_DE / zh_TW / C, and when I was doing the following test, none of them have the Pango warning message.

1. Open new file by click File -> New File menu item.
2. Forward to Step 2 (New Book Options), choose tab 3 (Business).
3. Finish the whole assistant with default options.
4. Save file by press save as.

I'm not sure if this is library version or region-specific problem. Feel free to tell me if there is anything I can help.

**Comment by fellen** [comment]
Merged, Thanks!

**Pull request merged**
