### PR TITLE
zh_CN.po: update Simplified Chinese translation

### PR DESCRIPTION
**Pull request by holymonson**
1. Use offical accouting terms.
2. Correct or delete some wrong translations.

A fixed version of #348, it was closed by accident.

### CODE REVIEW

**Comment by holymonson** [comment]
@fellen,
@hosiet is a member of zh_CN team of TranslationProject, and he will take over the patch when he's available.

**Comment by jralls** [comment]
@holymonson so we can close this PR, correct?

**Comment by holymonson** [comment]
No reply from TranslationProject, and I don't know what's going on in their workflow. @hosiet is a kindly member of TP, but not responsible for gnucash. In fact, no one is for very long time. And I don't want to join an organization just for one patch. I'm a gnucash user, not a translator.

Now, here is an unreviewd patch, not perfect but at least fixed many major errors existing for years, merging it won't be worse. Or, close this PR and wait for someone finally taking over it, this patch could be a reference.

Either way works for me, I can live with the english version, so don't be sorry for closing it.

**Comment by jralls** [comment]
Boyuan Yang *did* reply to [your post](https://groups.google.com/forum/#!searchin/i18n-zh/gnucash|sort:date/i18n-zh/89zz0KIsN-8/1pSfaCiiCgAJ) on i18-zh with a few review comments.

Unfortunately either TP maintains the translation and we get changes from them or we take the translation away from them and rely on a non-TP translator. I'm not willing to take the translation away for a drive-by, so I guess we'll have to hope that one of them picks it up.

**Comment by hosiet** [comment]
@holymonson I have reviewed and uploaded a new version of gnucash `zh_CN` translation. You can always find the latest version here: https://translationproject.org/PO-files/zh_CN/gnucash-3.3.zh_CN.po (link from https://translationproject.org/team/zh_CN.html )

It's pretty hard for me (who has no experience in finance) to review it but I always accept patches or improvement suggestions. You are still welcomed to join the TranslationProject at any time.

**Comment by jralls** [comment]
@hosiet Thanks for taking action on this. We'll include it in the 3.4 release.

**Comment by jralls** [comment]
@hosiet There's a subsequent translation that was submitted to your google-group list: https://groups.google.com/forum/#!topic/i18n-zh/iwwQRX8qF8E. I contacted the author by separate email but received no reply.

**Comment by hosiet** [comment]
@jralls Don't worry. I coordinated with that submitter in preparing this upload.

**Pull request closed without merging**
