### PR TITLE
Help page doesn't work

### PR DESCRIPTION
**Pull request by talmaashani2016**
If we click on the help page, the link wouldn't work. Link need to be corrected. Here is a photo that express the issue 
Thank you 
TB
Screen Shot 2019-11-14 at 12 52 27 PM

### CODE REVIEW

**Comment by gjanssens** [comment]
Ehm, why are you propoposing gitlab continuous integration for this project ? GnuCash is not hosted on gitlab.

**Comment by talmaashani2016** [comment]
> Ehm, why are you propoposing gitlab continuous integration for this project ? GnuCash is not hosted on gitlab.

I've been working on some continuous integration for the project on GitLab

**Comment by gjanssens** [comment]
While that's nice, I don't think this belongs in our repo. I'm sorry.

 We use github's CI integration. You are of course free to have a different CI in your gitlab clone of the project. If we ever consider to switch to gitlab ourselves (which I have been mulling in the past) we would be more interested in your integration project. Not in the current situation.

And as for the original PR subject: it looks as if you want to report a bug. We have bugs.gnucash.org for that. Please report it there and be sure to add sufficient detail, like what operating system, where does the package come from,....

Thank you.

**Comment by fellen** [comment]
BTW: I know of the "ghelp:<document>/<topic>" issue. Fixing the cross links is one of the next tasks on my list.

**Comment by fellen** [comment]
Another aspect is discussed in https://bugs.gnucash.org/show_bug.cgi?id=726146

**Pull request closed without merging**
