### PR TITLE
[date-utilities] Convert reldate list into srfi-9 records

### PR DESCRIPTION
**Pull request by christopherlam**
Cleanup, rearranges strings. Need to confirm i18n still works well. @fellen

### CODE REVIEW

**Comment by jralls** [comment]
This file gets removed in [c++options](https://github.com/jralls/gnucash/tree/c++options), no point in tidying it up.

**Comment by fellen** [comment]
I compared gnucash.pot before and after the commit: "One Week A{go|head}[.]" disappeared. Resaon?

N.B. This file has always been a terrible example of I18n:
 The tooltips are no full sentences.
Are full number words really required instead of a ngettext expression?  …

**Comment by christopherlam** [comment]
@fellen "One week ago" was translatable but not actually inserted into the reldate list. There are no complaints about it; I'd remove it. @jralls any ETA for c++options to be ready?

**Comment by jralls** [comment]
@christopherlam for what value of ready? I guess there's still 2-3 months of solid work left and I've managed about 3 days worth since July.

**Comment by christopherlam** [comment]
It'll be a while till c++options is ready then. I'll push this change which means we can deprecate `gnc:make-string-database`

**Comment by christopherlam** [comment]
To my shame, this branch breaks reports spectacularly. I'll await c++options to be complete then.

**Pull request merged**
