### PR TITLE
Transaction associations

### PR DESCRIPTION
**Pull request by Bob-IT**
Was thinking about using this but thought it could be improved the points being.
Added ability to see existing association.
Added a cell to the register so that you can see the transaction has an association and made it read only.
Added a dialog to retrieve all associations and test whether they are still available with the option to jump to the transaction or open the association or sort them.

### CODE REVIEW

**Comment by Bob-IT** [comment]
I see my pull request has failed on Travis but I can not gain access to any details, if click on Details I get a blank page!

**Comment by jralls** [comment]
Bob,
I had a bit of trouble getting Travis to display this morning, too, but after poking at it a bit got the results: It failed the report-utilities test. Unfortunately AFAIK there's no way to look at the test logs to find out what failed, but just like Frank's failures yesterday it's hard to see how your changes caused the failure.

**Comment by Bob-IT** [comment]
I wanted to open file associations in a Windows and Linux version so added a preference to set the path head and then file associations would be stored relative to this head if it is parent or full path if not. Also added a toggle column to indicate this in the dialog. This works OK but maybe the text could be improved.

**Comment by jralls** [comment]
Very nice. I particularly like using the second-line "reconciled" field for the attachment indicator. I don't use the second line and seldom think of it for available real estate.

Merged after a rebase.

**Pull request closed without merging**
