### PR TITLE
 Test loading and saving XML files with and without compression

### PR DESCRIPTION
**Pull request by nomis**
Add new test files that are written with the latest version of GnuCash. Test loading them, saving to compressed files, loading those compressed files and writing to an uncompressed file. At every stage check it matches the canonical version.

### CODE REVIEW

**Comment by nomis** [comment]
I haven't tested the cmake dist list changes.

**Comment by christopherlam** [comment]
I think the test suite is sorely lacking some real datafiles to read from. As an extension to this, it would be much easier to create tests for reports. Any thoughts about creating plumbing for this?

test-report.scm:
```scheme
(gnc-load-session "datafile.gnucash")
(test-transaction-reports)
```

**Comment by jralls** [comment]
> I think the test suite is sorely lacking some real datafiles to read from.

Maybe for a secondary test suite that isn't run often. As a general rule you don't want unit tests to depend on any sort of IO because IO is slow. Sure, one file load takes only a couple hundred milliseconds, but unit testing frameworks are designed to start every test from scratch. That delay adds up quickly.

**Comment by jralls** [comment]
@nomis, I would greatly prefer not using the legacy test framework for new code, especially when that new code is C++. Why didn't you use Googletest?

**Comment by nomis** [comment]
> Why didn't you use Googletest?

Because this test is copied from parts of `test-save-in-lang.cpp` and `test-load-xml2.cpp` that already process multiple `*.gml2` files.

**Comment by jralls** [comment]
That's not a good reason, especially since you had to extend the legacy test framework.

**Comment by nomis** [comment]
I've changed it to use GoogleTest.

Testing with `e0e13604b5bda4b2a28c13d77095800243410430` reverted:
```
Running main() from /usr/src/googletest/googletest/src/gtest_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from LoadSaveFilesDir/LoadSaveFiles
[ RUN      ] LoadSaveFilesDir/LoadSaveFiles.test_file/0
/home/simon/src/gnucash/libgnucash/backend/xml/test/gtest-load-save-files.cpp:246: Failure
Expected equality of these values:
  qof_session_get_error (save_compressed_session.get ())
    Which is: 1008
  0
qof_session_save (save_compressed_session.get (), nullptr): 1008 ""
[  FAILED  ] LoadSaveFilesDir/LoadSaveFiles.test_file/0, where GetParam() = "../gnucash/libgnucash/backend/xml/test/test-files/load-save/bug-746937-sx-split-order.gnucash" (5 ms)
[ RUN      ] LoadSaveFilesDir/LoadSaveFiles.test_file/1
/home/simon/src/gnucash/libgnucash/backend/xml/test/gtest-load-save-files.cpp:246: Failure
Expected equality of these values:
  qof_session_get_error (save_compressed_session.get ())
    Which is: 1008
  0
qof_session_save (save_compressed_session.get (), nullptr): 1008 ""
[  FAILED  ] LoadSaveFilesDir/LoadSaveFiles.test_file/1, where GetParam() = "../gnucash/libgnucash/backend/xml/test/test-files/load-save/sample1.gnucash" (9 ms)
[----------] 2 tests from LoadSaveFilesDir/LoadSaveFiles (14 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (17 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] LoadSaveFilesDir/LoadSaveFiles.test_file/0, where GetParam() = "../gnucash/libgnucash/backend/xml/test/test-files/load-save/bug-746937-sx-split-order.gnucash"
[  FAILED  ] LoadSaveFilesDir/LoadSaveFiles.test_file/1, where GetParam() = "../gnucash/libgnucash/backend/xml/test/test-files/load-save/sample1.gnucash"

 2 FAILED TESTS
```

**Comment by jralls** [comment]
Thanks!

**Pull request merged**
