### PR TITLE
Fix issues with loading and running init.py

### PR DESCRIPTION
**Pull request by codesmythe**

### CODE REVIEW

**Comment by gjanssens** [comment]
Thanks!

I have also merged into master where I still see the issues I reported earlier. Some more digging reveals this:

- Before running ninja-build install (so with the install directory still empty) the python-bindings test works.
- After running ninja-build install, the test runs, but exits with an exception.
- Emptying the install directory again, an the test runs fine again.

So it seems there is interference between the build and installation paths. Perhaps the changes to PYTHON_PATH should be done more selectively depending on whether in the build environmen or the installed environment ?

**Comment by codesmythe** [comment]
Hi Geert, 

In this PR (for maint), I added code to src/bin/CMakeLists.txt to add a setting for PYTHONPATH at the end of etc/gnucash/environment. In the merge to master, this code was added to gnucash/gnucash/CMakeLists-bin.txt, but I don't think this file is used, so the environment is not set up right, I think.

I can do a PR to get master sorted out, but I'd like to know the status of that CMakeLists-bin.txt file.

Thanks.

Rob

**Comment by gjanssens** [comment]
On dinsdag 12 september 2017 19:14:53 CEST Rob Gowin wrote:
> Hi Geert,
> 
> In this PR (for maint), I added code to src/bin/CMakeLists.txt to add a
> setting for PYTHONPATH at the end of etc/gnucash/environment. In the merge
> to master, this code was added to gnucash/gnucash/CMakeLists-bin.txt, but I
> don't think this file is used, so the environment is not set up right, I
> think.
> 
> I can do a PR to get master sorted out, but I'd like to know the status of
> that CMakeLists-bin.txt file.
> 
> Thanks.
> 
> Rob


I wasn't aware the merge applied these changes to CMakeLists.txt-bin. That 
file should not have been included in the repo, a mistake I made while 
restructuring the directories.

Please go ahead and create a PR to fix it, including the removal of that file.

Geert

**Comment by gjanssens** [comment]
I have made the changes myself to the proper CMakeLists.txt file. I still see the segfault at the end of the python bindings test. And it still happens only when ninja-build install has been run before (so gnucash is installed in the designated prefix).
Moreover, when running gnucash (from the installed location) it gives me this error right before it segfaults:

```
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: specified class size for type 'PyGtkGenericCellRenderer' is smaller than the parent type's 'GtkCellRenderer' class size
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  from gtk import _gtk
```

**Comment by codesmythe** [comment]
Thanks for fixing up the merge. I'm able to reproduce the issue with the python-bindings check failing after an install. So I'll take a look at that. For the import error you show above, could it be that we are mixing gtk-2 (from python) and gtk-3 (from GnuCash)?

**Comment by codesmythe** [comment]
One thing I've found on the python-bindings issue is that if you remove or rename $CMAKE_INSTALL_PREFIX/etc/gnucash/environment, the test passes. So I'm pursing that.

On the import issue, I guess but have not verified that the bindings work on an autotools build, so I'll need to do an autotools build next.

**Comment by gjanssens** [comment]
On woensdag 13 september 2017 16:20:10 CEST Rob Gowin wrote:
> Thanks for fixing up the merge. I'm able to reproduce the issue with the
> python-bindings check failing after an install. So I'll take a look at
> that. For the import error you show above, could it be that we are mixing
> gtk-2 (from python) and gtk-3 (from GnuCash)?

Yes, I saw that too. And I think you're right we're mixing gtk2 and gtk3. 
We'll have to figure out how to import the gtk3 python bindings instead (if 
they exist).

**Comment by jralls** [comment]
They do, but they work a bit differently so the python code has to change a bit. There's a [migration guide](https://wiki.gnome.org/Projects/PyGObject/IntrospectionPorting#Porting_from_PyGTK_2_to_PyGI_GTK_3) to get you started...

**Comment by gjanssens** [comment]
I've used the conversion script linked to on that webpage to do an initial conversion. That has at least solved the segmentation faults I got when trying to run  a gnucash built with python bindings enabled. It doesn't fix the python bindings themselves though. I now get this error on my system:
```
Traceback (most recent call last):
  File "/home/janssege/Development/installs/kdevelop/gnucash/master/share/gnucash/python/init.py", line 5, in <module>
    from gi.repository import Gtk
  File "/usr/lib64/python2.7/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gdk.py", line 441, in <module>
    initialized, argv = Gdk.init_check(sys.argv)
AttributeError: 'module' object has no attribute 'argv'
```

**Pull request merged**
