### PR TITLE
Optiondb changes

### PR DESCRIPTION
**Pull request by christopherlam**
because the account_list options were getting some spurious null accounts.

### CODE REVIEW

**Comment by jralls** [comment]
Looks good.

**Comment by christopherlam** [comment]
let's revert this for 799533

**Comment by jralls** [comment]
@christopherlam do you remember what motivated it in the first place? I thought that it was some discussion of a problem in gnucash-user but I couldn't find it.

**Comment by christopherlam** [comment]
3e5d6a5 was written to suppress some warnings, I recall there was a prior recent commit of yours (and I cannot find anymore) which was rather chatty especially when the account from a guid didn't exist anymore. However I cannot recall the exact action which was dumping warnings.

**Pull request merged**
