### PR TITLE
Cashflow barchart report

### PR DESCRIPTION
**Pull request by jmarino**
Three small changes to the just merged new report cashflow-barcharct.scm

The first 2 simplify the code a little bit and the 3rd adds a new feature: the ability to control the display of money in, out or net independently.

### CODE REVIEW

**Comment by jralls** [comment]
These changes break test-cashflow-barchart:
irectory: /Users/john/Development/Gnucash-Build/Gnucash-master-git/build/gnucas
h-git/gnucash/report/standard-reports/test
"test-cashflow-barchart" start time: Oct 28 14:17 PDT
Output:
----------------------------------------------------------
Backtrace:
In ice-9/boot-9.scm:
 160: 11 [catch #t #<catch-closure 10f78f580> ...]
In unknown file:
   ?: 10 [apply-smob/1 #<catch-closure 10f78f580>]
In ice-9/boot-9.scm:
  66: 9 [call-with-prompt prompt0 ...]
In ice-9/eval.scm:
 432: 8 [eval # #]
In ice-9/boot-9.scm:
2404: 7 [save-module-excursion #<procedure 10f814a00 at ice-9/boot-9.scm:4051:3
()>]
4056: 6 [#<procedure 10f814a00 at ice-9/boot-9.scm:4051:3 ()>]
In /Users/john/Development/gtk-sources/gnucash-git/gnucash/report/standard-repor
ts/test/test-cashflow-barchart.scm:
  34: 5 [#<procedure 10f930180 ()>]
In ice-9/boot-9.scm:
3589: 4 [process-use-modules (((gnucash report stylesheets)))]
 705: 3 [map #<procedure 10f79cc80 at ice-9/boot-9.scm:3589:25 (mif-args)> ((#))
]
3590: 2 [#<procedure 10f79cc80 at ice-9/boot-9.scm:3589:25 (mif-args)> (#)]
2870: 1 [resolve-interface (gnucash report stylesheets) #:select ...]
In unknown file:
   ?: 0 [scm-error misc-error #f ...]

ERROR: In procedure scm-error:
ERROR: no code for module (gnucash report stylesheets)
<end of output>
Test time =   0.54 sec
----------------------------------------------------------
Test Failed.
"test-cashflow-barchart" end time: Oct 28 14:17 PDT
"test-cashflow-barchart" time elapsed: 00:00:00
----------------------------------------------------------

**Comment by jmarino** [comment]
That's weird, I don't see that here. The error happens in test-cashflow-barchart.scm when it tries to load the stylesheets module and these 3 changes did not modify that file. Sometimes I've seen weird errors like this one that got fixed after a make clean ; make.

Is the loading of the stylesheets module done correctly?
```
(add-to-load-path "../../stylesheets/")
(use-modules (gnucash report stylesheets))
```
I don't really know if this is the proper way of doing it.

The module needs to be explicitly loaded in the test files to ensure that `gnc-monetary` values are rendered correctly. I believe this is not needed during normal operation because the stylesheets module is loaded from c code (in gnucash-bin.c).

**Comment by jralls** [comment]
The problem seems to be on the cmake side, and I discovered that it fails after the earlier PR as well. 

Yes, (add-to-load-path "../../stylesheets") is the likely problem. I'd expect the path to be relative to cwd rather than the location of the source file.

**Comment by jralls** [comment]
Hmm, but it passes on Travis. The failures are on both mac  and my Fedora 26 VM.

**Comment by jmarino** [comment]
What about this patch, moving the load-path addition to the build system:
```
diff --git a/gnucash/report/standard-reports/test/CMakeLists.txt b/gnucash/report/standard-reports/test/CMakeLists.txt
index 7be4c9c67..77c6badd6 100644
--- a/gnucash/report/standard-reports/test/CMakeLists.txt
+++ b/gnucash/report/standard-reports/test/CMakeLists.txt
@@ -10,11 +10,13 @@ SET(scm_test_standard_reports_SOURCES
   test-generic-net-linechart.scm
 )
 
+SET(GUILE_LOAD_DIRS    libgnucash/app-utils libgnucash/engine libgnucash/core-utils libgnucash/gnc-module gnucash/gnome-utils gnucash/report/report-system libgnucash/scm gnucash/report/stylesheets)
+
 GNC_ADD_SCHEME_TARGETS(scm-test-standard-reports
   "${scm_test_standard_reports_SOURCES}"
   gnucash/report/standard-reports/test
   ""
-  ""
+  "${GUILE_LOAD_DIRS}"
   ""
   "scm-gnc-module;scm-test-report-system"
   FALSE
diff --git a/gnucash/report/standard-reports/test/Makefile.am b/gnucash/report/standard-reports/test/Makefile.am
index 2a4e80803..78ebd09b7 100644
--- a/gnucash/report/standard-reports/test/Makefile.am
+++ b/gnucash/report/standard-reports/test/Makefile.am
@@ -30,6 +30,7 @@ GNC_TEST_DEPS = \
   --guile-load-dir ${top_builddir}/gnucash/report/report-system/test \
   --guile-load-dir ${top_builddir}/gnucash/report/standard-reports \
   --guile-load-dir ${top_builddir}/gnucash/report/standard-reports/test \
+  --guile-load-dir ${top_builddir}/gnucash/report/stylesheets \
 \
   --library-dir    ${top_builddir}/gnucash/report/report-system \
   --library-dir    ${top_builddir}/libgnucash/core-utils \
diff --git a/gnucash/report/standard-reports/test/test-cashflow-barchart.scm b/gnucash/report/standard-reports/test/test-cashflow-barchart.scm
index e4f7dde65..eacbfe61d 100644
--- a/gnucash/report/standard-reports/test/test-cashflow-barchart.scm
+++ b/gnucash/report/standard-reports/test/test-cashflow-barchart.scm
@@ -30,7 +30,6 @@
 (use-modules (gnucash report report-system test test-extras))
 (use-modules (gnucash report standard-reports cashflow-barchart))
 
-(add-to-load-path "../../stylesheets/")
 (use-modules (gnucash report stylesheets))
 
 (use-modules (ice-9 format))
```

**Comment by jralls** [comment]
That would actually work, but I bet it's not for the reason you think, and removing add-to-load-path would break the autotools build without some Makefile.am changes.

It turns out that the problem is that I usually call ninja check, relying on the test dependencies to get everything built. It doesn't build stylesheets.go, so the test fails. If I run ninja && ninja check the test passes. CMake builds put the build products in one place so the add-to-load-path dance is superfluous.

**Comment by jmarino** [comment]
That explains why I couldn't make the test fail when building with cmake. 

Then the extra load-path is only needed when building with autotools (which is what I was using) and this patch should do the trick, right?
```
diff --git a/gnucash/report/standard-reports/test/Makefile.am b/gnucash/report/standard-reports/test/Makefile.am
index 2a4e80803..78ebd09b7 100644
--- a/gnucash/report/standard-reports/test/Makefile.am
+++ b/gnucash/report/standard-reports/test/Makefile.am
@@ -30,6 +30,7 @@ GNC_TEST_DEPS = \
   --guile-load-dir ${top_builddir}/gnucash/report/report-system/test \
   --guile-load-dir ${top_builddir}/gnucash/report/standard-reports \
   --guile-load-dir ${top_builddir}/gnucash/report/standard-reports/test \
+  --guile-load-dir ${top_builddir}/gnucash/report/stylesheets \
 \
   --library-dir    ${top_builddir}/gnucash/report/report-system \
   --library-dir    ${top_builddir}/libgnucash/core-utils \
diff --git a/gnucash/report/standard-reports/test/test-cashflow-barchart.scm b/gnucash/report/standard-reports/test/test-cashflow-barchart.scm
index e4f7dde65..eacbfe61d 100644
--- a/gnucash/report/standard-reports/test/test-cashflow-barchart.scm
+++ b/gnucash/report/standard-reports/test/test-cashflow-barchart.scm
@@ -30,7 +30,6 @@
 (use-modules (gnucash report report-system test test-extras))
 (use-modules (gnucash report standard-reports cashflow-barchart))
 
-(add-to-load-path "../../stylesheets/")
 (use-modules (gnucash report stylesheets))
 
 (use-modules (ice-9 format))
```

**Comment by jralls** [comment]
Sorry, I stared right past the Makefile.am part of the patch. Yes, adding it there is better than calling add-to-load-path in test-cashflow-barchart.scm. Please also delete the line above add-to-load-path so that the gnucash modules are grouped together.

The cmake change isn't quite right as I said and while it would probably work with ninja it probably won't with cmake and make. The GNC_ADD_SCHEME_TEST function needs a way to set dependencies for its targets. I'll work on that a bit; meanwhile go ahead and push the autotools patch and I'll merge this PR.

**Comment by jmarino** [comment]
Committed patch as requested.

**Comment by jralls** [comment]
Thanks!

**Pull request merged**
