### PR TITLE
Update readme re pull requests - refer to wiki instead

### PR DESCRIPTION
**Pull request by goodvibes2**
As per discussion and suggestion by John Ralls in https://github.com/Gnucash/gnucash/commit/293b43dcedc36e9a9c6469b36c3032724d1f824b

### CODE REVIEW

**Comment by gjanssens** [comment]
Thanks for the update. I have committed it to maint after fixing the PR. I see you have switched to using feature branches now, which is good.

However it looks like you have a leftover from the previous PR that was directly on maint: most likely your local maint branch has diverged from the current maint branch in the origin repository.

What I suggest you do is this
- execute "git fetch origin"
- execute "git checkout maint"
- check your local maint branch doesn't have any commits that aren't already on the origin/maint branch. You can use a graphical tool like gitk for this (there are others, but I only have experience with this one).
- If you don't, execute "git reset --hard origin/maint". This will align your local maint branch with origin's maint branch again.
- If you do have commits on your local maint still that are not also on local/maint, proceed with these commands:
- git branch tmp
- git reset --hard origin/maint
- git rebase maint tmp
This should align your local maint branch with origin's maint and filter out any commits that weren't on origin's maint yet into a new branch called 'tmp', provided these commits don't conflict with origin's maint.

I believe if you stick with using feature branches this cleanup is only needed once.

Final note: as this PR has been merged with origin, you can now delete your local updateREADME feature branch as well as the one in your goodvibes2 github repo.

If anything is unclear, feel free to ask for more details. And thanks for the PR.

**Comment by goodvibes2** [comment]
Hi Geert,
Thanks very much for the detailed instructions.
I followed them but think I incorrectly understood gitk thinking I did not have a commit in local maint that was in origin/maint. I found after I finished that my GitHub maint still said it was 3 commits in front of Gnucash/maint, so, as I didn't have anything I needed to keep in my local repo, I deleted my local and GitHub repos and reforked Gnucash/gnucash and cloned again. Seems OK now.
Thanks again, Chris

**Comment by gjanssens** [comment]
Hi Chris,
I may have started from a wrong assumption. I assumed "origin" referred to Gnucash/gnucash, but reading your last comment it rather looks like it refers to goodvibes2/gnucash. In that situation my steps would not do what I had in mind. Sorry about that.
Does the cloned repo on your local machine also have a reference to the Gnucash/gnucash repo or only to goodvibes2/gnucash ?
If you intend to continue to send in PR's (which I hope), it's probably easier to have both configured as remotes for your local clone. That allows you to synchronize your local repo with new commits in Gnucash/gnucash and from there push the same changes to goodvibes2/gnucash.
Perhaps github has an interface for this as well, but I didn't find one.

To see if you have other remotes:
- git remote -v

To add Gnucash/gnucash as remote:
- git remote add <name> https://github.com/Gnucash/gnucash.git
You should replace <name> with something that's convenient for you to remember this remote refers to the Gnucash/gnucash repo on github. (It's like "origin" is the name to refer to your goodvibes2/gnucash repo).

**Comment by goodvibes2** [comment]
Hi Geert,
Yes I have created remote 'upstream' (https://github.com/Gnucash/gnucash.git) and of course have the 'origin' created automatically by cloning from github.com:goodvibes2/gnucash-docs.git.
I've been thinking I should add to http://wiki.gnucash.org/wiki/Git a recommendation for remote names so we all have more likelihood of talking about the same thing. There seems to be a few different naming schemes on the wiki and in some emails I've seen. E.g using 'github' for personal GitHub repo.

As some-one who doesn't have commit permissions to official Gnucash/gnucash[-docs], I think I only need upstream and origin.
As an official committer, what remotes do you use? I suppose you use upstream as code.gnucash.org/gnucash? Any others?

Thanks for bringing 'git remote -v' to my attention. I had been using 'git config -l'.

I think I now know how to use git enough for my needs, although I'm not sure how to handle updating a continuing feature branch after pulling from upstream to update local maint/master.
I'm using some instructions from a John email to some-one else that basically says, after mods are merged into official repo's, pull from upstream, then push to origin, then delete local and origin feature branches that were merged. Do I need to rebase other continuing local feature branches?
Thanks and regards, Chris

**Comment by gjanssens** [comment]
On Thursday 23 June 2016 15:53:21 Chris Good wrote:
> Hi Geert,
> Yes I have created remote 'upstream'
> (https://github.com/Gnucash/gnucash.git) and of course have the
> 'origin' created automatically by cloning from
> github.com:goodvibes2/gnucash-docs.git. I've been thinking I should
> add to http://wiki.gnucash.org/wiki/Git a recommendation for remote
> names so we all have more likelihood of talking about the same thing.
> There seems to be a few different naming schemes on the wiki and in
> some emails I've seen. E.g using 'github' for personal GitHub repo.
> 
Chris,

That's probably a good idea. I think the choice of names depends a bit on whether you have 
direct commit access or not and then on your level of comfort with git. I think it makes sense 
that the remote repository you use most should be named "origin". For non-committers that's 
typically their own fork on github, for committers that would be the repo on code.gnucash.org. 
For non-committers, "upstream" is a good name for the Gnucash/gnucash repo.

> As some-one who doesn't have commit permissions to official
> Gnucash/gnucash[-docs], I think I only need upstream and origin.

Correct.

> As
> an official committer, what remotes do you use? I suppose you use
> upstream as code.gnucash.org/gnucash? Any others?

Actually my configuration is slightly more advanced/complicated than that. My origin points to 
both code.gnucash.org/gnucash and github.com/Gnucash/gnucash. The former is used when I 
push, the latter when I pull (git remote -v shows different fetch and push urls). I have set it up 
like that so I can keep an eye on both repositories at once (they should always be in sync).

I also have a personal gnucash repo on github (github.com/gjanssens/gnucash). I use this rather 
infrequently and only to publicize code that's not ready yet for the canonical repository. For 
example I sometimes push a fix for a bug I can't verify myself and then ask the bug reporter to 
test the commit and report back. Or when I do bigger code changes and would like feedback 
from the other devs before merging it into the canonical repository, they first appear on my 
personal github repo.

To complete my setup and for my convenience I have cloned the gnucash repo twice on my local 
workstation: once for my work on the maint branch and once for my work on the master branch. 
This is useful when I have to switch context. I can just leave the maint repo in the state it is 
(even with uncommitted work!) and move to the master repo and continue whatever I was 
doing there.

Finally I have yet another remote repo, which resides on my internal server. I use that one to 
pass around stuff between the two repos (for example when I started something on maint, but 
then decide it should rather go on master) or my different PC's.

This setup has grown organically over the years.

> 
> Thanks for bringing 'git remote -v' to my attention. I had been using
> 'git config -l'.
> 
> I think I now know how to use git enough for my needs, although I'm
> not sure how to handle updating a continuing feature branch after
> pulling from upstream to update local maint/master. I'm using some
> instructions from a John email to some-one else that basically says,
> after mods are merged into official repo's, pull from upstream, then
> push to origin, then delete local and origin feature branches that
> were merged.
That is a good approach.

> Do I need to rebase other continuing local feature
> branches?
I would do so. You can however choose whether to do that immediately or only right before 
initiating a pull request.

My reasoning is this: if you rebase your branch right before starting a PR, you will catch any 
potential conflicts between your feature branch and its parent branch. As you are the author of 
the feature branch you're often best positioned to resolve these conflicts as you know best what 
your branch is supposed to be doing. The one processing your PR may not always have these 
details.

As to rebasing in general, there is some debate over whether it should be done or not. Rebasing 
a public branch that is tracked by many people would cause git pull to fail on that branch for 
each of those people. That's considered rude.

On the other hand not rebasing at all creates lots of split branches in the git history, which 
makes it harder to read.

So my compromise is to rebase everything that was never made public, right before publicizing 
it. I do the same with PR's if they are relatively small (few commits) and don't conflict.

For larger features it sometimes makes sense to merge instead of rebase, precisely to highlight 
it was a separate feature that got added with its own history.

I don't have hard rules for this, I partly go with my gut feeling.

Regards,

Geert

**Comment by jralls** [comment]
Mind if I join in?

My position on rebasing is that maint and branch are canonical and therefore never rebased. My long-running feature branches, which I publish on my [personal github repo](https://gitub.com/jralls/gnucash.git) get rebased frequently to make sure that conflicts with master are found and fixed quickly instead of snowballing.

I think it's better to rebase a branch immediately before merging. That keeps the merge commit from having a bunch of conflict-resolution changes. Merging with --no-ff will force a merge commit and so keep the feature branch separately identifiable in history. But nothing's permanent until you push, so you can always try the merge first and if it has a bunch of conflicts reset it and do a rebase.

**Comment by gjanssens** [comment]
Thanks for adding your experience and recommendations, John. I always prefer input from multiple sources.

I presume you meant maint and **master** branch.

I see we think roughly the same about rebase vs merge. However you manage to write it down more clearly and concisely. I didn't think of --no-ff. That's a useful option for big features.

**Comment by jralls** [comment]
> I presume you meant maint and master branch.

Oops, yes, of course.

**Comment by goodvibes2** [comment]
Hi Geert + John,
Thank you both for you comments - very helpful.
I have updated http://wiki.gnucash.org/wiki/Git fairly substantially, in the Non-Committers sections mostly.
I probably misunderstood some things so if you'd like me to change anything, please let me know.

I suspect you may not be happy with the way I have prefixed the sub-section headings with Patches or Pull Requests as I think it is important to be clear about where one is, but I'm happy to alter if you wish.

Regards, Chris

**Comment by jralls** [comment]
You're right, I don't like it. It's way to prescriptive. Perl has an initialism, TMTOWTDI: There's more than one way to do it. That applies to Git as well. 
Git is very well documented. There's absolutely no need to replicate small bits of it in the wiki page. That's just a disservice to learners who need to become fluent with at least the commonly-used commands, not given rituals to follow blindly.  Besides, it's pretty cheeky to think that we can improve on [Chacon](https://git-scm.com/book).

**Comment by goodvibes2** [comment]
Hi John,
I respectfully disagree with your comment about putting too much info about git into the wiki page.
I believe having to become a git expert before being able to make even a small documentation patch is a major disincentive for people to improve GnuCash.
Not understanding what each of the git commands is doing or why is incredibly frustrating.
I cannot improve on Chacon, but if we can provide a suggested easy path to follow which deals with the most common requirements, I think we should do it. I'll update the wiki to say this is a suggested path and not the only way to do things.
I tried to put in just the information I know I would have liked when I was trying to figure out what to do.
Searching through the git documentation each time one has a question is very slow, and the 'man git' info is incomprehensible until you know quite a bit about it.
Surely you'd prefer not to have to keep answering the same questions from most new contributors?

Did you wish me to remove the 'Patches' or 'Pull Requests' prefixes to the sub-section headings? I'm not sure from your answer.

Regards, Chris

**Comment by jralls** [comment]
I wish you to revert the whole thing. I thought that was obvious from my objection. If you want to create a "git for noobs" page and link to it from here and all of the other places that have step-by-step instructions I guess that would be OK. If you do, I suggest you lead off with instructions about getting git, cloning the repository, making a feature branch including whether to branch from maint or master, and making a commit. Those are the same for both patches and PRs. Then you can have a section about making a patch from your feature branch and another section about setting up a repo on Github, pushing the feature branch to it, making the PR, and later updates including force-pushing in response to comments.

I don't have to keep answering basic questions from new contributors because GnuCash is a sufficiently complex program that most new contributors already know git. It's now sufficiently deeply embedded in the OS landscape that nearly all programmers with enough experience to work on GnuCash already know how to work with git.

**Comment by goodvibes2** [comment]
A separate "git for noobs" page is fine by me. IIRC, I don't have permissions to create a new page - can you please?

**Comment by jralls** [comment]
You should be able to create pages now.

**Pull request closed without merging**
