### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by jralls** [comment]
Thanks, all.
@dawansv just three missing accelerators left in fr.po:
```
# src/gnome/glade-gnc-dialogs.c:1219 src/gnome/glade-gnc-dialogs.c:1240
# src/gnome/glade-gnc-dialogs.c:1276
#: gnucash/ui/gnc-plugin-business.ui:14
#: gnucash/ui/gnc-plugin-page-owner-tree.ui:23
#: gnucash/ui/gnc-plugin-page-owner-tree.ui:317
msgid "_New Customer…"
msgstr "Nouveau client…"

# src/gnome/glade-gnc-dialogs.c:1219 src/gnome/glade-gnc-dialogs.c:1240
# src/gnome/glade-gnc-dialogs.c:1276
#: gnucash/ui/gnc-plugin-business.ui:19
msgid "_Find Customer…"
msgstr "Chercher un client…"

# messages-i18n.c:338 po/guile_strings.txt:298
# src/gnome/glade-gnc-dialogs.c:635
#: gnucash/ui/gnc-plugin-page-account-tree.ui:150
#: gnucash/ui/gnc-plugin-page-account-tree.ui:254
#: gnucash/ui/gnc-plugin-page-register.ui:254
msgid "Stoc_k Split…"
msgstr "Division d'actions…"
```

**Comment by dawansv** [comment]
Will fix these tomorrow.

I am wondering if there is a trick to ensure translators don't use the same
acceleration key twice in the same context, besides locating the menu
itself in the app or source code. That part is certainly a challenge for
the translation.

**Comment by jralls** [comment]
Using context creates a new `msgid` for each context potentially plus one for no context. It would also be pretty annoying to users to have different accelerators for common actions depending on context.

**Comment by dawansv** [comment]
Oh that's right, I didn't think of same entries reused in different menus.
Then I guess it comes down to either looking at the code or winging it and
then fixing it afterwards when the conflict is more apparent in the menus
themselves.

**Pull request merged**
