### PR TITLE
[fr.po] update translations

### PR DESCRIPTION
**Pull request by christopherlam**
@YBSLE @svillemot est-ce que vous pouvez verifier mes traductions svp?
suivi de #429

### CODE REVIEW

**Comment by jralls** [comment]
@christopherlam are you going to run a spell-checker over your commit or should we just take it as-is?
BTW you didn't add yourself to the translators in the header.

**Comment by christopherlam** [comment]
I'll hopefully have feedback from a native soon... https://lists.gnucash.org/pipermail/gnucash-fr/2018-December/001187.html

**Comment by christopherlam** [comment]
I don't think I'll have any help for translations so I'll close this down for now.

**Comment by benjub** [comment]
@christopherlam If it's not too late and you can reopen this thread and tell me how to proceed, I can review your changes (I'm a French native speaker).

**Comment by fellen** [comment]
Why didn't you close the related https://bugs.gnucash.org/show_bug.cgi?id=750134?

**Comment by gjanssens** [comment]
> Why didn't you close the related https://bugs.gnucash.org/show_bug.cgi?id=750134?

If that referred to me - I don't see any mention of the bug on this PR. So I was not aware it was related to a bug report.

**Pull request closed without merging**
