### PR TITLE
cleanup investment-lots

### PR DESCRIPTION
**Pull request by christopherlam**
A few for @mcbridebt - some options are dependent on others. They should be modified to improve UX. Does this report have any other dependent options? Also some cleanup.

### CODE REVIEW

**Comment by mcbridebt** [comment]
> Does this report have any other dependent options?

All of the other options in the Chart tab are ignored when the "Show Chart" option is disabled.

BTW, a couple of weeks ago I created a PR to update the docs for this new report: https://github.com/Gnucash/gnucash-docs/pull/294

But there's been no response or activity on that PR. Did I create the PR incorrectly, or is typical for that repo to be handled more slowly? I notice the branch history seems to show much less activity that this one...

**Comment by jralls** [comment]
> BTW, a couple of weeks ago I created a PR to update the docs for this new report: https://github.com/Gnucash/gnucash-docs/pull/294

While it's true that Docs has a lot less activity than the code, the main problem is that I've been super busy the last few weeks and didn't get to it.

**Comment by mcbridebt** [comment]
No worries! I just wanted to make sure I didn't submit it incorrectly and put it into a "black hole" or something :-)

**Comment by christopherlam** [comment]
0decadd906

**Pull request merged**
