### PR TITLE
Pab/reports maint to pull v2

### PR DESCRIPTION
**Pull request by pbroadbery**
Cleaned up the commit history - so should be more readable.  
The first commit introduces a macro intended to replace the various guile-2 conditions scattered
about.  Not 100% sure it's in the right place and I don't mind backing it out if it's not the right idea.

### CODE REVIEW

**Comment by gjanssens** [comment]
I have tested this PR and the speed improvement is impressive. Thanks a lot for that.

I have no important remarks on pr in general, only a few minor things:
1. While currently used only in the reports area, none of the functions you split out in account.scm and split.scm are really reports specific. So I would find it more logical to move them into a more generic name space like the top-level "gnucash" name space (instead of under "gnucash report report-system"). IMO these two new files could be moved to src/scm and be treated like main.scm as far as installation is concerned.
2. My own quick tests showed no regressions compared to the original report. At the same time this is not a bugfix, but an enhancement of the existing report. So strictly according to our merge policy this pr should be added to the master branch instead of the maint branch. I'm in two minds about this myself however. I'd love to see this appear to our end users sooner than 2.8. I'll discuss this with the other devs.

**Comment by pbroadbery** [comment]
I'll re-roll the PR with the two files moved - wasn't sure on policy.  By
the way, would it make sense to use the gnc:module-begin-syntax macro I
added to gnc-module.scm in more places? If so I can do a second set of
patches.

**Comment by jralls** [comment]
As a general statement, any reduction in code duplication is good, so by all means do so.

I think the place for your account.scm and split.scm functions is src/engine/engine-utilities.scm, but if you feel strongly that they should stay in their own files then you could put them in src/engine and move the two very short functions from engine-utilities.scm into account.scm.

**Comment by gjanssens** [comment]
These are engine related functions indeed. So yes, somewhere in the engine directory would be good. However engine-utilties.scm is not a (guile) module, where account.scm and split.scm are. So if the functions are moved to engine-utilities.scm, they will have to be exported via engine.scm and loaded via 
(use-modules gnucash engine). Which kind of makes sense as well actually.

As for the branch, John and I agreed maint is ok.

**Pull request closed without merging**
