### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/gnucash/gnucash/) for GnuCash/Program.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
@gjanssens 
```
msgfmt -c --check-accelerators="_" --statistics po/nl.po 
po/nl.po:4087: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:5444: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:6206: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:13067: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:14980: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:15675: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:16592: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:16825: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:16835: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:16855: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:17174: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:17214: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:20775: msgstr has too many keyboard accelerator marks '_'
po/nl.po:21347: msgstr lacks the keyboard accelerator mark '_'
po/nl.po:23325: msgstr lacks the keyboard accelerator mark '_'
msgfmt: found 15 fatal errors
5373 translated messages, 12 fuzzy translations, 99 untranslated messages.
```

**Comment by fellen** [comment]
@gjanssens I reverted the "Test Term".
I watched the author was Anonymous <noreply@weblate.org> and for now would suspect, it was possible because you had admin rights.

Can you document, what you exactly did in https://wiki.gnucash.org/wiki/Weblate?

**Comment by fellen** [comment]
@milotype Thanks!

**Comment by gjanssens** [comment]
> @gjanssens I reverted the "Test Term".
> I watched the author was Anonymous [noreply@weblate.org](mailto:noreply@weblate.org) and for now would suspect, it was possible because you had admin rights.
> 
> Can you document, what you exactly did in https://wiki.gnucash.org/wiki/Weblate?

No that was done with my  account that didn't have admin rights.  I'll  document later.  Not sure why the author was "Anonymous" though.

**Comment by gjanssens** [comment]
> @gjanssens
> 
> ```
> msgfmt -c --check-accelerators="_" --statistics po/nl.po 
> po/nl.po:4087: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:5444: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:6206: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:13067: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:14980: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:15675: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:16592: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:16825: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:16835: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:16855: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:17174: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:17214: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:20775: msgstr has too many keyboard accelerator marks '_'
> po/nl.po:21347: msgstr lacks the keyboard accelerator mark '_'
> po/nl.po:23325: msgstr lacks the keyboard accelerator mark '_'
> msgfmt: found 15 fatal errors
> 5373 translated messages, 12 fuzzy translations, 99 untranslated messages.
> ```

So weblate's checks aren't perfect either... I'll look into those afterwards.

**Comment by fellen** [comment]
> So weblate's checks aren't perfect either... I'll look into those afterwards.

At least, until now I found no way to enable it. As it is a GTK only thing they probably didn't implement it. And the other tests are ways better.

**Comment by gjanssens** [comment]
@fellen I have fixed the  accelerator errors but what bothers me is that msgfmt  counts 12 fuzzy translations  and 99 untranslated messages while weblate suggests a full translation. Checking some of the  untranslated terms I do find them translated in weblate. So what is happening here ?

**Comment by gjanssens** [comment]
Hmm, not so clear. If I download the nl.po file directly from weblate I get the same result. Something's escaping me here. Anyway, for later.

**Pull request merged**
