### PR TITLE
Milotype hr 01

### PR DESCRIPTION
**Pull request by milotype**
These are several commits for the initial release of the croatian translation.

I don't have all the programing knowledge, so please take all necessary steps to enable the croatian version of GnuCash – for instance the Adjust po/CMakeLists.txt. I did not understand, if it's sufficient to simply add the hr-string into the file – so that's why I haven't changed that file.

If there is something else to translate, which is essential for the croatian release, please let me know.

### CODE REVIEW

**Comment by fellen** [comment]
Wow, much work!

while running the full test (https://wiki.gnucash.org/wiki/Translation#Desired), I get the following ouput:

> msgfmt -c --check-accelerators="_" --statistics hr.po 
> hr.po:2312: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
> hr.po:2326: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
> hr.po:2950: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
> hr.po:3458: msgstr lacks the keyboard accelerator mark '_'
> hr.po:3658: msgstr lacks the keyboard accelerator mark '_'
> hr.po:3666: msgstr lacks the keyboard accelerator mark '_'
> hr.po:4741: msgstr lacks the keyboard accelerator mark '_'
> hr.po:5301: msgstr lacks the keyboard accelerator mark '_'
> hr.po:6335: msgstr lacks the keyboard accelerator mark '_'
> hr.po:6888: msgstr lacks the keyboard accelerator mark '_'
> hr.po:6896: msgstr lacks the keyboard accelerator mark '_'
> hr.po:7826: msgstr lacks the keyboard accelerator mark '_'
> hr.po:11007: msgstr has too many keyboard accelerator marks '_'
> hr.po:12179: msgstr lacks the keyboard accelerator mark '_'
> hr.po:13376: msgstr lacks the keyboard accelerator mark '_'
> hr.po:14825: msgstr lacks the keyboard accelerator mark '_'
> hr.po:14830: msgstr lacks the keyboard accelerator mark '_'
> hr.po:15121: msgstr lacks the keyboard accelerator mark '_'
> hr.po:15206: msgstr lacks the keyboard accelerator mark '_'
> hr.po:15564: msgstr lacks the keyboard accelerator mark '_'
> hr.po:15635: msgstr lacks the keyboard accelerator mark '_'
> hr.po:15747: msgstr lacks the keyboard accelerator mark '_'
> hr.po:15841: msgstr lacks the keyboard accelerator mark '_'
> hr.po:15863: msgstr lacks the keyboard accelerator mark '_'
> hr.po:15909: msgstr lacks the keyboard accelerator mark '_'
> hr.po:15921: msgstr lacks the keyboard accelerator mark '_'
> hr.po:16148: msgstr lacks the keyboard accelerator mark '_'
> hr.po:16156: msgstr lacks the keyboard accelerator mark '_'
> hr.po:16164: msgstr lacks the keyboard accelerator mark '_'
> hr.po:16176: msgstr lacks the keyboard accelerator mark '_'
> hr.po:16218: msgstr lacks the keyboard accelerator mark '_'
> hr.po:16226: msgstr lacks the keyboard accelerator mark '_'
> hr.po:16254: msgstr lacks the keyboard accelerator mark '_'
> hr.po:16934: msgstr lacks the keyboard accelerator mark '_'
> hr.po:18819: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
> hr.po:19348: msgstr lacks the keyboard accelerator mark '_'
> hr.po:19930: msgstr lacks the keyboard accelerator mark '_'
> msgfmt: found 37 fatal errors
> 5259 translated messages.

The plural problem:
While in English the first form (singular) is only appiied on 1, it is replaced by a textual form ("one ", "a ", "the ") as part of the string.
But in hr it is applied on 1, 11, 21, ... So you must insert the format specifier (%d etc.) there, too.
See ru.po or sr.po as examples and the manual https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Translating-plural-forms.html#Translating-plural-forms.

For the keyboard accelerator mark  see underline in https://wiki.gnucash.org/wiki/Translation#Special_characters_and_other_tips.

More comments will follow later.

**Comment by milotype** [comment]
Thanx for the reply.
- I'll correct the singlular forms. 
I mistakenly presumed it would be an error, if the translated version has a format specifier in cases, where the original string doesn't ... my mistake!
- I'll correct the keyboard accelerator marks.

**Comment by milotype** [comment]
QUESTION: 
the following error has been marked in your output
>> hr.po:7826: msgstr lacks the keyboard accelerator mark ''

This one is just for the infos about the translator (in th espec it says, it should be used "In the headers of exported files"??? So where should I put the mark? Please see below …

#. Translators: the following string will be shown in Help->About->Credits
#. * Enter your name or that of your team and an email contact for feedback.
#. * The string can have multiple rows, so you can also add a list of
#. * contributors.
#: gnucash/gnome-utils/gnc-main-window.c:4576
msgid "translator_credits"
msgstr "Milo Ivir <mail@milotype.de>"

**Comment by milotype** [comment]
This one is peculiar. 
>> hr.po:11007: msgstr has too many keyboard accelerator marks ''
The underscore in the translation isn't meant as a mark. I use typographicaly correct (smart) double-quotation marks, as used in the croatian language. But obviously such *smart-quotes+underscore+smart-quotes* get misinterpreted as a keyboard accelerator mark !? This  doesn't happen with the (dumb) single quotes.
- Does that mean, that only *single quote+underscore+single quote* is allowed? 
- Are there other characters which have to be treated this way?

msgid: 
… underscores '_' in …
msgstr: 
… podvlakom „_” u …

**Comment by milotype** [comment]
All errors from your first report are done. Should I wait for your other comments, or should I commit the changes?

**Comment by fellen** [comment]
You can push your fixes because the po files then are ready. Yesterday I had no time to look in the templates.

**Comment by milotype** [comment]
Sorry, I'm not so firm with push/pull/and all of that. :-(
Should I:
a) make a new branch and commit, or
b) just exchange the .po file in my present branch "milotype-hr-01"

**Comment by fellen** [comment]
About the account templates:
1. I would prefer to name the directory hr (without region). Then also croatian speaking users of other regions will benefit. If we later get regional specific (business accounting) templates, we can modify the structure.
1. Can you remove the _hr from the template names, too?
1. If you, as suggested, started with accchrt_full, can you provide it, too?
1. Are you planning to add the missing modules, too, or are they not common in HR?

If you are ready, I will adjust the makefiles.

**Comment by fellen** [comment]
just commit it to this PR
* (select locally the milotype-hr-01 branch)
* commit the updated hr.po
* push it to your github repository
May be you have to use force in the push.
Then it should appear here.

**Comment by fellen** [comment]
> If there is something else to translate, which is essential for the croatian release, please let me know.

Essential not, but if you like, you can also (start to) translate 
* the website or
* the documentation, where the guide is more important than help.

**Comment by milotype** [comment]
Please note: 
I do not use a GitHub connection to my local computer. I only upload files/floders into folders of forks and branches on GitHub itelf.

1. I will rename the accounts directory hr (without region).
2. I will remove the _hr from the template names.
3. At present I cannot provide an accchrt_full (actually a business accchrt), because I'm not able to import CSV data, which contain croatian diacritics (as reported in Bug 797088 , https://bugs.gnucash.org/show_bug.cgi?id=797088).
4. I'll double-check the other modules, but I'm certain, that not all of them are relevant.

**Comment by milotype** [comment]
Question:
When preparing the accounts template files, should the <cmdty:space> be
a) ISO4217, or
b) CURRENCY
I'm asking, because the "iso_4217.po" (and "iso_4217.mo") files don't contain the croatian currency. But it exsists in the program's preferences, and can be chosen as "HRK (Croatian Kuna)". I couldn't find anything relevant on Bugzilla.

**Comment by jralls** [comment]
Looks like we're using ISO4217 in the C accounts. 

Perhaps you need to update your iso-codes installation, HRK *is* in the current [iso_4217.pot](https://salsa.debian.org/iso-codes-team/iso-codes/blob/master/iso_4217/iso_4217.pot#L245).

**Comment by milotype** [comment]
Hi John,
thank you for the link. I also found the hr.po file as well. That file contains the croatian translation for all defined currencies (170 english strings).

But where do all the currencies for GnuCash come from?

When i test my translations, I simply exchange the .mo files in my application folder:
/Applications/Gnucash.app/Contents/Resources/share/locale/hr/LC_MESSAGES/...
there are 3 files gnucash.mo, gtk30.mo and iso_4217.mo. I've converted this iso_4217.mo to a .po file – it contains 145 english strings (25 less than the debian file)

Even when I change the original iso_4217.mo in this folder, with the file from the debian (I use Poedit for .mo generation) GnuCash doesn't completely change the currencies list. Actually the pull-down lists in GnuCash's preferences window for reports and for accounts still contains e.g. DEM (Deutsche Mark) or YUM (Yugoslavian Dinar).
It also shows the HRK (Croatian Kuna). But in the .mo file it is specified as "Kuna", just as it is by the iso organisation.

Sorry for the lenghty post, but I really don't understand where all the currencies for GnuCash come from?

**Comment by jralls** [comment]
The currencies themselves are built from [iso-4217-currencies.xml](https://github.com/Gnucash/gnucash/blob/maint/libgnucash/engine/iso-4217-currencies.xml) that gets processed into a C file and compiled into libgncmod-engine.so. IIRC it's periodically copied from the ISO4217 website and we consider it utterly and preemptively authoritative for what is a currency.

Since you're working with MacOS GnuCash bundle the iso-codes version is stuck on version 3.67 until I can make time to complete and merge the [pipev branch](https://github.com/jralls/gtk-osx-build/tree/pipenv) for [gtk-osx](https://gitlab.gnome.org/GNOME/gtk-osx) to be able to handle building stuff with Python3 in a virtual environment. That version of iso-4217/hr.po has an empty msgstr for "Kuna", but ISTM that's OK because more recent versions just provide the same string.

**Comment by fellen** [comment]
> Actually the pull-down lists in GnuCash's preferences window for reports and for accounts still contains e.g. DEM (Deutsche Mark) or YUM (Yugoslavian Dinar).

Some long time users can have parts of their transactions recorded in legacy currencies. I still keep commodities, which I bought with DEM. So we can not remove them.
> Please note:
I do not use a GitHub connection to my local computer. I only upload files/floders into folders of forks and branches on GitHub itelf.

If I understand https://help.github.com/categories/managing-files-in-a-repository/ right, you can rename/move your files and dirs, upload newer versions ...
So just try it on this branch.

**Comment by milotype** [comment]
Update finished! 
If necessary, please check and release ;-)

**Comment by fellen** [comment]
Just to keep you informed:
While checking your files, I find parts in https://wiki.gnucash.org/wiki/Translation, which still require updates after we changed our https://wiki.gnucash.org/wiki/Build_Tools. But work is in progress ...

**Comment by fellen** [comment]
The glossary is syntactical correct, but the normal po still has 3 issues:

>msgfmt -c --check-accelerators="_" --statistics hr.po
hr.po:3638: msgstr lacks the keyboard accelerator mark '_'
hr.po:7788: msgstr lacks the keyboard accelerator mark '_'
hr.po:10957: msgstr has too many keyboard accelerator marks '_'
hr.po:16166: msgstr lacks the keyboard accelerator mark '_'
msgfmt: found 4 fatal errors

7788 is "translator_credits" which should be ignored
10957: „ime_datoteke-datum-format“ is the culprit
For the other 2 you have the choice, how to fix them.

**Comment by fellen** [comment]
Thanks, so the program translation is complete.

What are your plans about the missing templates: brokerage, business, childcare, fixedasset, retirement, spouse{inc|retire}, {car|edu}loan? 
Usually we suggest to translate full at first and then copy the translations in the other parts.

Are you planing to add them?
You can also say: I do not need that parts. somebody else can translate them later.

**Comment by milotype** [comment]
I'm not planing to add more at this stage. But I'll do more at a later time. Is there a timeline for a next release? So I could plan to finish those files until then.

IMO, we should now finish this "Milotype hr 01 #455" commit. What do you think?

NOTE: When merging, please remember to use only the "hr" folder for the templates. I do not know how to delete the "hr_HR" folder, which I created first.

**Comment by fellen** [comment]
After adjusting the CMakeLists, I am able to test your accounts and have 2 notes:
1.Suggestion: Mark "Kapital" as placeholder. You will not want transactions in top level accounts.
2. Why is "Temeljni kapital" no subaccount of Kapital? Did you use different GUIDs?

**Comment by fellen** [comment]
> I'm not planing to add more at this stage. But I'll do more at a later time. Is there a timeline for a next release? So I could plan to finish those files until then.

https://wiki.gnucash.org/wiki/Release_Schedule#Current_Stable_3.x
> IMO, we should now finish this "Milotype hr 01 #455" commit. What do you think?

OK
> NOTE: When merging, please remember to use only the "hr" folder for the templates. I do not know how to delete the "hr_HR" folder, which I created first.

Already done in my local branch.

**Comment by milotype** [comment]
Thank you for catching the mistakes. 
- I've corrected your proposed changes. 
- I did some other minor corrections on the other files.
- I added two more acconut files: eduloan + fixedassets

**Comment by fellen** [comment]
OK, it got finally commited with commit 49ebc96.
Thank You!

**Comment by fellen** [comment]
Can you redo your changes from yesterday in a new PR?
Because you suggested to close this PR, I didn't look here.

And can you try to give your commits more meaningfull messages?
I.e. "Update croatian common template" or "Adding croatian EduLoan template".
Remember this messages will get published in the git history and partial also in the release notes.

Ideally you would, while adding files, also uncomment the respective line in CMakeFiles.txt (in the same directory) in the same commit.

**Comment by gjanssens** [comment]
Never mind. I have pulled in the remaining commits, squashed them together and pushed the changes upstream. Everything in this PR is now merged. Thanks!

**Pull request closed without merging**
