### PR TITLE
Modularisation guile code

### PR DESCRIPTION
**Pull request by christopherlam**
I think this is now _ready_ for more scrutiny. Most warnings removed. Some `format` warnings remain.

Top-level modules:

`(gnucash core-utils)` `(gnucash engine)` `(gnucash app-utils)` `(gnucash qif-import)` `(gnucash report)` `(gnucash reports)`

`app-utils`, `qif-import`, `report` have submodules. `app-utils` and `report` will re-export submodules public functions.

`qif-import` modularisation isn't yet debugged especially C code calling scheme.

### CODE REVIEW

**Comment by christopherlam** [comment]
Ready for review... interestingly `fin.scm` is not, and should not be a module. It causes weird crashes(*) otherwise.

(*) crashes on startup with unbound identifier `gnc:report-template-new-options/report-guid`, only if there are tabbed reports upon load.

**Comment by jralls** [comment]
Well, it builds on everything, which is progress, but it has some really strange test failures... strange both because they reflect computational errors--e.g. a calculated amount is wrong--and because on some builds (Ubuntu-20.04 on github-actions and Ubuntu-18.04 on Travis) they pass.

The code generally looks good, but I think you should explain either in a comment or a commit message why you sometimes use `(define-module foo #:export bar)` and sometimes `(define module foo)(export bar)`.

**Comment by christopherlam** [comment]
Weird calculation errors indeed. I'll diagnose remotely via some debug commits.

`#:export (list-of-symbols)` is the modern variant, however I think it's best to use `(export symbol)` because it's much easier when grepping symbols.

**Comment by christopherlam** [comment]
@jralls I think Ive isolated this bug to the old friend TZ;  `(gnc_dmy2time64 1 1 1970)` returns
* -28800 on my machine (with TZ=GMT+8 or TZ=GMT-8) or on travis-ubuntu
*  28800 on travis-arch

**Comment by jralls** [comment]
@christopherlam Too much to put in IRC. I don't think the problem is timezone, the difference in the transaction dates is too big. Besides, when I run `TZ=Australia/Perth ctest -V -R test-report-utilities` it still fails with the same values except for the gmt offset test. That's on Fedora 33 and guile-2.0.14 and Arch Linux with guile-2.2.6.

On Debian unstable with guile-3.0.4 it passes with TZ=Australia/Perth and only the gmt offset test fails without it.

Back on Fedora33 I made some changes to see what's going on:
```
diff --git a/gnucash/report/test/test-report-utilities.scm b/gnucash/report/test/test-report-utilities.scm
index a9390bb4b..14a6e2b58 100644
--- a/gnucash/report/test/test-report-utilities.scm
+++ b/gnucash/report/test/test-report-utilities.scm
@@ -637,25 +637,25 @@
         (gnc:account-accumulate-at-dates bank1 dates))
 
       (env-transfer env 15 01 1970 income bank1 10)
-      (env-transfer env 15 02 1970 income bank1 10)
-      (env-transfer env 15 03 1970 income bank1 10)
-      (let ((clos (env-transfer env 18 03 1970 income bank1 10)))
+      (env-transfer env 15 02 1970 income bank1 20)
+;      (env-transfer env 15 03 1970 income bank1 40)
+      (let ((clos (env-transfer env 18 03 1970 income bank1 80)))
         (xaccTransSetIsClosingTxn clos #t))
 
-      (env-transfer env 15 12 1969 income bank2 10)
-      (env-transfer env 17 12 1969 income bank2 10)
-      (env-transfer env 15 02 1970 income bank2 10)
+      (env-transfer env 15 12 1969 income bank2 11)
+      (env-transfer env 17 12 1969 income bank2 21)
+      (env-transfer env 15 02 1970 income bank2 41)
 
-      (env-transfer env 15 03 1970 income bank3 10)
+      (env-transfer env 15 03 1970 income bank3 14)
 
-      (env-transfer env 15 01 1970 income bank4 10)
+      (env-transfer env 15 01 1970 income bank4 18)
 
       (test-equal "1 txn in each slot"
-        '(("USD" . 0) ("USD" . 10) ("USD" . 20) ("USD" . 40))
+        '(("USD" . 0) ("USD" . 10) ("USD" . 30) ("USD" . 110))
         (map monetary->pair (gnc:account-get-balances-at-dates bank1 dates)))
 
       (test-equal "1 txn in each slot, tests #:split->amount to ignore closing"
-        '(("USD" . 0) ("USD" . 10) ("USD" . 20) ("USD" . 30))
+        '(("USD" . 0) ("USD" . 10) ("USD" . 30) ("USD" . 30))
         (map monetary->pair
              (gnc:account-get-balances-at-dates
               bank1 dates #:split->amount
@@ -664,31 +664,31 @@
                      (xaccSplitGetAmount s))))))
 
       (test-equal "2 txn before start, 1 in middle"
-        '(("USD" . 20) ("USD" . 20) ("USD" . 30) ("USD" . 30))
+        '(("USD" . 11) ("USD" . 32) ("USD" . 73) ("USD" . 73))
         (map monetary->pair (gnc:account-get-balances-at-dates bank2 dates)))
 
       (test-equal "1 txn in late slot"
-        '(("USD" . 0) ("USD" . 0) ("USD" . 0) ("USD" . 10))
+        '(("USD" . 0) ("USD" . 0) ("USD" . 0) ("USD" . 14))
         (map monetary->pair (gnc:account-get-balances-at-dates bank3 dates)))
 
       (test-equal "1 txn in early slot"
-        '(("USD" . 0) ("USD" . 10) ("USD" . 10) ("USD" . 10))
+        '(("USD" . 0) ("USD" . 18) ("USD" . 18) ("USD" . 18))
         (map monetary->pair (gnc:account-get-balances-at-dates bank4 dates)))
 
       (test-equal "1 txn in each slot"
-        '(#f 10 20 40)
+        '(#f 10 30 110)
         (gnc:account-accumulate-at-dates bank1 dates))
 
       (test-equal "2 txn before start, 1 in middle"
-        '(20 20 30 30)
+        '(11 32 73 73)
         (gnc:account-accumulate-at-dates bank2 dates))
 
       (test-equal "1 txn in late slot"
-        '(#f #f #f 10)
+        '(#f #f #f 14)
         (gnc:account-accumulate-at-dates bank3 dates))
 
       (test-equal "1 txn in late slot, tests #:nosplit->elt"
-        '(x x x 10)
+        '(x x x 14)
         (gnc:account-accumulate-at-dates bank3 dates #:nosplit->elt 'x))
 
       (test-equal "1 txn in late slot, tests #:split->elt"
@@ -696,7 +696,7 @@
         (gnc:account-accumulate-at-dates bank3 dates #:split->elt (const 'y)))
 
       (test-equal "1 txn in early slot"
-        '(#f 10 10 10)
+        '(#f 18 18 18)
         (gnc:account-accumulate-at-dates bank4 dates))
 
       ;; Tests split->date sorting. note the 3 txns created below are
@@ -726,7 +726,7 @@
         (set-reconcile txn3 (gnc-dmy2time64 1 5 1971))
 
         (test-equal "sort by reconcile-date"
-          '(#f 5 16)
+          '(#f 3 5)
           (gnc:account-accumulate-at-dates
            bank1 (list (gnc-dmy2time64 1 3 1971)
                        (gnc-dmy2time64 1 4 1971)
```
That gets everything to pass. By using different values for each transaction it becomes easy to see what transactions are collected in each test. Note near the top, 
```
-      (env-transfer env 15 03 1970 income bank1 10)
...
+;      (env-transfer env 15 03 1970 income bank1 40)
```
Uncommenting that changes the fourth "1 txn in each slot" and "1 txn in each slot, tests #:split->amount to ignore closing" to 70. That suggested that only 3 transactions can be added; I did some additional tests on that, adding more transactions on various dates and found that to be the case: Only the first 3 transactions matter; date doesn't.

Similarly the `bank2` transactions register only the first transaction in 1969 until the second date; making the second entry earlier than the first switches the value but changing the date range from 1/1 - 1/4 to 1/2 - 1/5 doesn't.
If I add a test
```
      (test-equal "scratch test" '(("USD" . 11)) (map monetary->pair (gnc:account-get-balances-at-dates bank2 (list (caddr dates)))))
```
It passes.

That leads me to think that there's some subtle difference between the way gnc:account-get-balances-at-dates is working in guile 2.x vs. guile 3.0.

**Comment by jralls** [comment]
@christopherlam Why don't you set up a build with guile-2.2 so that you can test/debug on you're own machine?

**Comment by jralls** [comment]
Now you need
```
diff --git a/gnucash/gnome-utils/CMakeLists.txt b/gnucash/gnome-utils/CMakeLists.txt
index ba03bc7f8..908ce932b 100644
--- a/gnucash/gnome-utils/CMakeLists.txt
+++ b/gnucash/gnome-utils/CMakeLists.txt
@@ -261,17 +261,16 @@ install(FILES ${gnome_utils_HEADERS} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/gnu
 set(GUILE_DEPENDS      gnc-gnome-utils scm-engine scm-app-utils)
 
 gnc_add_scheme_targets(scm-gnome-utils-1
-    SOURCES gnome-utils.scm
-    OUTPUT_DIR gnucash
-    DEPENDS "${GUILE_DEPENDS}")
-
-
-gnc_add_scheme_targets(scm-gnome-utils-2
     SOURCES gnc-menu-extensions.scm
     OUTPUT_DIR "gnucash/gnome-utils"
     DEPENDS "${GUILE_DEPENDS}"
     MAKE_LINKS)
 
+gnc_add_scheme_targets(scm-gnome-utils-2
+    SOURCES gnome-utils.scm
+    OUTPUT_DIR gnucash
+    DEPENDS "scm-gnome-utils-1")
+
 add_custom_target(scm-gnome-utils ALL DEPENDS scm-gnome-utils-2 scm-gnome-utils-1)
 
 set_local_dist(gnome_utils_DIST_local CMakeLists.txt ${gnome_utils_SOURCES} ${gnome_utils_HEADERS}
diff --git a/libgnucash/app-utils/CMakeLists.txt b/libgnucash/app-utils/CMakeLists.txt
index 2cc9c82f1..70012b4f8 100644
--- a/libgnucash/app-utils/CMakeLists.txt
+++ b/libgnucash/app-utils/CMakeLists.txt
@@ -170,7 +170,6 @@ install(FILES ${app_utils_HEADERS} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/gnuca
 
 set (app_utils_SCHEME_1
     business-options.scm
-    business-prefs.scm
     c-interface.scm
     date-utilities.scm
     options.scm
@@ -191,11 +190,15 @@ gnc_add_scheme_targets(scm-app-utils-1
     OUTPUT_DIR "gnucash/app-utils"
     DEPENDS "${GUILE_DEPENDS}"
     MAKE_LINKS)
+  gnc_add_scheme_targets(scm-bus-prefs
+    SOURCES "business-prefs.scm"
+    OUTPUT_DIR "gnucash/app-utils"
+    DEPENDS "scm-app-utils-1")
 
 gnc_add_scheme_targets(scm-app-utils-2
     SOURCES "${app_utils_SCHEME_2}"
     OUTPUT_DIR "gnucash"
-    DEPENDS "scm-app-utils-1")
+    DEPENDS "scm-bus-prefs")
 
 # Module interfaces deprecated in 4.x, will be removed for 5.x
 gnc_add_scheme_deprecated_module (OLD_MODULE "migrate-prefs")
```

To get it to build all the way.
But there's a problem with test-stress-options taking forever; I killed it after 52M of output. The repeating test writes
```
98: d0.0328 t191.162: ('split-date 35377140 Split<d:02/14/71,acc:Wallet,amt:$20.00,val:$20.00>)
98: d0.0153 t191.178: ('dates (list 31132799 31219199 31305599 31391999 31478399 31564799 31651199 31737599 31823999 31910399 31996799 32083199 32169599 32255999 32342399 32428799 32515199 32601599 32687999 32774399 32860799 32947199 33033599 33119999 33206399 
```
over and over.

**Comment by christopherlam** [comment]
> Now you need
> (snip)
> To get it to build all the way.

Added.

> But there's a problem with test-stress-options taking forever; I killed it after 52M of output.

This was due to increased logging in gnc:account-accumulate-at-dates, now removed.

**Comment by jralls** [comment]
Still failing in CI :-(. Failed on guile-3 because you left in my test changes that got test-report-utilities to pass on guile 2.2, but other things failed as well. I'll diagnose tomorrow.

**Comment by christopherlam** [comment]
When writing test-report-utilities' gnc:account-accumulate-at-dates I designed it to cover most/all combinations of date-boundaries and splits. e.g. dates at 1-jan, 1-feb, 1-mar, and splits on 15-jan, 15-mar, 17-mar. What I'm not sure I've tested is cases whereby split->date falls exactly on the date-boundary. I haven't analysed your version of these tests.

**Comment by jralls** [comment]
Those tests would be TZ-sensitive. I didn't change that. The interesting change I made was to the amounts so that it's easy to see which splits are included in any particular balance; the problematic changes I made were to match the expectation to the incorrect values generated by guile-2.x; it's those that are failing in the guile-3.0 CI test.

**Comment by jralls** [comment]
Almost there. You need to remove  3f6225e and do one more Cmake fixup:
```
diff --git a/gnucash/report/reports/standard/test/CMakeLists.txt b/gnucash/report/reports/standard/test/CMakeLists.txt
index c6558c9f9..0875bcbf1 100644
--- a/gnucash/report/reports/standard/test/CMakeLists.txt
+++ b/gnucash/report/reports/standard/test/CMakeLists.txt
@@ -34,7 +34,7 @@ set(GUILE_DEPENDS
   scm-core-utils
   scm-test-report
   scm-reports
-  scm-reports-standard-with-exposed-generator-links
+  scm-reports-standard-with-exposed-generator
   scm-report-stylesheets
   )
 
```
That gets everything built and passing for me with guile-2.2.

Then `git rebase -i` to combine 38ebe4481 as a fixup of 948f9652f. I'd also combine the above patch, 4dc140a, and 6929080 as a single commit and put it along with bd40058 at the beginning instead of the end of the patch set.

**Pull request merged**
