### PR TITLE
[master] sample-graphs.scm add tutorial for html-chart

### PR DESCRIPTION
**Pull request by christopherlam**
Add option in `sample-graphs.scm` to show html-chart tutorial.
Is it worth while completing?

image

### CODE REVIEW

**Comment by jralls** [comment]
More documentation is good, but I'm not sure that a report is the right way to do it. It's not really where someone would go looking. What about putting the narrative part in [Custom Reports](https://wiki.gnucash.org/wiki/Custom_Reports) with a pointer to the sample code in Github?

**Comment by christopherlam** [comment]
Fair comment. Some good scheme tricks using `local-eval` in this branch converting data to string and to code :). There's already section in wiki/Custom Reports for html-barchart. Herewith the final tutorial, to be added to wiki:

image

**Comment by jralls** [comment]
That seems a lot clearer than what's there now.

**Comment by christopherlam** [comment]
https://wiki.gnucash.org/wiki/Tutorial_for_html-chart.scm#Tutorial_to_html-chart.scm all done thanks pandoc

**Pull request closed without merging**
