### PR TITLE
fixed wrong translation + a bit more

### PR DESCRIPTION
**Pull request by akadig**
data is not date
rewording

### CODE REVIEW

**Comment by gjanssens** [comment]
Thank you for your pull request.

Currently all translation work should be done on the maint branch, not the master branch. For more information, refer to [our Translation wiki page](http://wiki.gnucash.org/wiki/Translation). Since the changes are very small and trivial I have reapplied the changes to maint myself.

Secondly, I note the last translator for the Russian language was @zeldigas. If you intend to continue contributing to the Russian translation (which I encourage you to do!), please contact him to coordinate further. It would be a pity if your independently created translations would clash at some point.

Thanks again!

**Comment by zeldigas** [comment]
@akadig @gjanssens I'm currently working on big translation update. Branch to track changes: https://github.com/zeldigas/gnucash/tree/dev/russian_translation_update

**Comment by gjanssens** [comment]
Thanks for the heads up and good to hear this!

I will refrain from committing any other Russian translation fixes until I hear back from you.

**Comment by akadig** [comment]
@gjanssens Thank you for your assistance and acceptance of fixes.
Sorry, that it was committed in to the wrong branch. I just saw a typo and decided on a quick fix. Especially because it was already in the translated fragment.
Nevertheless, I'll look into that wiki page more closely.

Of course, if I'm going to translate, or to do more than just correct small errors here and there, I certainly will contact the translators.

@zeldigas It's great! If I'm going to translate, then I for sure will cooperate with you.

**Comment by zeldigas** [comment]
@akadig I'll apply your "data format:" translation fix

**Pull request closed without merging**
