### PR TITLE
Income GST statement

### PR DESCRIPTION
**Pull request by christopherlam**
#202 rises from the ashes again. I've removed all trailing whitespace.

### CODE REVIEW

**Comment by christopherlam** [comment]
PS I still cannot reproduce the gnc-make-monetary errors.

**Comment by gjanssens** [comment]
@christopherlam I sent you a test data file a few days back. Did you receive it ?

It only has one transaction. When I run your report and configure it such that this transaction is included in the report, the gnucash trace file will have these warnings:

```;;; WARNING (wrong arguments for gnc:make-gnc-monetary:  #<swig-pointer 
gnc_commodity * 4b2e970> #f)

;;; WARNING (wrong arguments for gnc:make-gnc-monetary:  #<swig-pointer 
gnc_commodity * 4b2e970> #f)

;;; WARNING (wrong arguments for gnc:make-gnc-monetary:  #<swig-pointer 
gnc_commodity * 4b2e970> #f)

;;; WARNING (wrong arguments for gnc:make-gnc-monetary:  #<swig-pointer 
gnc_commodity * 4b2e970> #f)

;;; WARNING (wrong arguments for gnc:make-gnc-monetary:  #<swig-pointer 
gnc_commodity * 4b2e970> #<<gnc-monetary> commodity: #<swig-pointer 
gnc_commodity * 4b2e970> amount: #<<gnc-numeric> num: -10000 denom: 100>>)

;;; WARNING (wrong arguments for gnc:make-gnc-monetary:  #<swig-pointer 
gnc_commodity * 4b2e970> #<<gnc-monetary> commodity: #<swig-pointer 
gnc_commodity * 4b2e970> amount: #<<gnc-numeric> num: -10000 denom: 100>>)```

**Comment by christopherlam** [comment]
Whoops. Gmail didn't like your email. I'll check tonight. I'm working on
fixing the sorting and grouping algorithm in my private branch.

**Comment by christopherlam** [comment]
I think it should be fine now :)

**Comment by gjanssens** [comment]
The gnc:make-monetary errors are gone indeed. I didn't know they only appeared on the linux terminal because I have redirected my gnucash trace output there as well... Glad you found it in the end :)

I see one more issue using my old test data: in my case bills are incorrectly interpreted. For bills my transactions look like this:

    A/P                   121,- (Debit)
    Liabilities:Vat-21%    21,- (Credit)
    Expense:SomeExp       100,- (Credit)

Liabilities:Vat-21% is marked as a tax account. This results in a line on the report like this:

Date | Num | Description | Memo/Notes | Account | Total Sales | Net Sales | Tax on Sales | Total Purchases | Net Purchases | Tax on Purchases
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
14/02/2007 | 000356 | Bla |   | Expense:SomeExp | € 21,00- |   | € 21,00- | € 100,00 | € 100,00 |

With the transaction above it should be 

Date | Num | Description | Memo/Notes | Account | Total Sales | Net Sales | Tax on Sales | Total Purchases | Net Purchases | Tax on Purchases
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
14/02/2007 | 000356 | Bla |   | Expense:SomeExp |   |   |    | € 121,00 | € 100,00 | € 21,00

A peculiarity about my book: I am using the same tax account for income and expenses. That may break some assumptions you made in your code. Can you check this out ?

I have pushed your PR after a rebase to unstable. It's definitely far enough to be ready for wider audience testing. Any follow-ups can go into a new PR. Thanks for your work!

**Comment by christopherlam** [comment]
Yes the assumption is that the tax accounts selected will be judged to belong to Expense or Income according to whether they’re themselves a Liability or Asset.
After all, you pay & expense your bills (+VAT) and expect VAT back. Therefore the VAT must be classed an asset.
If the same tax account is used for both income/expense then this report will not be very accurate. It would be impossible to distinguish between an income/expense tax incurred or the opposite expense/income refund. But the final VAT totals will still match up.
HTH, Chris

**Comment by miguelmoura** [comment]
Sorry, but iam trying to removed me from this mail list And thread but so
far, i Was unable to do it.

Please, remove me from this thread and mail list.

Thanks
Miguel

Em 17/09/2017 02:58, "christopherlam" <notifications@github.com> escreveu:

PS I still cannot reproduce the gnc-make-monetary errors.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Gnucash/gnucash/pull/203#issuecomment-330007026>, or mute
the thread

**Comment by gjanssens** [comment]
@miguelmoura The message you replied to is not from a mail list. It comes from [a conversation on github](https://github.com/Gnucash/gnucash/pull/203). I have no idea how you got subscribed to notifications on this conversation. However you are the only one able to stop receiving them.

Did you try to click the link at the end of the mail (the one about "mute the thread") ? If that failed you can also lick on the link I mentioned in the first paragraph and on the right hand side of the page you will find an "unsubscribe" button under notification. If you click it, you should no longer receive mails in this conversation (which has pretty much ended anyway). If you receive more mails from github, you may have subscribed to gnucash in general on that website.

**Comment by gjanssens** [comment]
On donderdag 21 september 2017 14:43:08 CEST christopherlam wrote:
> Yes the assumption is that the tax accounts selected will be judged to
> belong to Expense or Income according to whether they’re themselves a
> Liability or Asset. After all, you pay & expense your bills (+VAT) and
> expect VAT back. Therefore the VAT must be classed an asset. If the same
> tax account is used for both income/expense then this report will not be
> very accurate. It would be impossible to distinguish between an
> income/expense tax incurred or the opposite expense/income refund. But the
> final VAT totals will still match up. HTH, Chris

I'm not sure this is a correct assumption in all circumstances and for sure 
when the business features are used there is no ambiguity as you can deduce 
the tax direction from the type of invoice (is_customer_document).

However I'm fine leaving the report as it is now. And I see you have clearly 
documented this on the empty report page. So consider this finished.

**Pull request closed without merging**
