### PR TITLE
add tests for report options

### PR DESCRIPTION
**Pull request by GnuFiBux**
Hi,

here is my next follow-up on Bug787401 "tests for the report system", this time for report options.

### CODE REVIEW

**Comment by jralls** [comment]
One doesn't normally waste test time on simple setters. Is there a point to these tests?

**Comment by jralls** [comment]
> ideally a unit test would test the functionality of a module rather than its implementation...we want to test the function does exactly what we want..."

Not quite. A test obviously tests the implementation, it being a bit difficult to test anything else. The objective is to ensure that the implementation achieves the desired functionality (as @christopherlam says in the later bit). My point is that if a function simply takes a list of arguments and assigns them to a set of variables there's not much point in testing it: It can be easily determined by inspection that it does that. Expanding, if a function starts off setting a bunch of variables and then does other stuff there's no need to test the setting, get straight to the other stuff.

**Comment by GnuFiBux** [comment]
Hi John, Christopher,
thanks for your feedback.
Many interesting aspects that I think are good to open endless philosophical discussions.
One thing I totally agree with: this set of tests is not complete.

Not to waste even more time on those kind of discussions:
Consider it an offer. Take it or leave it.
Let's see if I can make time to "bug" you with the findings that came of of this waste. I think I had the one or the other spot...

**Comment by jralls** [comment]
It's a very practical issue: Unnecessary/not-useful tests add code clutter and take additional run time with no payback.
Since the tests all pass I will be interested to see your bug reports, and since I don't see any benefit to the tests I'll "leave it".

**Pull request closed without merging**
