### PR TITLE
Bug 798749 - Fails to read gsettings on startup

### PR DESCRIPTION
**Pull request by gjanssens**
This alternative implementation gets rid of caching the GSettings objects except for keeping track of signal handlers.

Will slow down GSettings interactions, but in general they are already that fast, there is no noticeable side effect.

### CODE REVIEW

**Comment by jralls** [comment]
Works on Windows.

**Comment by Bob-IT** [comment]
@gjanssens 
I have pushed my changes but have noticed that there is a segfault on exit...

`Thread 1 "gnucash" received signal SIGSEGV, Segmentation fault.
0x00007ffff6f085dc in gnc_gsettings_remove_cb_by_func (schema=0x7ffff7a7a26f "history", key=0x0, func=0x7ffff7a32ca0 <gnc_plugin_history_list_changed>, user_data=0x555555c5c330) at /var/tmp/portage/app-office/gnucash-4.901/work/gnucash-4.901/libgnucash/app-utils/gnc-gsettings.cpp:274
274	        if (!G_IS_SETTINGS (settings_ptr))`

**Comment by gjanssens** [comment]
@Bob-IT I got a similar crash yesterday, but not today. I am in the process of rewriting the signal handler tracking, so that may fix the segfault.

**Comment by gjanssens** [comment]
@Bob-IT can you retest with the most recent master branch ?

**Comment by Bob-IT** [comment]
@gjanssens  Looks OK, now to see what you have changed and get an idea of how it works now.

**Pull request merged**
