### PR TITLE
Qofcollection C++ implementation

### PR DESCRIPTION
**Pull request by tkdchen**
Major changes to QofCollection

1. new C++ class of QofCollection in namespace `gnucash::qof`
2. unit tests for legal QofCollection C implementation, and fix type conversion by using Glib's `GPOINTER_TO_INT` and `GINT_TO_POINTER` instead of (gint *).
3. same unit tests in C++ to QofCollection class to ensure C++ implementation does the same things as what C implementation does.

### CODE REVIEW

**Comment by jralls** [comment]
No. Totally, completely wrong. This is just dressing up the existing C code to make it vaguely resemble C++98. It doesn't even move us toward replacing GLib.

We want a template implementation that uses std::vector. That was specifically the direction I gave you two months ago. The driving principle of the C++ rewrite is to eliminate the dependence on Gnome, so using GHashMap would be the wrong answer even if using a C container in C++ was a good idea, which it isn't.

**Comment by tkdchen** [comment]
Sorry for the mistakes. I'll make following changes to correct

- replace GHashTable with std::map<GncGUID, QofInstance>
- rewrite unit tests of QofCollection class based on gtest.

Thanks!

**Comment by jralls** [comment]
No, you don't get it. Picking the wrong container is only part of the problem. I'll put it on a separate line so you don't gloss over it.

You didn't write it in C++.
You wrote it in C dressed up to look sort of like C++.
We're not interested in that. Sorry.

**Comment by tkdchen** [comment]
Thank you Mr. Ralls for pointing these problems out and giving useful guidance and patience to me. :)

**Pull request closed without merging**
