### PR TITLE
Asan

### PR DESCRIPTION
**Pull request by christopherlam**
(just to take advantage of github ci)

### CODE REVIEW

**Comment by christopherlam** [comment]
will ci in own branch

**Comment by jralls** [comment]
[WTF?](https://github.com/Gnucash/gnucash/pull/1802)

**Comment by christopherlam** [comment]
It's to get github ci asan logfiles easily! I'll check on my own branch https://github.com/christopherlam/gnucash/pull/10 instead of here.

**Comment by jralls** [comment]
You don't need CI to run asan, just tell cmake `-DCMAKE_BUILD_TYPE=Asan`. Then you can run and work on a single test.

**Pull request closed without merging**
