### PR TITLE
Use official language code 'cs_CZ' as subdir name for czech republic account templates.

### PR DESCRIPTION
**Pull request by rhabacker**
This fixes a KMymoney issue not been able to display language in cleartext.

### CODE REVIEW

**Comment by rhabacker** [comment]
After seeing the build failures I recognized that the language is uses in more build system related files, which I'm going to fix.
There are several renames required, should I make one big patch or for each language a single patch including all related ?

**Comment by jralls** [comment]
You have this backwards. If KMyMoney is going to borrow our account templates then KMyMoney has to follow *our naming scheme*, not the other way around.

**Comment by rhabacker** [comment]
This bug has been detected with kmymoney and the requested changes are in the gnucash locale specification according to https://wiki.gnucash.org/wiki/Locale_Settings#Language_tags, so where is the problem ?

**Comment by derekatkins** [comment]
This is not a bug in GnuCash.  It may be a bug in that KMyMoney does not fall back properly.

Official Czech language is cs.  Using cs.po et al is valid for all regions using the Czech language.  Using cs_CK is only required *IF* there are multiple regions using the same language that require differentiation, but the specification states to fall back from <lang>_<region> to <lang> if there is no <lang>_<region> file(s) found.  For example, there are different spellings of color (vs. colour) in en_US vs en_UK which necessitate separate configs.  But for cs, da, ko, nb, and ja, there is absolutely no need for differentiation at this time so using the fallback from cs_CK to cs is legal per the specification, and would probably cause problems if there *WERE* regionalization.

If at some point in the future there is a need for, e.g. ja_US in addition to ja_JP, then, and only then, would it make sense to rename and move stuff around.  But I don't see that happening for these languages.

**Comment by jralls** [comment]
> This bug has been detected with kmymoney and the requested changes are in the gnucash locale specification according to https://wiki.gnucash.org/wiki/Locale_Settings#Language_tags, so where is the problem?

Two problems:

1. The GnuCash wiki isn't a specification. There is no specification.
2. The account files are templates intended for the use of GnuCash and GnuCash alone. Even to the limited extent that we publish an API (and we make *no* stability guarantees about that API) for GnuCash users to script GnuCash, those templates aren't part of published API.

If KMyMoney wants to use GnuCash resources in compliance with copyright law and the GPL, that's fine, but it's not reasonable to expect GnuCash to change anything or keep anything stable to support KMyMoney's usage. KMyMoney can either copy the bits they want into their own code base and modify that as it pleases them or they can code to what's in GnuCash and live with the fact that we may change things at whim and won't care if it breaks KMyMoney.

**Comment by rhabacker** [comment]
Can we agree that on a recent linux system the command line util 'locale', which is provided by glibc, tells us the truth about locals ? 

On opensuse Leap 42.1 I get for  'locale -a | grep da'
da_DK
da_DK.utf8

Checking the related locale with 
xxx@yyy:~> LANG=da_DK locale 
LANG=da_DK
LC_CTYPE="da_DK"
LC_NUMERIC=nds_DE.UTF-8
LC_TIME="da_DK"
LC_COLLATE="da_DK"
LC_MONETARY="da_DK"
LC_MESSAGES="da_DK"
LC_PAPER="da_DK"
LC_NAME="da_DK"
LC_ADDRESS="da_DK"
LC_TELEPHONE="da_DK"
LC_MEASUREMENT="da_DK"
LC_IDENTIFICATION="da_DK"
LC_ALL=

works as expected.  Then I tried the abbreviated language code:
xxx@yyy:~> LANG=da locale 
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=da
LC_CTYPE="da"
LC_NUMERIC=nds_DE.UTF-8
LC_TIME="da"
LC_COLLATE="da"
LC_MONETARY="da"
LC_MESSAGES="da"
LC_PAPER="da"
LC_NAME="da"
LC_ADDRESS="da"
LC_TELEPHONE="da"
LC_MEASUREMENT="da"
LC_IDENTIFICATION="da"
LC_ALL=

which prints some errors because of incomplete code. 

same with using country code 'DK' 
xxx@yyy:~> LANG=DK locale 
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory

Same with cs, ja, nb. It looks that the base system does not like abbreviated codes.

I took a look into gnucash source and saw the locale related sub dir is determined by calling setLocale(LC_MESSAGE) so it matches the above mentioned issue. Managing of abbreviated codes has been build into gnucash. See the related commit:

/home/xxx/src/gnucash/ChangeLog.2002:3551 [1]
2002-07-03  Christian Stimming  <stimming@tuhh.de>

	* src/gnome/druid-hierarchy.c (gnc_get_ea_locale_dir): If current
	locale doesn't work for account hierarchy druid, then check all
	abbreviated versions of that locale.

and 

commit 9854876c702bca212d31221fba4f4126445bb25a
Author: John Ralls <jralls@ceridwen.us>
Date:   Sun Mar 20 15:11:06 2016 -0700

    OSX: Get the locale for account trees from the OS instead of setlocale().
    
    It's possible for OSX to create locales that while legal aren'tI
    supported by setlocale, and we have account trees for some of these.
    Retrieving the locale from NSLocale **ignores the fixup done in
    gnucash-bin** to ensure that a reasonable and supported locale is used.

I haven't checked running locale on a OSX System yet but from the last sentence it looks to me that abbreviated locals are already *not* supported on OSX.

At least this may be a reason to rename abbreviated locals to full locale codes, otherwise some languages will not be supported on OSX.  If not kmymoney requires to have a hack similar to [1] in the account importer, which results into having two hacked applications, while a simple rename would fix all related issues.

@derekatkins: An additional point for the need of renames is the russian templates using code ru. 

locale -a | grep ru  shows two variants 
ru_RU
ru_UA

Is the recent ru template for ru_RU = Russian/Russia or for ru_UA = Russian/Ukranie ?

**Comment by jralls** [comment]
It doesn't matter.at.all what linux's locale command reports.

The only thing that matter's is whether GnuCash users in those locales get the right template when they create a new Chart of Accounts. I just tested that with with Russian/Ukraine on my Mac and got the Russian templates. That's because our code "falls back" to the language-only templates when the exact locale doesn't have one.

I also tested Spanish/Guatemala because we have es_ES and es_MX only. I got the C templates, which is a problem and one that this PR would make worse.

The answer to your question for Derek is *both*. Unless the Russian and Ukrainian accounting rules differ significantly (unlikely) *and* some Russian-speaking Ukrainian provides new templates matching the Ukrainian rules, ru templates serve for both. Otherwise the only alternative is to provide the C templates, meaning English and the US's rather different rules. That's certain to be much less useful to our hypothetical Ukrainian.

**Comment by gjanssens** [comment]
Interesting discussion that's going on here :)

> I also tested Spanish/Guatemala because we have es_ES and es_MX only. I got the C templates, which is a problem and one that this PR would make worse.

The example for the Spanish situation would suggest we'd need to actually **add more** abbreviated locales rather than removing them. For example for Spanish we could choose say es_ES as fallback and then configure our various templates such that es would point to es_ES. That way people in other Spanish speaking countries are proposed a Spanish account template rather than en English one.

**Comment by gjanssens** [comment]
> I haven't checked running locale on a OSX System yet but from the last sentence it looks to me that abbreviated locals are already not supported on OSX.
> 
> At least this may be a reason to rename abbreviated locals to full locale codes, otherwise some languages will not be supported on OSX.

I'm not on OSX, however I believe you're interpreting this commit backwards. This commit was not to deal with abbreviated locales, but with fully specified locales which aren't supported by setlocale on OS X, yet for which we do have account templates.

**Comment by gjanssens** [comment]
And just to be clear, our account template selection does exactly the same thing as glibc does to find locale sensitive information.

Let me explain with an example:
Suppose your system locale is da_DK (a fully specified locale). If you run KMyMoney, it will happily use the Danish translation for the interface. Where are these translated strings retrieved from ? Well, on my system they come from
/usr/share/locale/**da**/LC_MESSAGES/kmymoney.mo

So while the system locale is _da_DK_, the translation is searched for in a directory _da_, because there is no translation available for Denmark specifically. That's how glibc works. It falls back to a language-only search if the language/country combination is not found.

Our account templates are not part of the locale system, however they are equally locale sensitive. Hence gnucash implements the same search algorithm for them: if templates are found in the language_country subdirectory, provide those, otherwise fall back to a language only directory.

Where's the difference for you and  why would that be a bug ?

**Comment by rhabacker** [comment]
On creating a new file or importing account templates kmymoney tries to retrieve to the country name from the subdir account templates are located into and groups them is a tree view grouped by the the country name which fails for the to 'language-only' subdirs like cz, da, ja, ko and nb.

**Comment by jralls** [comment]
Then that's a bug in KMyMoney, if KMyMoney wants to use the GnuCash templates as-is. See the bit about KMyMoney's options in [my earlier post](https://github.com/Gnucash/gnucash/pull/105#issuecomment-252361242), in particular the part about us changing things at whim that might break whatever KMyMoney does this week to adapt to how the templates work now.

Bottom line: The GnuCash community develops its components and resources **exclusively for use by GnuCash**. While other projects are free to **copy** those resources so long as they comply with the GPL, they are foolish to rely on the stability or fitness for their purposes of anything in the GnuCash repositories.

**Comment by rhabacker** [comment]
Thanks for all your explanations. Because KMymoney, which uses the underlaying os (glibc) to retrieve country names, still fails to retrieve the country name from the subdirectory named like a language and the language is not part of the country like 'da', 'ja', 'ko' and 'nb', while it works using 'da_DK' or 'dk', I renamed the related folder after importing into kmymoney to fix the mentioned issue (see https://github.com/KDE/kmymoney/commit/234a248d4e7ae1595e53db451050d1659446cd8c)

**Comment by fellen** [comment]
Don't forget to add at least links for da_DE, da_FO, da_GL to cover the regions where dansk is an official language and do similar for the other languages.

**Pull request closed without merging**
