### PR TITLE
Prices Import and delete old ones 

### PR DESCRIPTION
**Pull request by Bob-IT**
This pull request adds the ability to import prices from a fixed format csv file. It all seems to work OK so was looking for any suggestions / changes. I will refactor some functions to a util file as they are repeated in other fixed format import files. There is a known problem with the date format selector affecting all import options that I will raise on the list.

Also I have changed the options for deleting old prices to make it more flexible and this is where travis is failing. Any suggestions / changes are always welcome and I will change the unit tests if these changes are OK.

### CODE REVIEW

**Comment by gjanssens** [comment]
Bob, thanks for your work. I haven't reviewed it yet. However I want to inform you I'm in the process of eliminating the transaction fixed format import. It will be incorporated in the new csv importer as a preset.

So please hold of refactoring common functions to a util file for now.

**Comment by gjanssens** [comment]
Quick review: you are using gnc-csv-model.h for some reason. I guess you want the date parsing function in there. This file is gone in my work as the importer is rewritten in c++. The date parsing function is now available in a c++ file called gnc-trans-props.hpp/cpp.
Can you pull my private cpp branch and rebase your commits on that one ? You will probably have to make your price importer compile as c++ in order to use the new date parsing function. My cpp branch can be found here:
https://github.com/gjanssens/gnucash/tree/cpp

**Comment by Bob-IT** [comment]
Thanks for the information, been tracking yours and John's c++ changes with a small amount of understanding but the finer points no. Will have a look at the date parser. The changes here were a heads up for what I cobbled together and before I tried to refine was looking for any suggestions / changes required.

**Comment by Bob-IT** [comment]
I am closing this and will resubmit later after the csv import changes and will split this in to two.

**Pull request closed without merging**
