### PR TITLE
Hebrew translation 95% completed...

### PR DESCRIPTION
**Pull request by avma**

### CODE REVIEW

**Comment by jralls** [comment]
Super, but please do a soft reset, rename the file to `he.po` (not `git rename` as there's already an `he.po` that we need your file to replace), recommit, and force push.

**Comment by fellen** [comment]
Good work, but a few further notes:

In the header, see https://wiki.gnucash.org/wiki/Translation#Adjust_the_header_and_special_strings

- Update the copyright:

```
- # Copyright (C) 2008 
+ # Copyright (C) 2008 - 2019 by the respective translator
# This file is distributed under the same license as the GnuCash package.

```

- We want to keep the history from the previous version of the file for the copyright, but you can rearrange it::

```
+ # Ori Hoch <ori@uumpa.com>, 2008.
+ # http://www.uumpa.com/gnucash-he/
+ <a line about you>
```


"Project-Id-Version: GnuCash 3.5\n"
"POT-Creation-Date: 2019-03-30 14:44-0700\n"

- The pot seems not to be recent. Can you merge a recent template?

https://wiki.gnucash.org/wiki/Translation#Get_a_fresh_template and
https://wiki.gnucash.org/wiki/Translation#Update_an_existing_.po_file

- Not required, but desired:

he.po:2191: msgstr lacks the keyboard accelerator mark '_'
he.po:3517: msgstr lacks the keyboard accelerator mark '_'
he.po:3869: msgstr lacks the keyboard accelerator mark '_'
he.po:4197: msgstr lacks the keyboard accelerator mark '_'
he.po:5183: msgstr lacks the keyboard accelerator mark '_'
he.po:9298: msgstr lacks the keyboard accelerator mark '_'
he.po:9367: msgstr lacks the keyboard accelerator mark '_'
he.po:9429: msgstr lacks the keyboard accelerator mark '_'
he.po:9614: msgstr lacks the keyboard accelerator mark '_'
he.po:9729: msgstr lacks the keyboard accelerator mark '_'
he.po:9944: msgstr lacks the keyboard accelerator mark '_'
he.po:10702: msgstr lacks the keyboard accelerator mark '_'
he.po:11104: msgstr lacks the keyboard accelerator mark '_'
he.po:11226: msgstr lacks the keyboard accelerator mark '_'
he.po:11434: msgstr lacks the keyboard accelerator mark '_'
he.po:11486: msgstr lacks the keyboard accelerator mark '_'
he.po:11502: msgstr lacks the keyboard accelerator mark '_'
he.po:11803: msgstr lacks the keyboard accelerator mark '_'
he.po:11839: msgstr lacks the keyboard accelerator mark '_'
he.po:12555: msgstr lacks the keyboard accelerator mark '_'
he.po:13448: msgstr lacks the keyboard accelerator mark '_'
he.po:14240: msgstr lacks the keyboard accelerator mark '_'

**Comment by avma** [comment]
Sure no problem, the latest gnucash.pot file I found refers to gnucash 3.6...
I'll work on it a bit more then recommit.

**Comment by avma** [comment]
Sure no problem, the latest gnucash.pot file I found refers to gnucash 3.6...
I'll work on it a bit more then recommit.

**Pull request closed without merging**
