### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
Thanks!

@cewbdex I got the following warnings:
```
msgfmt -c --check-accelerators="_" --statistics po/cs.po 
po/cs.po:13183: msgstr lacks the keyboard accelerator mark '_'
po/cs.po:14424: msgstr lacks the keyboard accelerator mark '_'
po/cs.po:16961: msgstr lacks the keyboard accelerator mark '_'
po/cs.po:18180: msgstr lacks the keyboard accelerator mark '_'
po/cs.po:18184: msgstr lacks the keyboard accelerator mark '_'
msgfmt: found 5 fatal errors
2388 translated messages, 1917 fuzzy translations, 1096 untranslated messages.
```
To  understand that log, 'po/cs.po:13183' means line 13183 in cs.po—you can download that format from weblate.
That section  reads:
```
#: gnucash/gtkbuilder/assistant-csv-export.glade:456
#: gnucash/gtkbuilder/gnc-plugin-page-register.glade:141
msgid "Select _Range"
msgstr "Zvolte rozsah"
```
Can you read https://wiki.gnucash.org/wiki/Translation#Special_characters_and_other_tips and try to fix them?

@SziaTomi @mocsa and other hungarian translators it would be nice if you would start to fix the 70 similar issues in hu.po.

**Comment by mocsa** [comment]
Hungarian translations are fixed. But now I get "Inconsistent" errors. I always clicked the "Apply selected translation to all propagated strings" and Weblate jumped to the next string to be translated. But when I navigated back, the error was still there. So my translation was never propagated to the "Program-beta" component.

**Comment by fellen** [comment]
That is correct. As Program-beta is still only a copy of Program, I have locked it, After I accept your changes, I will merge them also into Program-beta .

**Comment by cewbdex** [comment]
@fellen 
I have fixed the strings you listed, however, I found the Czech translation being in a horrible shape. There are so many source strings that have an identical translation (which is 99% irrelevant). Is there a way to find such dupliacates? Weblate seems to have no tool for this. Also you closed the beta translation, but it still shows the error and prevents from going to next string, can it be hidden from Weblate completely?

**Pull request merged**
