### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by jralls** [comment]
Thanks, all.

@CWehli there are 34 missing accelerators in de.po. Can you please fix them when you have a chance?

@yurchor There's one missing accelerator in uk.po, 
```
#: gnucash/ui/gnc-plugin-bi-import.ui:6
msgid "Import Bills & _Invoices…"
msgstr "Імпортувати рахунки і рахунки-фактури…"
```

**Comment by dawansv** [comment]
@jralls I noticed the french "screen" keyboard in Weblate is putting `&nbsp;` html codes instead of U+00A0 when using the NBR "non breaking space".  French language uses a lot of NBR before/after quotes, some punctuation, etc. These `&nbsp;` show as is in the interface (I assume the only place they are OK is in reports).
image

image

I will fix now by inserting U+00A0 manually but is that something that can be changed in some parameter somewhere? https://docs.weblate.org/en/latest/admin/config.html#special-chars

I am pretty sure it was not like that when I started doing the translation just a few weeks ago. Not 100% sure about it.

**Comment by dawansv** [comment]
@jralls OK well weblate will not take U+00A0. If I enter that character and press save, I get the following message and the character is automatically converted to `&nbsp;`  Same thing happens with the screen keyboard NBS key, so the keyboard is not the issue here, it correctly enters the U+00A0 character, but it gets converted to HTML when saving. Was that HTML option somehow enabled recently or something?

> Following fixups were applied to translation: Unsafe HTML

**Comment by jralls** [comment]
@dawansv Yes, I added the `safe-html` translation flag because the Weblate console was whining about it. I just removed it so things should go back to normal.

IMO that's a weblate bug. If it's going to do things like that it should be context-sensitive and only override prohibited characters when it's editing HTML. 

Edit: I'm not the only one who [thinks so](https://github.com/WeblateOrg/weblate/issues/6490) either.

**Comment by dawansv** [comment]
Thanks I will fix the French translation now.

It seems for now the safe-html flag would have to be added at the string level for what I assume would only be strings in reports.

**Comment by jralls** [comment]
It would have to be applied with `#,` in gnucash.pot like `scheme-format`. I don't know offhand how that's done.

**Pull request merged**
