### PR TITLE
Hebrew he.po for v 3.6

### PR DESCRIPTION
**Pull request by avma**

### CODE REVIEW

**Comment by avma** [comment]
sure can...

btw, do I need to cancel this pr, commit the new he.po file and create a new pr, or just commit the new he.po file?

**Comment by christopherlam** [comment]
You can use any Git client, GitHub has a nice one https://desktop.github.com/ - you'll be modifying files locally, committing new changes, and pushing to your branch in no time.

**Comment by avma** [comment]
unfortunately, they don't have a Linux version yet...

**Comment by gjanssens** [comment]
> sure can...
> 
> btw, do I need to cancel this pr, commit the new he.po file and create a new pr, or just commit the new he.po file?

There is no need to cancel a PR. Anything you commit and push to the base branch of the PR will automatically become part of the PR. It even withstands force-pushing if your rebased or amended commits.

**Comment by fellen** [comment]
@avma Are you still working to improve he.po or missed I a pull request?

**Pull request closed without merging**
