### PR TITLE
Made ofx-gschema dependent on WITH_OFX flag

### PR DESCRIPTION
**Pull request by bhardwajs**
Change cmake config to move ofx-gschemas out of main list and check for WITH_OFX flag.

### CODE REVIEW

**Comment by bhardwajs** [comment]
Somehow, I didn't get a notification yesterday that Travis build failed. Taking a look now.

Surprised that Travis fails for autotools when the PR doesn't touch any of autotools part.

**Comment by jralls** [comment]
It was test-import-map which fails intermittently for no particular reason. Don't worry about it.

**Comment by gjanssens** [comment]
Thanks!
Note your changes got me thinking about this business of conditionally excluding some directories from the build path and I believe this has negative side effects on the generation of our distribution tarballs. I've opened [a new bug](https://bugzilla.gnome.org/show_bug.cgi?id=787497) for this so we can discuss this. It's not an issue you have introduced. We already did this wrong for aqbanking an the python-bindings.

**Comment by bhardwajs** [comment]
Thanks @jralls .
@gjanssens I did check today to confirm that WITH_OFX and WITH_AQBANKING are handled consistently. Let me look at the bug that you created. Thanks!

**Pull request merged**
