### PR TITLE
Clean up bitrot to get CuteCash building again.

### PR DESCRIPTION
**Pull request by codesmythe**
1. Use guile-2.0 instead of guile-1.8.
2. Set GNC_PLATFORM_POSIX on Unix (for gnc_timezone.cpp).
3. Pass guile include files when compiling cutecash.
4. Link Boost libraries.
5. Add -std=gnu99 to CMAKE_C_FLAGS.
6. Temporarily put -O2 in CMAKE_C_FLAGS since Fedora requires
    optimization for FORTIFY_SOURCE.  (Eventually with CMake
    we will have separate Debug and Release builds.)

Tested that cutecash builds and launches on OS X, Fedora 23 and Ubuntu 14.04.3.

### CODE REVIEW

**Comment by jralls** [comment]
Thanks. I'm taking it on faith that this works because I don't have a Qt installation to test against. I'm looking forward to a PR that has a switch for Gtk that I can test.

**Comment by gjanssens** [comment]
Tried to build cutecash today with these patches applied on a Fedora 22 system. The cmake run worked fine, make failed due to missing glibmm development headers.

I can't seem to find these on F22. @codesmythe you say you managed to build this successfully on Fedora 23. Which package provides glib22 development headers on F23 ?

**Comment by codesmythe** [comment]
Hi @gjanssens,

I'm using glibmm24-devel on Fedora 23.

**Comment by gjanssens** [comment]
Hmm, that's what I had as well.

I cleared the build directory reran cmake and now it 
appears to work fine. Odd.

Thanks for cleaning up the cutecash build !

**Pull request merged**
