### PR TITLE
Maint

### PR DESCRIPTION
**Pull request by victor811**
Update Russian translation

### CODE REVIEW

**Comment by zeldigas** [comment]
good catch, thank you for fix

**Comment by jralls** [comment]
@zeldigas I take it that means it's OK to merge?

**Comment by zeldigas** [comment]
Sure

**Comment by gjanssens** [comment]
Thanks for the feedback. I have merged the PR after a rebase. The improvements will go into the next release. Thank you very much.

@victor811 In case you intend to submit more translation improvements, I encourage you to coordinate thie with @zeldigas as he is indicated as the last translator in the current ru.po file. That's just to avoid unecessary double work. Thanks!

**Pull request closed without merging**
