### PR TITLE
Typo fix and README update

### PR DESCRIPTION
**Pull request by Abschiedsstein**
Fixed typos in common/cmake_modules/GncAddSwigCommand.cmake
Updated README

### CODE REVIEW

**Comment by jralls** [comment]
The typo is OK, but why remove the reference to README.git?

**Comment by Abschiedsstein** [comment]
The reference is in building and installing section. But there is no such information in README.git.
If the reference should be kept it should be in the context of how to behave when making changes to gnucash (which is the information addressed in README.git)

**Comment by jralls** [comment]
OK, I see your point. I think that whole section needs overhauling: Most of the content either duplicates or belongs in README_CMAKE.txt.

**Comment by gjanssens** [comment]
Thanks. I have merged this. It wasn't clear to me who is supposed to do the overhauling. @Abschiedsstein  if you would take a stab at this, feel free to create a new PR.

**Pull request merged**
