### PR TITLE
Update Indonesian translation for GnuCash.

### PR DESCRIPTION
**Pull request by triyanwn**
Update Indonesian translation.

### CODE REVIEW

**Comment by fellen** [comment]
Shouldn't 'split' become 'perpisahan', 'pemisahan' or similar? I wonder, why you replaced it.

Commited as commit 562b4be after adding the statistics.

Thank you

**Comment by triyanwn** [comment]
At first, I use pisahan/pemisahan, but then I think these words are not common to use in finance, so I leave it as is.

**Comment by fellen** [comment]
Perhapsyou can find a term starting with https://id.wikipedia.org/wiki/Pembukuan_berpasangan ?

**Comment by triyanwn** [comment]
Thanks, I will check it. My other consideration for not translating it is that some other accounting software doesn't translate it either, including GnuCash for Android. Apart from that, in my opinion, this term is safer not to translate, because there is no correct word equivalent in Bahasa Indonesia. If this term is translated, it can be misinterpreted by the user.

**Pull request closed without merging**
