### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program-beta](https://hosted.weblate.org/projects/gnucash/program-beta/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by jralls** [comment]
Thanks, all.

@taoyouh, one missing accelerator, line 1678:
```
#: gnucash/gnome/assistant-stock-transaction.cpp:956
msgid "Ne_w Balance"
msgstr "新余额"
```

@gallegonovato 19 missing accelerators:
```
#: gnucash/gnome-utils/gnc-account-sel.c:528
msgid "Hide _Hidden Accounts"
msgstr "Ocultar cuentas ocultas"

#: gnucash/gtkbuilder/dialog-account.glade:1464
msgid "Acco_unt Type"
msgstr "Tipo de cuenta"

#. Translators: Menu entry, no full stop
#: gnucash/import-export/import-main-matcher.c:1341
msgid "Assign e_xchange rate"
msgstr "Asignar tipo de cambio"

#: gnucash/ui/gnc-main-window.ui:193
msgid "Tab P_osition"
msgstr "<b>Posición de pestaña</b>"

# Título de Ventana
#: gnucash/ui/gnc-plugin-business.ui:78
msgid "Find Bi_ll…"
msgstr "Buscar cargo…"

#: gnucash/ui/gnc-plugin-business.ui:112
#: gnucash/ui/gnc-plugin-page-owner-tree.ui:55
#: gnucash/ui/gnc-plugin-page-owner-tree.ui:627
msgid "_New Employee…"
msgstr "Crear operador…"

#: gnucash/ui/gnc-plugin-business.ui:114
msgid "Open the New Employee dialog"
msgstr "Abre “Crear operador” como diálogo"

#: gnucash/ui/gnc-plugin-business.ui:117
msgid "_Find Employee…"
msgstr "Buscar operador…"

#: gnucash/ui/gnc-plugin-business.ui:122
msgid "New _Expense Voucher…"
msgstr "Crear comprobante de gasto…"

#: gnucash/ui/gnc-plugin-business.ui:127
msgid "Find Expense _Voucher…"
msgstr "Buscar comprobante de gasto…"

#: gnucash/ui/gnc-plugin-csv-import.ui:16
msgid "Import _Prices from a CSV file…"
msgstr "Importa precios desde un fichero CSV…"

#: gnucash/ui/gnc-plugin-page-account-tree.ui:90
#: gnucash/ui/gnc-plugin-page-account-tree.ui:195
#: gnucash/ui/gnc-plugin-page-budget.ui:79
#: gnucash/ui/gnc-plugin-page-owner-tree.ui:86
#: gnucash/ui/gnc-plugin-page-register.ui:353
msgid "_Filter By…"
msgstr "Filtrar por…"

#: gnucash/ui/gnc-plugin-page-account-tree.ui:138
#: gnucash/ui/gnc-plugin-page-account-tree.ui:239
#: gnucash/ui/gnc-plugin-page-register.ui:242
msgid "_Auto-clear…"
msgstr "Auto-puntear…"

#: gnucash/ui/gnc-plugin-page-account-tree.ui:150
#: gnucash/ui/gnc-plugin-page-account-tree.ui:254
#: gnucash/ui/gnc-plugin-page-register.ui:254
msgid "Stoc_k Split…"
msgstr "División de acciones…"

#: gnucash/ui/gnc-plugin-page-account-tree.ui:271
#: gnucash/ui/gnc-plugin-page-account-tree.ui:427
msgid "_Delete Account…"
msgstr "Borrar cuenta…"

#: gnucash/ui/gnc-plugin-page-budget.ui:22
#: gnucash/ui/gnc-plugin-page-budget.ui:240
msgid "_All Periods…"
msgstr "Todos los períodos…"

#: gnucash/ui/gnc-plugin-page-budget.ui:70
#: gnucash/ui/gnc-plugin-page-budget.ui:200
msgid "Budget _Options…"
msgstr "Opciones del presupuesto…"

#: gnucash/ui/gnc-plugin-page-register.ui:295
#: gnucash/ui/gnc-plugin-page-register.ui:433
#: gnucash/ui/gnc-plugin-page-register.ui:657
msgid "Sche_dule…"
msgstr "Planificación…"

#: gnucash/ui/gnc-plugin-page-register.ui:348
msgid "_Sort By…"
msgstr "Ordenar por…"
```

**Comment by gallegonovato** [comment]
Good afternoon @jralls

 I apologize as I didn't realize the _

 I translated the whole thing without noticing that part.

I will try to fix it as soon as possible. 

I don't know where my head would be.

Please excuse me 

A hug and thank you for your indication

**Comment by gallegonovato** [comment]
Good afternoon:

In this chain I have several doubts:

Leave it as it is Ref in Spain is Economic and Fiscal Regime of the Canary Islands Put Reference

I don't know if you could specify a little more

I think it is Reference but just in case. The string is https://hosted.weblate.org/translate/gnucash/program-beta/es/?q=label%3A%22Source+needs+review%22&offset=9#comments

Best regards

**Comment by jralls** [comment]
@gallegonovato 
>Please excuse me

No worries, the accelerator marks are easy to miss.

**Pull request merged**
