### PR TITLE
Unique values in option example

### PR DESCRIPTION
**Pull request by flywire**

### CODE REVIEW

**Comment by jralls** [comment]
Please remove the last commit: Pull requests shouldn't have any merge commits. You can rebase on today's master to get that change.

The first commit would be better split into three: Renaming hello-world.scm to sample-report.scm, removing welcome-to-gnucash.scm, and your changes to sample-report.scm.

I think it would be better to remove the crash option from sample-report and the exception from test-stress-options so that sample-report is tested.

To force-push your repaired branch say `git push -f <remote> Hello5`, substituting the remote name for `<remote>`.

**Comment by flywire** [comment]
> To force-push your repaired branch say `git push -f <remote> Hello5`, substituting the remote name for `<remote>`.

Forcing pushes back to the repo is failing possibly due to wrong <remote> reference. Can you give me that line explicitly referencing https://github.com/Gnucash/gnucash/pull/1524#issuecomment-1418263961 ?

**Comment by jralls** [comment]
It failed when you tried to push Hello5 to hello4 because you left off the `-f` in `git push origin Hello5:hello4`. Maybe it will be easier to remember if you spell it out: `git push --force origin Hello5`.

A non-forced push expects the source branch (the one you're pushing) to include the commit that is HEAD on the destination (i.e. remote) branch and adds the commits on the source to that commit. A force push *replaces* the HEAD commit and its chain of parents on the destination branch with those from the source branch.

**Comment by jralls** [comment]
Thanks!

**Pull request merged**
