### PR TITLE
797338

### PR DESCRIPTION
**Pull request by DaveC49**
changes in the import matcher to change U+R to U+C and R to C

### CODE REVIEW

**Comment by fellen** [comment]
No, we do not want to merge Master in Maint. ;-)

**Comment by christopherlam** [comment]
@DaveC49 easy to fix. Edit the PR (from github website) and change base to master.

**Comment by DaveC49** [comment]
Not sure what happened here. I think I accidentally rebased 797338 onto maint after a pull with fast forward from both maint and master when it should have been rebased onto master. Only 578c27c
OK I think i have managed to undo the rebase and rebase it onto master

**Comment by DaveC49** [comment]
I think I managed to fix it using git reflog  followed by a hard reset and a rebase onto the master. I have repushed the new rebased on master branch to my repo and created another pull request to my repo and created a new pull request.

**Pull request closed without merging**
