### PR TITLE
Fixed and polished translation in ru.po

### PR DESCRIPTION
**Pull request by ashed**
Almost finished fixing and polishing russian translation of Gnucash in ru.po
Would you add this *bunch of bytes*?
[ru.zip](https://github.com/Gnucash/gnucash/files/1345098/ru.zip)

### CODE REVIEW

**Comment by jralls** [comment]
That's a novel way to abuse Github's pull request system. Would you like me to just apply the changes or would you prefer to learn to make a proper pull request?

**Comment by ashed** [comment]
I am so sorry if I disturbed you. Can I add fixed variant of ru.po in main branch?

**Comment by jralls** [comment]
You didn't disturb me.

Most translators just send updated po files to the list or work with the Translation Project. You're trying to use git and github instead, which is fine, but you're not doing it right. I'll help you learn if that's what you want to do. If it isn't I'll just commit your po for you.

**Comment by ashed** [comment]
O-h! This sound great. 
I download only ru.po without fork or cloning Ghucash repo.
And I can not push changes obviously.
That's right?
Would you help me please?
Sorry my poor English.

**Comment by jralls** [comment]
OK. Looks like you found a bug in Github, their Pull Request tool shouldn't permit creating a PR between branches in a project, that's a bit nuts.

I'll commit your new po file for you. Next time just send it to gnucash-devel.

**Comment by ashed** [comment]
This is great. Thank you very much. Is **gnucash-devel** a new branch?

**Comment by ashed** [comment]
And besides I've got a bunch of articles about Gnucash. It scraped from many sites. It is like unofficial and more flexible manual. Maybe this is useful for gnucash project?

**Comment by jralls** [comment]
No, [gnucash-devel](https://lists.gnucash.org/mailman/listinfo/gnucash-devel) is the developer's mailing list. Click the link to subscribe.

**Comment by jralls** [comment]
>And besides I've got a bunch of articles about Gnucash. It scraped from many sites. It is like unofficial and more flexible manual. Maybe this is useful for gnucash project?

Useful or not it would be theft for us to republish them without permission, but if you still have the URLs we could make a "What others say" page on the wiki and add them, perhaps with a brief summary.

**Comment by ashed** [comment]
This sound reasonable. Sure this some "walking on edge".  It is a good idea to deal about articles with it's authors. Totally agree.
This is URLs list.
[http://ashep.org/tag/gnucash/](http://ashep.org/tag/gnucash/)
[https://geektimes.ru/post/206866/](https://geektimes.ru/post/206866/)
[https://habrahabr.ru/post/336656/](https://habrahabr.ru/post/336656/)

**Comment by jralls** [comment]
Oh. I guess I should have expected they'd be in Russian. We don't have a Russian wiki to attach them too.

The server that hosts the mailing lists, wiki, and a few other things is having some network issues at the moment and its owner is traveling. Try again next week.

**Comment by ashed** [comment]
And because this articles in Russian. Perhaps you will make a decision collegially and a wiki in this project will have a Russian part too?
I'll try to subscribe next week according to your advice. Thanks again.

**Comment by jralls** [comment]
Unfortunately adding a Russian wiki isn't that easy. We'd need someone to figure out which English pages need to be translated, then do the translations, and finally to commit for the long term to maintain it. There are some others who have been working on translating the Concepts Guide and one of them asked for a gnucash-ru to coordinate the efforts. That also requires someone to manage the list and I think it is stalled waiting, but once Derek gets the network situation sorted out perhaps you can connect with them on gnucash-devel and work something out.

**Comment by fellen** [comment]
Because there is no ru translation of the main page, I put the links in https://wiki.gnucash.org/wiki/Documentation, which is a multilingual collection. Later you can move it like we did with the de section.

Currently we are working with lang tags as prefix, e.g. De/GnuCash is the german main page.
To get  a real multilingual wiki with our prederred module:
  Linas will have to create subdomains in the DNS,
 then Derek can adjust the configuration,
 then I will run first tests by moving wiki.gnucash.org/wiki/De/* to de.wiki.gnucash.org/wiki/* or similar,
 finally the others can follow.

**Comment by fellen** [comment]
Ahem. I am really sorry to chime in so late, but I am still fighting a cold.

jralls, did you see the pending https://github.com/Gnucash/gnucash/pull/204? It got now conflicts.
May I remember you about https://wiki.gnucash.org/wiki/Translation which was before this  PR mandative for localisation questions. ;-)

Ashed: did you see 742ff: ...You should only translate the letter *after* the colon.
"not cleared:", "cleared:", ... is the context, not the translatable string.

**Comment by fellen** [comment]
Oops, I was not ready with my comment:

We got 2 PRs for ru.po, which now conflict.
This one is based on an very old template, PR#204 merged a fresh template.
As usual the merge produced noise.
This contains some noise from switching the tool.

I would like to ask booth authors to submit next time 2 commits in one working branch:
1. preparations like msgmerge or reformatting,
2. real translation work.
Then it is much easier to read.

My few hours russian are much to less to decide which is the easier way to resolve the conflict between this two PRs.

@ashed , can you discuss it with DiMan? I will be the next week here to help you.

@jralls was committing "Add missing export (gnc:date-get-week)" intended?

**Comment by gjanssens** [comment]
On zaterdag 30 september 2017 07:38:38 CEST Frank H. Ellenberger wrote:
> @jralls was committing "Add missing export (gnc:date-get-week)" intended?

That was not @jralls' work. I have merged PR 206 shortly before @jralls 
commented on this PR 209. PR 206 is the PR that actually offers this commit 
for inclusion. So yes, that was intentional :)

The fact this same commit is in PR 209 is the result of how @ashed created his 
PR. I don't know the exact details but it looks he pulled in PR 206 while 
attempting to create his own PR. From there it looks like he made a PR from 
his maint branch (now including the commit from PR206 I hadn't merged yet at 
that moment) to our master branch (which is wrong as well). And instead of 
actually including his translation work in a commit, he chose to add a link to 
it in the comment of the new PR.

All very confusing, but otherwise unrelated to my deliberate choice of merging 
PR 206.

**Comment by ashed** [comment]
I am so sorry for this accidental confusing. I wrote to DiMan, who did PR 206 and we try to got decision.
Maybe honorable @gjanssens propose better solution?

**Comment by gjanssens** [comment]
On vrijdag 29 september 2017 20:18:13 CEST John Ralls wrote:
> OK. Looks like you found a bug in Github, their Pull Request tool shouldn't
> permit creating a PR between branches in a project, that's a bit nuts.

I believe this is in fact normal git functioning. git is agnostic to branch 
names (although it proposes "master" as default branch) and you can merge from 
any branch to any other at your discretion. We happen to give special meaning 
to maint in our repository, but as far as git is concerned it is just a branch 
like any other branch (topic or not, it makes no difference).

Of course not all types of merges would make sense and some would even be 
problematic. But what makes sense is project policy not git.

We have chosen one particular branching and merging strategy, but it's not 
necessarily the only valid one.

I agree this would create a pretty odd commit history, but github can't know 
whether this is wrong or not.

**Comment by gjanssens** [comment]
On zaterdag 30 september 2017 11:00:21 CEST ashed wrote:
> I am so sorry for this accidental confusing. I wrote to DiMan, who did PR
> 206 and we try to got decision. Maybe honorable @gjanssens propose better
> solution?

@ashed You're still adding to the confusion :) @DiMan did PR#204 not PR#206. 
PR#206 has nothing to do with the Russian translation.

As for the better solution you have taken step one and contacted @DiMan to 
coordinate further so you are not doing double work.

Next, take @fellen's suggestion into account:

To start read the translation wiki page and follow procedures explained there.

Then an attempt to get the current situation resolved:

* pull the latest maint branch from our repository (something similar to 
```git checkout maint; git pull --rebase origin maint```)
* create a new branch to do further translation work (```git branch 
ru_po_update```)
* checkout this new branch and continue your work from there (```git checkout 
ru_po_update```)
* start with a msgmerge of the current gnucash.pot file into your ru.po. If 
you don't know how to build gnucash to obtain the pot file, you can always 
[download the most recent one](http://translationproject.org/POT-files/
gnucash-2.6.18.pot) from [the translation project](http://
translationproject.org/domain/gnucash.html)
* commit this result without any other modification!
* From there on you'll have to compare your ru.po file with @DiMan's work and 
the two of you should discuss which translation to use in case your 
translation differs from his. I have no knowledge of your language so I can't 
help with this step.
* after you both agree on all adjustments, commit all these translation 
changes in another commit.
* push your work to your github repository and create a PR (against our maint 
branch!) from it.

This work can also be done by @DiMan with you advising him. The steps would be 
similar, except @DiMan should

* copy his ru.po aside
* back out his local commit (the one at the basis of PR#204)
* do the steps above

The end goal should be one final PR which includes two commits

1. one commit capturing the result of an msgmerge
1. one commit with translation updates. These updates would be the synthesis 
of the work of @ashed and @DiMan.

Note as I'm instructing you both to create a new branch and work on that 
branch instead of maint, this will create a completely new PR, rather than 
amend #204 or #209. The old ones will simply be closed. The new one merged in.

**Comment by jralls** [comment]
>>OK. Looks like you found a bug in Github, their Pull Request tool shouldn't
 permit creating a PR between branches in a project, that's a bit nuts.

>I believe this is in fact normal git functioning. git is agnostic to branch
names (although it proposes "master" as default branch) and you can merge from
any branch to any other at your discretion. We happen to give special meaning
to maint in our repository, but as far as git is concerned it is just a branch
like any other branch (topic or not, it makes no difference).

@gjanssens: The problem is that one can go to https://github.com/Gnucash/gnucash/pulls, click "new pull request", and be offered two branches inside *this repository* to pull between. Now I can see an argument that it provides a mechanism for discussion about merging a feature branch, but to avoid confusion it shouldn't be available to users who aren't registered on the project's team.

**Comment by jralls** [comment]
> The fact this same commit is in PR 209 is the result of how @ashed created his
PR. I don't know the exact details but it looks he pulled in PR 206 while
attempting to create his own PR. From there it looks like he made a PR from
his maint branch (now including the commit from PR206 I hadn't merged yet at
that moment) to our master branch (which is wrong as well). And instead of
actually including his translation work in a commit, he chose to add a link to
it in the comment of the new PR.

@gjanssens: Nope. @ashed didn't do anything in git. (As he said early on he hasn't cloned GnuCash.) He created a new PR from https://github.com/Gnucash/gnucash/pulls, selected "maint" from the second drop-down on https://github.com/Gnucash/gnucash/compare, and clicked "Create Pull Request". He wrote the first message and attached his ru.zip.

The resulting PR shows 0905465 because you'd merged maint->unstable->master and then committed it so that was the only thing to merge. I didn't merge the PR, I just retrieved ru.zip, expanded it to ru.po, copied it to gnucash/po, ran msgfmt -c on it to make sure it's OK, and  committed the result. I'd somehow missed that #204 was on ru.po; I thought that @DiMan was working on translating the Guide.

**Comment by ashed** [comment]
New version of gnucash russian translation
updated from **gnucash-2.6.18.pot**
Add it please.
[ru-2.6.18.zip](https://github.com/Gnucash/gnucash/files/1346806/ru-2.6.18.zip)

**Comment by jralls** [comment]
@DiMan, is ashed's new ru.po OK with you?

**Comment by jralls** [comment]
@DiMan responded on #204, so I've applied @ashed's latest change. @ashed, when you have more changes please don't use this PR.

**Comment by fellen** [comment]
@ashed Instead create a new PR.

While committing the statistics was: 
4670 translated messages, 2 fuzzy translations, 5 untranslated messages. That is really good, but it was complaining about 71 msgstr lacks the keyboard accelerator mark '_'.
See https://wiki.gnucash.org/wiki/Translation#Special_characters_and_other_tips for this issue.

**Comment by fellen** [comment]
@ashed Later I saw the file is missing the glade msgctxt messages. So my question: From where took you your gnucash-2.6.18.pot.

@jralls If it was from TP the tarball was built intree instead of out of tree.

I prepared a patch for ru.po but can currently not push it - packet loss at code.gnucash.org.
Statistics: 4670 translated messages, 10 fuzzy translations, 5 untranslated messages.

**Comment by gjanssens** [comment]
@fellen I checked on my local build (always out of tree) and the msgctxt comments are missing there as well. So we may have to investigate this further. I am building on Fedora 25, using cmake/ninja-build.

**Comment by fellen** [comment]
@ashed , @DiMan because of the счёт vs. счет change I would suggest to commit a russian https://wiki.gnucash.org/wiki/Translation#The_glossary_file and use it in translation and documentation.

**Comment by fellen** [comment]
Oops, where did I left my glasses? ;-)
We have already a https://github.com/Gnucash/gnucash/blob/maint/po/glossary/ru.po.
So just update it and  then review
https://github.com/Gnucash/gnucash-docs/tree/master/guide/ru for consistency.

**Comment by DiMan** [comment]
@Jon: You are right. I have been working on the transfer of the russian Guide translation from the HTML format into DocBook XML format and found some inconsistencies between Guide and GUI translation. I wanted to analyze and correct them.

@all:
In `Language-Team: russian ru@li.org` I set the URL of our group: `gnucash-ru@googlegroups.com`
(see PR #211). I write now to all users, who translated texts for GnuCash, and try to organize our communication in one place.

**Pull request closed without merging**
