### PR TITLE
Added new sv_AX and sv_FI account plans.

### PR DESCRIPTION
**Pull request by hawk-lord**
New pull request with only the current changes.

### CODE REVIEW

**Comment by gjanssens** [comment]
Thanks for starting a clean feature branch for this. I was in the process of cleaning up your previous pull request, but this makes it easier :)

A minor nit: you are replacing plain whitespace with tabs in your makefile changes. Please don't do this unless you have good reason to.

Also your previous PR contained a commit for the fi_FI account plans as well. Do you intend to add it to this PR as well ?

**Comment by hawk-lord** [comment]
I have a new IDE and apparently it defaults to tabs. I'll take care of that.

**Comment by hawk-lord** [comment]
The fi_FI will be submitted later.

**Comment by gjanssens** [comment]
Thanks. I have pushed your commit after rebasing it on maint (and correcting the white space inconsistencies). That way it will already appear in the next stable release.
Note that users on linux won't be able to use these new account plans because sv_AX and sv_FI are not valid locales and the gnucash code will switch to the C locale if either is set. I'll have to discuss with the other devs to decide on a proper solution for that.

**Comment by hawk-lord** [comment]
I am on OS X and I had the same problem with the locales until I got help from the mailing list.

**Pull request closed without merging**
