### PR TITLE
Increase of MAX_TAB_COUNT to change appearance of dialog "Book Options"

### PR DESCRIPTION
**Pull request by DiMan**
Increase of MAX_TAB_COUNT to change appearance of dialog "Book Options" in german language.

The dialog "Book Options" looks in german different, because it has 5 tabs: four standard tabs and additionaly one tab for tax settings, which appears only for german language. The 1 to 4 tabs appearance on top (horizontal mode). The appearance switchs to vertical mode (with tabs on the left side) for 5 and more tabs. Here the setting MAX_TAB_COUNT is increased to 5. This change should make the appearance of dialog "Book Options" similar in german and other languages.

Dialog "Book Options" in english, only for comparison:
bildschirmfoto_2018-07-14_20-58-57

Dialog "Book Options" in german before change:
bildschirmfoto_2018-07-14_20-58-05

Dialog "Book Options" in german after change:
bildschirmfoto_2018-07-14_20-52-51

### CODE REVIEW

**Comment by jralls** [comment]
This is a global change that will affect all GtkNotebooks in dialogs with 5 tags. That includes several reports' option dialogs. I think we should discuss it with the user community first, so please start a thread on gnucash-user.

**Comment by DiMan** [comment]
I just sent an email to gnucash-user.

**Comment by DiMan** [comment]
I have change the value MAX_TAB_COUNT to 8. See small discussion under https://lists.gnucash.org/pipermail/gnucash-user/2018-July/078224.html and the listing of all GnuCash dialogs: 
[GnuCash - Dialogs with GtkNotebooks.pdf](https://github.com/Gnucash/gnucash/files/2207239/GnuCash.-.Dialogs.with.GtkNotebooks.pdf)

**Comment by DiMan** [comment]
As written in mailing list, the report with 7 tabs still looks fine (<800x600). 
https://lists.gnucash.org/pipermail/gnucash-user/2018-July/078229.html

Which setting would you prefer:
* `MAX_TAB_COUNT=6`: all current reports are covered with this setting
* `MAX_TAB_COUNT=7`: + 1 tab additionally as reserve for future flexibility. (window < 800x600)
* `MAX_TAB_COUNT=8`: + 2 tabs additionally as reserve for more future flexibility (windows may be> 800x600 for some design themes)

**Comment by jralls** [comment]
Let's stop at 6. I merged and changed it in the merge commit. I actually think that the number of options pages on some reports is already a bit much.

**Comment by DiMan** [comment]
Thanks!

**Pull request merged**
