### PR TITLE
Use the proper UTF8 strip function.

### PR DESCRIPTION
**Pull request by ingoha**
Fixes #797473

### CODE REVIEW

**Comment by jralls** [comment]
When a commit is a bug-fix we use the bug summary as the commit summary, so 
```Bug 797473 - UTF8 characters not processed correctly with aqbanking6```.  You can explain what you did and why it fixes the bug in the commit comment.

**Comment by cstim** [comment]
@ingoha In other words, your bugfix is great and we would like to merge it. However, we ask for some code quality in the commits. so please edit the commit summary as described. Also, please try to limit your commit to the actual code change without unneeded whitespace changes in this same commit. Remember: You write the commit only once, but it will be read many many times, so please invest some time during writing the commits to write them as helpful as possible. Thanks!

**Comment by ingoha** [comment]
@cstim Understood :-) I will do the requested cosmetics on the commit's content.
As for the commit message: @jralls Is the bug you are referencing already in the bugtracker?

**Comment by ingoha** [comment]
@jralls Nevermind, I had a look into bugzilla and found the correspondig bug :-)

**Comment by jralls** [comment]
@ingoha Aren't you the Ingo who reported it?

**Comment by ingoha** [comment]
> @ingoha Aren't you the Ingo who reported it?

Yes - I was confused 8-)

**Pull request merged**
