### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
Thanks!

Note: did you update the year in `msgid "translator-credits"`? See https://wiki.gnucash.org/wiki/Translation#Adjust_special_messages.

@cyphra 
```
msgfmt -c --check-accelerators="_" --statistics po/es.po 
po/es.po:16681: msgstr lacks the keyboard accelerator mark '_'
msgfmt: found 1 fatal error
5390 translated messages.
```

@yth1130 There are a few errors:
```
msgfmt -c --check-accelerators="_" --statistics po/ko.po 
po/ko.po:4495: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:4515: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:4524: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:4590: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:8672: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:8787: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:9003: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:12672: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:13169: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:14074: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:14084: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:14114: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:14154: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:14166: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:14395: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:14891: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:15839: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:16094: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:16153: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:16172: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:16436: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:16446: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:16535: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:16660: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:17192: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:17196: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:17236: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:17445: msgstr lacks the keyboard accelerator mark '_'
po/ko.po:17569: msgstr lacks the keyboard accelerator mark '_'
msgfmt: found 29 fatal errors
2222 translated messages, 1788 fuzzy translations, 1380 untranslated messages.
```
Can you read https://wiki.gnucash.org/wiki/Translation#Special_characters_and_other_tips and fix them?

**Comment by yth1130** [comment]
I read the link, but I still don't understand.

The words I translated were very simple words.

I'm not sure where the underscore should go.

**Comment by jralls** [comment]
@yth1130, @fellen isn't criticizing your work, he's asking you to help improve the translation a bit more by fixing the mnemonics. The underscores mark a particular character as a keyboard shortcut for operating the button or menu item with the `alt` key for users who prefer that over using the mouse. For example, the first one at line 4495 is, in English, "_Company Report". An English-locale Linux user would be able to use `alt-r`, `alt-c` to access the Report>Company Report menu item when they have an Invoice tab open. To enable the same feature for a Korean user one of the characters in 회사 보고서 must be marked with a leading underscore; which one is best depends on what's already marked in the rest of the Korean translation of the Reports menu and what makes sense in Korean to represent that command.

**Comment by fellen** [comment]
> @fellen This is my first time participating in such a translation work, so I translated only simple words at first, but I will try my best in the future.

That would be nice as it was for several years unmaintained.

**Pull request merged**
