### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
Thanks!

@Gregory-K I get a few error messages:
```
msgfmt -c --check-accelerators="_" --statistics po/el.po 
po/el.po:4102: msgstr lacks the keyboard accelerator mark '_'
po/el.po:4202: msgstr lacks the keyboard accelerator mark '_'
po/el.po:5467: msgstr lacks the keyboard accelerator mark '_'
po/el.po:5630: msgstr lacks the keyboard accelerator mark '_'
po/el.po:8125: msgstr lacks the keyboard accelerator mark '_'
po/el.po:13106: msgstr lacks the keyboard accelerator mark '_'
po/el.po:14438: msgstr lacks the keyboard accelerator mark '_'
po/el.po:16273: msgstr lacks the keyboard accelerator mark '_'
po/el.po:16538: msgstr lacks the keyboard accelerator mark '_'
po/el.po:16782: msgstr lacks the keyboard accelerator mark '_'
po/el.po:16814: msgstr lacks the keyboard accelerator mark '_'
po/el.po:16822: msgstr lacks the keyboard accelerator mark '_'
po/el.po:17505: msgstr lacks the keyboard accelerator mark '_'
po/el.po:17961: msgstr lacks the keyboard accelerator mark '_'
po/el.po:17965: msgstr lacks the keyboard accelerator mark '_'
po/el.po:19387: msgstr lacks the keyboard accelerator mark '_'
po/el.po:23064: msgstr has too many keyboard accelerator marks '_'
msgfmt: found 17 fatal errors
2919 translated messages, 1433 fuzzy translations, 1028 untranslated messages.
```
Can you read
https://wiki.gnucash.org/wiki/Translation#Special_characters_and_other_tips
and try to fix them?

**Comment by Gregory-K** [comment]
hmm.... I took a quick look. I'm currently under a demanding work schedule.  
Give me a week and I'll provide you a corrected `el.po` if it's OK (much easier than searching in Weblate).

**Comment by fellen** [comment]
No problem!

**Comment by fellen** [comment]
> I think it's OK. 17 keyboard accelerators were added. [el.zip](https://github.com/Gnucash/gnucash/files/8043436/el.zip)

I saw it just now, but was able to merge it: commit 48d4bae. In the future better create a Pull Request.

Yes, all warnings disappeared.

> Note: I'm not sure about duplicates though. I'll have to use GnuCash in Greek in order to spot them and that's a whole new endeavour that can be postponed till all strings are translated. _(Unless if `--check-accelerators` can provide relative warnings ?)_

That is the purpose of `msgfmt -c --check-accelerators="_" 
`

**Comment by Gregory-K** [comment]
Thanks, I wasn't sure about the pull request policy (for just a `.po` file). I'll follow that in the future.

**Pull request merged**
