### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
Thanks, although you were one day too late for the GnuCash 4.12 release. We need your work on saturday.

@LudLaf I got a warning:
```
msgfmt -c --check-accelerators="_" --statistics po/es.po 
po/es.po:8955: msgstr no tiene la marca del acelerador de teclado '_'
msgfmt: se encontró 1 error fatal
5400 mensajes traducidos, 1 traducción difusa.
```
Can you read https://wiki.gnucash.org/wiki/Translation#Special_characters_and_other_tips
to fix:
```
msgid "Tab P_osition"
msgstr "<b>Posición de pestaña</b>"
```
@ovari same for you, still 114 errors.

@sarekashi also:
```
msgfmt -c --check-accelerators="_" --statistics po/id.po 
po/id.po:5789: msgstr kuran tanda akselerasi keyboard '_'
msgfmt: ditemukan 1 kesalahan fatal
5187 pesan diterjemahkan, 189 terjemahan fuzzy, 25 pesan belum diterjemahkan.
```
in
```
msgid "Stock Ass_istant"
msgstr "Asisten Saham"
```

**Comment by ovari** [comment]
> @ovari same for you, still 114 errors.

@fellen can you please advise which `Strings status` in [Weblate](https://hosted.weblate.org/projects/gnucash/gnucash/hu/) should be clicked to find the 114 errors? Thank you

**Comment by fellen** [comment]
> @fellen can you please advise which `Strings status` in [Weblate](https://hosted.weblate.org/projects/gnucash/gnucash/hu/) should be clicked to find the 114 errors? Thank you

Weblate is still missing this test. Perhaps easiest is to compare them in 
https://hosted.weblate.org/browse/gnucash/gnucash/hu/?offset=1&q=_&sort_by=source&checksum=
If the right side is missing `_`, fix it.

Another way: in PR #1441 I added the list with the line numbers. You could download hu.po, fix it locally and uoload it again.

**Comment by ovari** [comment]
@mocsa can you please fix the keyboard accelerators for magyar?

**Pull request merged**
