### PR TITLE
Find account

### PR DESCRIPTION
**Pull request by Bob-IT**
The first patch fixes the hidden and Tax options on Accounts as they are not being read correctly. I have used the same procedure that was used for the place holder value.

The second patch adds the option to search for an account, once found, you can select it and it will be opened  in the account tree or if it is hidden the account edit dialogue will pop up. The menu option placement may need adjusting but I think it is OK. This was recently mentioned on the lists and thought it was an interesting idea.

### CODE REVIEW

**Comment by jralls** [comment]
Um, what problem are you fixing with the first commit? Is there a bug report?

I don't think automatically opening the register is the right thing to do. The search should just select the found account in the tree-view. If it's hidden perhaps the search could open a dialog offering to show hidden and zero-value files, or maybe just silently override those setting for that particular account and its parents.
With that in mind, GtkTreeView has a built-in search function that kicks in when you type at it. That seems to be disabled (maybe it's normally enabled on list-views?) in the accounts page. ISTM it would be better to handle the search that way than with a separate dialog box.

**Comment by Bob-IT** [comment]
Not sure if there was a bug report, this relates to master, but when I was looking to see what would happen if the account was hidden I realised that if you tried to hide an account it would still show in the account tree.

Regarding the search, the dialogue allows you to filter the account list, if the right one is listed, you can select it or double click on it and you will jump to that account in the account tree, will not open the register. If it is a hidden account, the account edit dialogue is raised allowing to un-hide it. There is also an option for the dialogue to stay open if required. Will look into the built-in search, not come across that before.

**Comment by jralls** [comment]
Account list filter is different from find account. We already have a filter-accounts dialog and it might makes sense to add your new feature to that and perhaps to change it from a dialog box to a panel with a show/hide button on the right side of the tree control. There's another filter option that can cause accounts to not be shown in the CoA window that you need to consider, 0 balance.

**Comment by cyphra** [comment]
Updated Spanish translation
[es.po.zip](https://github.com/Gnucash/gnucash/files/253066/es.po.zip)

**Comment by jralls** [comment]
@cyphra that is absolutely the wrong way to submit a translation update. Please first discuss your changes with the last translator, Francisco Javier Serrador <fserrador@gmail.com> and then present your changes either in your own pull request (meaning you have to learn to use git and make a PR) or on the mailing list. Please use gzip rather than zip for compression if you do the latter.
Note that we won't accept your changes unless we hear from Francisco that they're OK.

**Comment by Bob-IT** [comment]
I really should be more precise in the words I use. The find dialogue to start with lists all the accounts which you can easily browse or by entering a string and pressing the search button, the list will be reduced to the entries that contain the string in the full account path. From here you can select a particular account and then jump to the account in the account tree. This is achieved by adding the ability to override the account tree filter for that session and is used when the account is hidden, not used or has zero balance.
 
I have looked at the built in tree view search option and it is all ready enabled, it searches the account name, code and description columns but only if they are visible, collapsed leafs are not searched and it will only find the first match unless I have missed a key sequence.

**Comment by jralls** [comment]
Sorry for leaving this to stew for so long. I just rebased it on master and tried it out. Seems to work OK. Some design comments, should be easy to fix:
* The radio group at the top, "search from root" and "search from sub account" doesn't seem to ever enable the second choice.
* The check boxes for placeholder, hidden, not used, and balance zero look like controls rather than indicators because you used GtkCellRendererToggle, which is intended to be used as a selector control. I think it would be better to use GtkCellRendererPixbuf, setting is-expander to true, pixbuf-expander-open to GTK_STOCK_OK, pixbuf-expander-closed to GTK_STOCK_NO, and setting the is-expanded property TRUE or FALSE as appropriate.
* I think that the View menu is a weird place to put "Find Account...", especially when it's visible on all tabs. Users expect Find menu items to be under Edit. Yes, View>Filter By... is there, but what Filter By... dialog box you get depends on what kind of tab has focus.

We also need this new feature documented in the Help. That's a different repo so it can't go on this PR.

**Comment by Bob-IT** [comment]
Changed to use cell render pixbuf as suggested but only displaying image when column is true.
The search from sub account is only enabled when you right click an account for the popup menu.

**Comment by jralls** [comment]
Better, but the radio group still bugs me. Is it too hard to detect the selected account when it's launched from the main menu instead of the context menu? If so, how about hiding the whole control in that case?

Would you please rebase the feature branch to make it current? I just did with no conflicts; if you do it and force-push then github will recognize the merge.

One other thing: Please use &lt;primary>I instead of &lt;control>I for the accelerator. &lt;primary> does "command" on Macs and "control" everywhere else.

**Comment by Bob-IT** [comment]
I decided it looked better if I hid the radio buttons when dialogue started from main menu and then show them from the context menu. The last commit changes all the accelerator keys defined with control to primary.

**Comment by jralls** [comment]
Merged after a rebase. Thanks!

**Pull request closed without merging**
