### PR TITLE
gnc:format

### PR DESCRIPTION
**Pull request by christopherlam**
better than `format`

```scheme
(gnc:format "${document} from ${owner}"
 'owner "customer"
 'document "invoice")
```

will return

`"invoice from customer"`

### CODE REVIEW

**Comment by jralls** [comment]
This handles only string arguments, i.e. `~a` or `~s`, right?

**Comment by christopherlam** [comment]
well ~a and ~s can handle any scm object -- this code will handle string values only (thanks to the `(? string? value)` match pattern.

**Comment by jralls** [comment]
True but the result might not be what you want or expect particularly with numbers. That might be a corner-case for translatable strings and this makes it a lot easier on translators.

**Comment by jralls** [comment]
Converting all of the msgids is going to be a massive re-translation effort. We can automate the weblate languages but the TP translators maintain their own po files and ignore any changes we make. @fellen any thought on how/when to roll this out?

**Comment by christopherlam** [comment]
> True but the result might not be what you want or expect particularly with numbers. That might be a corner-case for translatable strings and this makes it a lot easier on translators.

Ok. The motivation for limiting to strings now was to narrow the input. Anyway, I've modified to convert all to string. The latest change is to improve error reporting especially if translator doesn't insert a valid ${symbol}.

**Comment by christopherlam** [comment]
As @fellen has requested this now has tests. I don't think all ~a or ~s need to be overhauled. Only the difficult strings could be modified.

**Pull request closed without merging**
