### PR TITLE
Python gettext localize clean

### PR DESCRIPTION
**Pull request by c-holtermann**
Cleanup of PR "Python gettext localize (draft)" #506

### CODE REVIEW

**Comment by c-holtermann** [comment]
Hmm. Some other files got included that I didn't want to.

**Comment by c-holtermann** [comment]
broken

**Comment by gjanssens** [comment]
There's no need to close the PR. You can just clean up your local branch and force push the result to github. The PR should be updated automatically. Anyway, continuing on #655 ...

**Comment by fellen** [comment]
@c-holtermann It seem you merged maint into branch.
Instead you should have rebased your branch on maint.

**Comment by c-holtermann** [comment]
Well - whatever I exactly did :) I tried to make it better in #655

**Pull request closed without merging**
