### PR TITLE
Translation de

### PR DESCRIPTION
**Pull request by Mechtilde**
correct some translations and shortcuts

### CODE REVIEW

**Comment by gjanssens** [comment]
Thank you for the updates. I have committed them to maint after a rebase. They will appear in the next gnucash release.

**Comment by fellen** [comment]
Die »Anführungszeichen« sollten erhalten bleiben, es sei denn, neuere Gnome-HIGs bestimmen etwas anderes. In dem Fall sollten sie aber durchgängig in der ganzen Datei ersetzt werden und nicht nur auf der einen Seite eines Wortes.

**Comment by jralls** [comment]
It doesn't make sense to re-open a merged PR. It can't be un-merged and after almost 3 months there's no good way to append more changes to it.
You can fix the problem yourself, open a bug, or ask Mechtilde to make a new PR via email or IRC.

**Comment by fellen** [comment]
The reopen was intended as a pointer for myself because I had to interrupt my review.
And there at least one other issue, which should not have passed:

commit 5671408:
-"POT-Creation-Date: 2016-01-05 05:25+0100\n"
+"POT-Creation-Date: 2016-01-02 13:27+0100\n"

Here we are switching back to an older template version. This should not happen, Geert.
Mechtilde did not rebase after my last commit.

FYI: I will close it again after fixing,

**Comment by jralls** [comment]
Hmm.
Maybe we should have a policy about POT merges.  In this case it seems extremely unlikely that there would be a difference between the potfiles between 2 and 5 January except perhaps  a line-number change or two. But in general and in order to maintain some amount of sanity particularly with respect to the Translation Project perhaps we should create new potfiles and merge them only at release time?

**Comment by fellen** [comment]
No, that day I removed a bunch of obsolete strings.
IMHO, we should msgmerge at least on release dates. But yes, we should discuss the policy.

About the prefered quotation signs, I opended https://bugzilla.gnome.org/show_bug.cgi?id=769344 - Update strings to new human interface guide (HIG).

John, do you have any idea about the build fails on travis?

Closing this again, because my review is finished.

**Comment by gjanssens** [comment]
A late reply as I'm still  catching up after the holidays...

Frank, I missed the fact that Mechtilde didn't rebase after your last commit. Sorry about that. I'll pay more attention in the future.

As for policy, I agree merging on release dates is a good idea.

**Pull request closed without merging**
