### PR TITLE
Build with -Wunused

### PR DESCRIPTION
**Pull request by richardcohen**
Builds with gcc 12.2.0 and clang 15.0.6 on ubuntu 22.10

### CODE REVIEW

**Comment by jralls** [comment]
@richardcohen I need you to clean up the conflicts, force-push, and remove the draft tag in order to merge this.

**Comment by richardcohen** [comment]
@gjanssens the Mac build failure seems to be from your change https://github.com/Gnucash/gnucash/commit/e5de32fd730d8dae06f196e7a7dcb739575418c1
```
In file included from /Users/runner/work/gnucash/gnucash/gnucash/import-export/csv-imp/gnc-import-tx.cpp:43:
In file included from /Users/runner/gnucash/inst/include/boost/regex.hpp:34:
In file included from /Users/runner/gnucash/inst/include/boost/regex/v5/regex.hpp:31:
In file included from /Users/runner/gnucash/inst/include/boost/regex/regex_traits.hpp:30:
In file included from /Users/runner/gnucash/inst/include/boost/regex/v5/regex_traits.hpp:27:
In file included from /Users/runner/gnucash/inst/include/boost/regex/v5/cpp_regex_traits.hpp:34:
In file included from /Users/runner/gnucash/inst/include/boost/regex/v5/object_cache.hpp:24:
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/map:726:17: error: no viable overloaded '='
        __ref() = __v.__get_value();
        ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~
...
/Users/runner/work/gnucash/gnucash/gnucash/import-export/csv-imp/gnc-import-tx.cpp:895:46: note: in instantiation of member function 'std::map<const GncTransPropType, std::string>::operator=' requested here
        std::get<PL_ERROR>(*parsed_lines_it) = all_errors;
                                             ^
```

**Comment by gjanssens** [comment]
Interesting. I'll check this out later this week (if @jralls  doesn't beat me to it). May be a gcc vs clang thing ?

**Comment by richardcohen** [comment]
> Interesting. I'll check this out later this week (if @jralls doesn't beat me to it). May be a gcc vs clang thing ?

FWIW, on Ubuntu 22.10, clang 15.06, boost 1.74.0 compiles OK

**Comment by jralls** [comment]
> FWIW, on Ubuntu 22.10, clang 15.06, boost 1.74.0 compiles OK

You're getting thrown off by the include path, it doesn't have anything to do with boost. @gjanssens uses std::map without including `<map>` explicitly, but boost-regex uses std::map so that's how <map> got included. It's a template instantiation error so you have to read down a bit to see what it's actually complaining about:
```
/Users/runner/work/gnucash/gnucash/gnucash/import-export/csv-imp/gnc-import-tx.cpp:895:46: note: in instantiation of member function 'std::map<const GncTransPropType, std::string>::operator=' requested here
[679](https://github.com/Gnucash/gnucash/actions/runs/4176926461/jobs/7233848029#step:8:680)
        std::get<PL_ERROR>(*parsed_lines_it) = all_errors;
```
Also Apple clang isn't quite the same as regular clang. Apple tweaks it a bit, including setting different defaults on what warns and what errors.

**Comment by jralls** [comment]
Thanks!

**Pull request merged**
