### PR TITLE
Update Croatian

### PR DESCRIPTION
**Pull request by milotype**
Some necessary corrections.

### CODE REVIEW

**Comment by milotype** [comment]
Can someone please complete this PR. 
I need to correct the README file one more time after this PR is commited (I've lost the "https" in the file and the BOM). I'm very sorry.

**Comment by jralls** [comment]
@milotype can't you fix the file and amend the commit from the github editor?

**Comment by milotype** [comment]
Yes, I can try that.

**Comment by milotype** [comment]
Ahhh, shit (sorry). I already deleted that branch.

**Comment by fellen** [comment]
But it is still on github. Got to files changed tab, view file, edit file.

**Comment by milotype** [comment]
I've found the files changed tab, but not view and edit. The only edit is in the top right hand corner for editing the name of th PR. And the blue plus is probably for adding a comment to a specific line of code, not for changing it (right?).
edit file

**Comment by milotype** [comment]
soory, wrong image ...
edit file

**Comment by fellen** [comment]
behind the 3 dots at the right of the file.

**Comment by jralls** [comment]
How did you make the commit?

**Comment by milotype** [comment]
I usually make a fresh fork. Then i create a new branch on my fork. I commit files to my fork. Then I wait for confirmation, that the branch has no conflicts. Then I send s PR to the original repository. (I hope I got all the git-wording right ;-)

**Comment by milotype** [comment]
No luck, the Edit function is grayed out (Tooltip Info: You must be on a branch to make or propose changes to this file)

**Comment by fellen** [comment]
OK, I have commited them after rebasing.

You can now clone again for the corrections.

**Comment by milotype** [comment]
Great, thank you!

**Comment by jralls** [comment]
> No luck, the Edit function is grayed out (Tooltip Info: You must be on a branch to make or propose changes to this file)

Were you trying to edit it from the PR or from your branch that the PR is based on? You want the latter, and the PR should automatically update with any changes you make.

**Pull request closed without merging**
