### PR TITLE
Update hr.po

### PR DESCRIPTION
**Pull request by milotype**
Some translation corrections and file clean-up.

### CODE REVIEW

**Comment by fellen** [comment]
Thanks, commited.

Because we are 2 weeks before the next release, you might consider to 
https://wiki.gnucash.org/wiki/Translation#Update_an_existing_.po_file.

Prepopulate your file with translations from other projects
https://wiki.gnucash.org/wiki/Translation#GTK3
might in this context also be of interest.

**Comment by fellen** [comment]
Another question, where I am not sure:
Did you provide a
https://wiki.gnucash.org/wiki/Windows_Installer_Translation
and it got lost?

**Comment by milotype** [comment]
> Because we are 2 weeks before the next release, you might consider to
> https://wiki.gnucash.org/wiki/Translation#Update_an_existing_.po_file.
I'm not sure what you mean – my translation is build upon .pot 3.5, and I actually removed unnecessary/undefined data.
 
> Prepopulate your file with translations from other projects
> https://wiki.gnucash.org/wiki/Translation#GTK3
> might in this context also be of interest.
That translation is overall OK.

**Comment by fellen** [comment]
Oh, I meant, start with
https://wiki.gnucash.org/wiki/Translation#Get_a_fresh_template
Think of it as 3.6pre pot-

**Comment by milotype** [comment]
> Did you provide a https://wiki.gnucash.org/wiki/Windows_Installer_Translation
> and it got lost?
Hmm, I think I didn't. I did transalte "README-hr.win32-bin.txt", which probably isn't what you are talking about. Where can I find the file for the windows installer? Can you please give me the links to the necessary files I would need to translate?

**Comment by fellen** [comment]
https://github.com/Gnucash/gnucash-on-windows/blob/master/inno_setup/gnucash-mingw64.iss

**Comment by milotype** [comment]
> Oh, I meant, start with https://wiki.gnucash.org/wiki/Translation#Get_a_fresh_template
> Think of it as 3.6pre pot-
Please send me the 3.6pre pot-file … I don't know how to make .pot files myself. For .pot-files, I use the file from: http://translationproject.org/domain/gnucash.html

**Comment by fellen** [comment]
About Innosetup, it is provably easier to review the croatian file from http://www.jrsoftware.org/files/istrans/ Section "Unofficial translations"

**Comment by milotype** [comment]
> https://github.com/Gnucash/gnucash-on-windows/blob/master/inno_setup/gnucash-mingw64.iss
> search [Languages]
So if I follow/duplicate the german stuff (whatever I find with "de") and translate it to croatian, would that be it?

**Comment by milotype** [comment]
> About Innosetup, it is provably easier to review the croatian file from http://www.jrsoftware.org/files/istrans/ Section "Unofficial translations"
Overall, that file looks OK.

**Comment by milotype** [comment]
@fellen 
I haven't sent anything to GitHub yet, but I've translated the english original strings and added them to the file prefixed with "hr.". I've also added the following lines to the file "gnucash-mingw64.iss":

- Name: "hr"; MessagesFile: "compiler:Languages\Croatian.isl"; InfoAfterFile: "@INST_DIR@\share\doc\@PACKAGE@\README-hr.win32-bin.txt"
- hr.LanguageCodePage=0

I found the Croatian in the "unofficial" folder of Inno Setup Translations. It's not quite my taste, but it's fully translated. But it doesn't seem to be utf-8 encoded, as I keep seeing "special" characters for some diacritics (I only have my mac, no windows).
My question is, should I simply: 
1. add a copy of the croatian file "Croatian.isl" (version 5.3.3) into the folder "gnucash-on-windows/inno_setup/"?
2. send a merge request with my changes for "gnucash-mingw64.iss" in the same folder?

**Comment by milotype** [comment]
@fellen 
> > Prepopulate your file with translations from other projects
> > https://wiki.gnucash.org/wiki/Translation#GTK3
> > might in this context also be of interest.
Do I understand that right – I should merge the gnucash .po-file and the gtk .po-file together? I would open both files in my BBEdit programm and simply copy all of gtk-data (without the header data) into the gnucash .po-file at the end? That will greatly increase the file with 1089 new strings.

**Comment by jralls** [comment]
@milotype Inno Setup used to have a non-Unicode version and it required .isl files to be encoded with the code page for the language. The Unicode version could and can read those, so no doubt they provided only the code-page translations to save space and haven't bothered to transcode them since they dropped the non-Unicode version.

Unofficial translations like the Croatian one must be added to the gnucash-on-windows repo alongside the Latvian and two Chinese ones. The line in gnucash-mingw64.iss will be 
```
Name: "lv"; MessagesFile: "@GC_WIN_REPOS_DIR@\inno_setup\Croatian-5.5.3.isl"; InfoAfterFile: "@INST_DIR@\share\doc\@PACKAGE@\README-hr.win32-bin.txt"
```
To make your PR you'll make that change and add the hr language code page line to gnucash-mingw64.iss, copy the downloaded Croatian.isl to inno_setup/Croatian-5.5.3.isl  , do
```
git add inno_setup/Croatian-5.5.3.isl gnucash-mingw64.iss
git commit -m "Add Croatian translation."
```
and make a PR out of it.

Your new README-hr.win32-bin.txt goes in a separate PR to this repo.

**Comment by milotype** [comment]
@fellen 
Please let me know about my question on merging gnucash .po-file and the gtk .po-file. I'm still uncertain, whether I understood you correctly.

@jralls 
I've just made a pull requests on gnucash-on-windows for the .iss and .isl files. Please check my comments there.
I 've also updated "Update README-hr.win32-bin.txt", which I've translated some time ago.

**Comment by fellen** [comment]
I just added a new section in
https://wiki.gnucash.org/wiki/Translation#Prepopulate_your_file_with_translations_from_your_glossary_and_other_projects

Can you help me to improve it? Is it understandable or ways too abstract?

**Comment by milotype** [comment]
> https://wiki.gnucash.org/wiki/Translation#Prepopulate_your_file_with_translations_from_your_glossary_and_other_projects
> Can you help me to improve it? Is it understandable or ways too abstract?

Sorry, I can't. I'm no programmer and I don't understand a word of it.

As mentioned before, all I could do is open both files in my BBEdit programm and simply copy all of gtk-data (without the header data) into the gnucash .po-file at the end. (That will greatly increase the file with 1089 new strings) … but that is probably not the way to do it …

**Comment by fellen** [comment]
Intro added.

**Pull request merged**
