### PR TITLE
add a shipping contact name column for FindCustomerDialog

### PR DESCRIPTION
**Pull request by TianXing-Yi**

### CODE REVIEW

**Comment by TianXing-Yi** [comment]
four parameter options, only three-column results.
Screenshot below:
[Before](https://github.com/TianXing-Yi/GImage/blob/master/1-Before.png)
[After](https://github.com/TianXing-Yi/GImage/blob/master/1-After.png)

**Comment by gjanssens** [comment]
I'd have gone the other way around and add a column for shipping contact.

**Comment by fellen** [comment]
No, some companies have 2 different addresses like
a real street for goods and a PO box for invoices or 
a factory for the goods, but the head office for invoices.

That is implemented for customers. 
@gjanssens The issue is, the shipping address is missing in vendors. How can I return goods?

**Comment by gjanssens** [comment]
> That is implemented for customers.
> @gjanssens The issue is, the shipping address is missing in vendors. How can I return goods?

It was never implemented for vendors. As it stands now you'll have to dig up your paper invoice and find the proper return address there.

**Comment by jralls** [comment]
Thanks!

**Pull request merged**
