### PR TITLE
update ru.po with a new gnucash.pot file

### PR DESCRIPTION
**Pull request by DiMan**

### CODE REVIEW

**Comment by fellen** [comment]
Hi Dmitry,

unfortunately JRalls committed PR 209 and we get now conflicts. Can you discuss the best solution to resolve them with ashed? I am still writing more on his PR.

Regards
Frank

**Comment by ashed** [comment]
Hello, DiMan.
[fellen](https://github.com/fellen) wrote in PR [#209](https://github.com/Gnucash/gnucash/pull/209)
Oops, I was not ready with my comment: We got 2 PRs for ru.po, which now conflict. This one is based on an very old template, PR#204 merged a fresh template. As usual the merge produced noise. This contains some noise from switching the tool. I would like to ask booth authors to submit next time 2 commits in one working branch:  preparations like msgmerge or reformatting, real translation work. Then it is much easier to read.  My few hours russian are much to less to decide which is the easier way to resolve the conflict between this two PRs. @ashed , can you discuss it with DiMan? I will be the next week here to help you.
--
What kind of submitting of our PR do you prefer, colleague?

1. preparations like msgmerge or reformatting,
2. handy translation work with finger tips.
With kind regards
**ashed**

**Comment by jralls** [comment]
Most of the conflicts are pretty trivial, e.g.
```
<<<<<<< HEAD
"этом счёте"
=======
"этом счете"
>>>>>>> c12fa34e28d60016b0ca463dd93fe0da1dda940b
```
(The first is @ashed's, the second @DiMan's.) or just msgmerge artifacts where a string in a source file is a few lines different.  Being completely illiterate in Russian I have no idea what, if any, difference there is between ё and е; I didn't even know that cyrillic *had* umlauts until just now. With guidance from @ashed and @DiMan I could resolve those two sorts of conflicts.

There would remain a very few conflicts that are significant changes in wording, e.g.
```
<<<<<<< HEAD
"Если включено, то GnuCash специально отменит обратную совместимость файла "
"данных со старыми версиями GnuCash, что приведет к невозможности загрузить "
"данные в более старую версию GnuCash. Иначе, GnuCash будет записывать данные "
"только в формате, читаемом старыми версиями."
=======
"Если включено, то GnuCash специально отменить обратную совместимость файла "
"данных со старыми версиями GnuCash, что приведет к невозможности загрузить "
"более старой версией GnuCash. В противном случае, GnuCash будет записывать "
"данные только в формате, доступном старым версиям."
>>>>>>> c12fa34e28d60016b0ca463dd93fe0da1dda940b
```
(Again, @ashed's version is first). On those the two of them will have to negotiate which is better.

One other note: ```msgfmt --stat``` on @ashed's translation reports 4532 translated messages, 34 fuzzy translations, 59 untranslated messages and on @DiMan's 4438 translated messages, 81 fuzzy translations, 158 untranslated messages.

**Comment by DiMan** [comment]
Hi, thanks for your comments. I only updated the .po file for future translation. I think, it would better to ignore my PR. I can update the file after PR 209.

**Comment by jralls** [comment]
OK, thanks.

**Comment by fellen** [comment]
@DiMan can you set in "Language-Team: russian <ru@li.org>\n"
the email address or URL of your group to avoid such issues in the future?
Thanks.

**Comment by DiMan** [comment]
@Frank H. Ellenberger:
In "`Language-Team: russian ru@li.org`" I set the URL of our group: `gnucash-ru@googlegroups.com`
(see PR #211). I write now to all users, who translated texts for GnuCash, and try to organize our communication in one place.

@all: счёт vs. счет. 
It is right: "e" and "ё" are two different charakters in cyrillic language. But very often "ё" is written as "e".
I will check the glossary file and adjust it, if it is necessary.

**Pull request closed without merging**
