### PR TITLE
[account.cpp] account->children is a vector

### PR DESCRIPTION
**Pull request by christopherlam**
1 step towards better memory management...

### CODE REVIEW

**Review by christopherlam — COMMENTED** [review]
some more c++isms

**Comment by christopherlam** [comment]
This branch causes segfault when deleting an account from ui...
https://lists.gnucash.org/pipermail/gnucash-user/2024-July/112255.html

**Comment by jralls** [comment]
OK. What do you want/intend to do about it?

**Comment by christopherlam** [comment]
Can't find anything particularly wrong so I'd be inclined to revert

**Comment by jralls** [comment]
It's [Bug 799347](https://bugs.gnucash.org/show_bug.cgi?id=799347). I can reproduce it in the debugger but haven't quite figured out what it's trying to dereference that's crashing, nor what exactly is different about what we're handing to the tree model.

**Comment by jralls** [comment]
@christopherlam I think https://github.com/Gnucash/gnucash/commit/60ccca017f1be3af2caebb8a9d0c82a197f1da4f fixes it. Comments should explain why.

**Pull request merged**
