### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
Thanks!

@Kaligula0 I got a few warnings:
```
msgfmt -c --check-accelerators="_" --statistics po/pl.po 
po/pl.po:4086: w msgstr brakuje skrótu oznaczenia klawiszowego „_”
po/pl.po:19965: w msgstr brakuje skrótu oznaczenia klawiszowego „_”
po/pl.po:21700: w msgstr brakuje skrótu oznaczenia klawiszowego „_”
msgfmt: znaleziono 3 błędy krytyczne
3570 przetłumaczonych komunikatów, 1320 tłumaczeń budzi wątpliwości, 511 nieprzetłumaczonych komunikatów.
```
To  understand that log, 'po/pl.po:4086' means line 4086' in pl.po—you can download that format from weblate.
The first is about
```
#: gnucash/gnome/gnc-plugin-page-account-tree.c:258
msgid "_Cascade Account Properties..."
msgstr "Przenieś właściwości konta..."
```
Can you read https://wiki.gnucash.org/wiki/Translation#Special_characters_and_other_tips and try to fix them?

**Comment by Kaligula0** [comment]
I'll check that.

**Comment by Kaligula0** [comment]
1st and 3rd is already corrected on Weblate. I also corrected them in a file locally. But I have no idea how to check where the 2nd one is in GUI.
4086: "Przenieś _właściwości konta..."
19965: "Potwierdź hasło"
21700: "Importuj c_eny z pliku CSV…"

**Comment by Kaligula0** [comment]
Final version:
4086: "Przenieś _właściwości konta..."
19965: "_Potwierdź hasło"
21700: "Importuj c_eny z pliku CSV…"

**Pull request merged**
