### PR TITLE
Add ability to build GnuCash with CMake

### PR DESCRIPTION
**Pull request by codesmythe**
Adds CMakeLists.txt and other CMake files to allow GnuCash to be built with CMake. 

Details are available in cmake/README_CMAKE.txt.

Windows now builds in under five minutes. You'll need my pull request on gnucash-on-windows.git as well.

I've been careful to only change CMake related files, so should coexist peacefully with existing auto tools build.

### CODE REVIEW

**Comment by jralls** [comment]
This is very good. 

I have some issues with README_CMAKE.asc though: First is that it's asc, please make it either plain text. README files shouldn't need rendering. If you insist on formatting, then use Doxygen and put it in src/docs with some name other than README.
Next is that it refers to your repo, and that will be incorrect when it's merged into GnuCash.
The last is relatively minor: Dependencies aren't handled autotools any more than they are by cmake, so building first with autotools isn't going to accomplish anything.

**Comment by codesmythe** [comment]
My quest to get AsciiDoc into GnuCash is foiled again! :-)

My original idea when writing the doc was to have people kick the tires before I submitted the pull request, so that is why it refers to my repos. I decided to just do the pull request and forgot to update the docs. 

Anyway, I'll update the doc and convert it plain text (Asciidoc is already pretty close). 

I rebased on current master and things are broken, so I'm working on getting it fixed.

**Comment by codesmythe** [comment]
Doc has been updated. Rebased on master, commits squashed.

**Comment by jralls** [comment]
And merged, thank you *very* much!

**Comment by codesmythe** [comment]
You're welcome. I've been a long time user of GnuCash, and am happy to be able to give a little back.

On with the tests...

**Pull request merged**
