### PR TITLE
Added forward declaration for struct GncGUID

### PR DESCRIPTION
**Pull request by limitedAtonement**
I also removed the guid.hpp include where I could.

### CODE REVIEW

**Comment by jralls** [comment]
With the forward declaration can't the ```#include "guid.hpp"``` go after the C include block with the rest of the C++ includes?

**Comment by limitedAtonement** [comment]
Yes, it looks like that works. It's much less intrusive that way, and I've rebased and force-pushed to come up with a new pull request.

**Comment by jralls** [comment]
Unfortunately:
```
In file included from /Users/john/Development/gtk-sources/gnucash-git/src/libqof/qof/qofid.h:82:
/Users/john/Development/gtk-sources/gnucash-git/src/libqof/qof/guid.h:95:9: error:
      'guid_new_return' has C-linkage specified, but returns incomplete type
      'GncGUID' which could be incompatible with C [-Werror,-Wreturn-type-c-linkage]
GncGUID guid_new_return (void);
```

**Comment by limitedAtonement** [comment]
That's an interesting warning. What TU is being compiled by what compiler when that warning is emitted? I don't get that warning (GCC 6.1.1); I checked by doing a from-scratch build just now.

**Comment by jralls** [comment]
It was in ```src/libqof/qof/gnc-aqbanking-templates.cpp:```, the first module in qof. Compiler is Apple LLVM version 7.3.0 (clang-703.0.31) called as 'gcc', which changes its behavior slightly.

**Comment by limitedAtonement** [comment]
Well, I can't imagine why gcc doesn't need the definition, but clang does. I'm thinking I should go back to putting the include on top then?

**Comment by jralls** [comment]
Clang has lots of warnings that gcc doesn't, and keeps adding them, all to protect us from doing dumb things. I agree with this one, if the compiler doesn't know how much space to make for the GncGUID it's likely to pick the wrong size, like sizeof(int) or sizeof(int*).

The "old" commit has the same problem. To fix it every *.cpp that includes guid.h will need to include guid.hpp before its extern "C" block. That's a lot of files.

The better solution would be to remove guid_new_return. It's used only in the sql backend where it can easily be replaced with a constructor and 3 places in reports -- meaning it's passed to guile, so we just need to change gnc-engine.i to use guid_new instead of guid_new_return and tell guile how delete the ptr.

**Comment by jralls** [comment]
Hmm. Removing guid_new_return() gets to a new warning from src/engine/kvp-scm.cpp:
In file included from /Users/john/Development/gtk-sources/gnucash-git/src/engine/kvp-scm.cpp:10:
/Users/john/Development/gtk-sources/gnucash-git/src/engine/engine-helpers-guile.h:41:9: error:
      'gnc_scm2guid' has C-linkage specified, but returns user-defined type
      'GncGUID' which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
GncGUID gnc_scm2guid(SCM guid_scm);

**Comment by limitedAtonement** [comment]
Sorry I haven't said anything, I am reading carefully. So we're looking at an honest divergence between what C and C++ use; no trickery this time. That sounds like it may be the most straight forward, even if it may require more code short term. We're also taking boost::uuids::uuid out of the inheritance hierarchy and making `GncGUID` a plain base class.

**Pull request closed without merging**
