### PR TITLE
Commit

### PR DESCRIPTION
**Pull request by c-holtermann**
Based on discussion on bugtracker: https://bugs.gnucash.org/show_bug.cgi?id=796137

Fix problems with qof_query_search_for in python bindings resulting from switch to Python 3 and different string handling.

### CODE REVIEW

**Comment by jralls** [comment]
This doesn't look right. I don't see any commit about QofQuery and there are a bunch of commits about other things, including merges. A pull request should never have merge commits in it.

**Comment by c-holtermann** [comment]
Hmm, it seems as if I have to clean up history. https://github.com/Gnucash/gnucash/pull/408/commits/2b4bb4df75cf9a022b68e9b14d7aaf1c62f397bf, https://github.com/Gnucash/gnucash/pull/408/commits/f1d66eb5402dc3b902f28caa8a6f883dd5ace87f and https://github.com/Gnucash/gnucash/pull/408/commits/3bbe44ec700f97a79efa2352a59103ce8bc4e130 are the relevant commits.

**Comment by c-holtermann** [comment]
But in addition the gslist part fails to build in Travis. That needs attention.

**Comment by c-holtermann** [comment]
Partial revert 3bbe44e to see if it makes Travis work

**Comment by c-holtermann** [comment]
Fixing the history of my fork is a bit tricky. I guess I will only have time to figure that out in two weeks or so (maybe someone can give me a hint how to do that ?). So feel free to have a look at the relevant commits and discuss them or someone with a clean history copies this pull request.

**Comment by c-holtermann** [comment]
I think I managed to provide a clean history now. Created 2nd pull request (https://github.com/Gnucash/gnucash/pull/410) and will close this one.

**Pull request closed without merging**
