### PR TITLE
high level python wrappers for app-utils

### PR DESCRIPTION
**Pull request by c-holtermann**
I'd like to have wrapper methods that return instances

### CODE REVIEW

**Comment by jralls** [comment]
You only need the `Session` one. The other two are already wrapped as `Session.get_book()`  and `Book.get_root_account()`.

**Comment by c-holtermann** [comment]
@jralls ok. I'll remove them. I'll look throught the rest of the functions visible for python in _sw_app_utils and see if any other makes sense.

**Comment by jralls** [comment]
#678 replaces this, right?

**Comment by c-holtermann** [comment]
This is different to and based on #678.

**Comment by jralls** [comment]
@c_holterman, it is now. It wasn't when I wrote that. This is OK now, I'll merge it when #678 is ready.

**Comment by c-holtermann** [comment]
Thanks!

**Comment by jralls** [comment]
Thanks!

**Pull request merged**
