### PR TITLE
Fix latex_invoice.py

### PR DESCRIPTION
**Pull request by srwalter**
Various fixes to get latex_invoice.py working again

### CODE REVIEW

**Comment by c-holtermann** [comment]
I'll have a look at it today.

**Comment by c-holtermann** [comment]
@srwalter Thank you for the fixes. The scripts are broken for me as well in the current setting and work again with the provided patches. It would be nice to document when or why they stopped working but that's just nice to have. One thing: could you please remove the decode lines from Invoice.tex.tmpl as well as that is the template used by gncinvoice_jinja.py ?

**Comment by srwalter** [comment]
> @srwalter Thank you for the fixes. The scripts are broken for me as well in the current setting and work again with the provided patches. It would be nice to document when or why they stopped working but that's just nice to have. One thing: could you please remove the decode lines from Invoice.tex.tmpl as well as that is the template used by gncinvoice_jinja.py ?

Done!

**Comment by c-holtermann** [comment]
Thank you for the fixes. Looks good to me. Approval to merge from my side.

**Comment by fellen** [comment]
Thanks!

**Pull request merged**
