### PR TITLE
[test-transaction.scm] Added test to show odd behavior when accessing content of rows using a "minus even" location

### PR DESCRIPTION
**Pull request by dawansv**
Discovered this while working on test for  PR #1617.  It appears that trying to access rows from the bottom, using a "minus row-number" argument, fails on even numbered rows but not on odd numbered ones.

I have added a simple test to test-transaction.scm to demonstrate it failing. Using the default data for the bank account with a very simple table on which only date, description, account and amount is left, with no grouping or totals or subtotals.  Yet "minus even" rows (-2, -4, -6) fails by returning #f instead of their content.

```
[fail] line:966, test: Row -6
transaction.scm/minus-even row issue
 -> expected: ("11/03/23" "$103 income" "Root.Asset.Bank" "$103.00")
 -> obtained: #f
[pass] line:969, test: Row -5
[fail] line:972, test: Row -4
transaction.scm/minus-even row issue
 -> expected: ("11/15/23" "$22 expense" "Root.Asset.Bank" "-$22.00")
 -> obtained: #f
[pass] line:975, test: Row -3
[fail] line:978, test: Row -2
transaction.scm/minus-even row issue
 -> expected: ("12/09/23" "$109 income" "Root.Asset.Bank" "$109.00")
 -> obtained: #f
[pass] line:981, test: Row -1
```

### CODE REVIEW

**Comment by dawansv** [comment]
Here is the html file from the test result showing the full table of data. One must remove the .log extension (it's not possible to attach files with just an .html extenstion).
[test-trep-read-rows-from-the-bottom.html.log](https://github.com/Gnucash/gnucash/files/11362583/test-trep-read-rows-from-the-bottom.html.log)

**Comment by christopherlam** [comment]
I think this bug lies within sxml. I've sent a bug report to guile maintainers: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=63196 and we'll await their response. Here's a smaller .scm using the same input html file. I think the source is the cause: https://git.savannah.gnu.org/cgit/guile.git/tree/module/sxml/xpath.scm#n181

```scheme
(use-modules (sxml simple))
(use-modules (sxml xpath))
(use-modules (ice-9 textual-ports))

(define html (call-with-input-file "/tmp/test-file.html" get-string-all))
(define sx (xml->sxml html))

;; note this path: try different indices for the tr tag:
;; odd numbers -1 -3 -5 are ok
;; even numbers -2 -4 -6 will fail
(define path '(// (table 1) // (tr -1)))

(format #t "html=[~s]\n" html)
(format #t "sxpath is [~s]\n" path)
(format #t "result is [~s]\n" ((sxpath path) sx))
```

and its output with `(tr -2)

```
html=[<SNIP>]
sxpath is [(// (table 1) // (tr -2))]
Backtrace:
In ice-9/boot-9.scm:
  1752:10 18 (with-exception-handler _ _ #:unwind? _ # _)
In unknown file:
          17 (apply-smob/0 #<thunk 7f52a7f0d2e0>)
In ice-9/boot-9.scm:
    724:2 16 (call-with-prompt _ _ #<procedure default-prompt-handle…>)
In ice-9/eval.scm:
    619:8 15 (_ #(#(#<directory (guile-user) 7f52a7f12c80>)))
In ice-9/boot-9.scm:
   2836:4 14 (save-module-excursion _)
  4388:12 13 (_)
In /home/chris/sources/sxml-bug.scm:
    15:30 12 (_)
In sxml/xpath.scm:
   254:18 11 (map-union #<procedure 7f52a46bdb40 at sxml/xpath.scm:…> …)
   254:18 10 (map-union #<procedure 7f52a46bdb40 at sxml/xpath.scm:…> …)
   254:18  9 (map-union #<procedure 7f52a46bdb40 at sxml/xpath.scm:…> …)
   254:18  8 (map-union #<procedure 7f52a46bdb40 at sxml/xpath.scm:…> …)
   254:18  7 (map-union #<procedure 7f52a46bdb40 at sxml/xpath.scm:…> …)
   252:22  6 (map-union #<procedure 7f52a46bdb40 at sxml/xpath.scm:…> …)
   252:22  5 (map-union #<procedure 7f52a46bd760 at sxml/xpath.scm:…> …)
   254:18  4 (map-union #<procedure 7f52a46d5ce0 at sxml/xpath.scm:…> …)
   254:18  3 (map-union #<procedure 7f52a46d5ce0 at sxml/xpath.scm:…> …)
   252:22  2 (map-union #<procedure 7f52a46d5ce0 at sxml/xpath.scm:…> …)
   484:19  1 (loop _ ((tr -2)))
   181:24  0 (_ _)

sxml/xpath.scm:181:24: yikes!
```

**Comment by dawansv** [comment]
Nice little test scm there. It gave me the idea of running the test repeatedly while simplifying the html code bit by bit. It didn't take long to discover that the problem goes away as soon as we remove the `<thead></thead>` and `<tbody></tbody>` tags.

Here are 2 super simplified html files (a tiny table with 4 one-cell rows); one works (no thead or tbody), the other one fails (with thead and tbody). Possibly you can pass this update in your bug report.

[test-simple-fail.html.log](https://github.com/Gnucash/gnucash/files/11366850/test-simple-fail.html.log)
[test-simple-pass.html.log](https://github.com/Gnucash/gnucash/files/11366851/test-simple-pass.html.log)

**Comment by dawansv** [comment]
I am closing this pull request as it was never meant to be merged and it is now to the guile maintainers to fix this issue with the `<thead></thead>` and `<tbody></tbody>` tags if they so choose. In the meantime whoever is writing tests for the scheme reports should be aware of this issue.

**Pull request closed without merging**
