### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/gnucash/gnucash/) for GnuCash/Program.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
Thanks!

@milotype I got 2 errors:
```
msgfmt -c --check-accelerators="_" --statistics po/hr.po 
po/hr.po:6139: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
po/hr.po:18016: msgstr lacks the keyboard accelerator mark '_'
msgfmt: found 2 fatal errors
5362 translated messages.

```

**Comment by milotype** [comment]
@fellen 
Thank you. I found only the plural form problem and corrected it on weblate just now:
msgid "Do you really want to delete this scheduled transaction?"

Can you tell me where the problem with the accelerator mark is?
Weblate doesn't seem to inform about such a problem.

**Comment by fellen** [comment]
> @fellen
> Thank you. I found only the plural form problem and corrected it on weblate just now:
> msgid "Do you really want to delete this scheduled transaction?"
> 
> Can you tell me where the problem with the accelerator mark is?

```
#: gnucash/gtkbuilder/dialog-sx.glade:724
msgid "Set 'Re_view Created Transactions' as default"
msgstr "Postavi „Pregledaj stvorene transakcije” kao standardno"

```
I have no idea how to search for msgformat's lineno. in weblate.
> Weblate doesn't seem to inform about such a problem.

I found no way to enable the accellerator check. Perhaps we should ask the weblate team.

**Comment by milotype** [comment]
> ```
> #: gnucash/gtkbuilder/dialog-sx.glade:724
> msgid "Set 'Re_view Created Transactions' as default"
> msgstr "Postavi „Pregledaj stvorene transakcije” kao standardno"
> ```

Thank you. Done!

> I found no way to enable the accellerator check. Perhaps we should ask the weblate team.

Yes, do not hesitate ... I've talked with Michal Čihař (the owner of Weblate) several times while I was translating Weblate itself into Croatian ... he is quite quick in responding ...

**Comment by fellen** [comment]
> > Weblate doesn't seem to inform about such a problem.
> 
> I found no way to enable the accellerator check. Perhaps we should ask the weblate team.

in my local translate-toolkit pofilter 3.3.6 has a filter `accelerators    Checks whether accelerators are consistent between the two strings.`

**Comment by nijel** [comment]
See https://github.com/WeblateOrg/weblate/issues/5962 for related Weblate issue.

**Pull request merged**
