### PR TITLE
Bug 797725 - Untranslatable string "For Period Covering ~a to ~a"

### PR DESCRIPTION
**Pull request by christopherlam**
use `(gnc:format)` strings.

### CODE REVIEW

**Comment by fellen** [comment]
I wonder if we should create a report-msgs.scm or similar to collect such constructs.

**Comment by jralls** [comment]
It sets the report title so it's more boilerplate than message. That aside it doesn't really merit a separate file just for itself, but if there's a bunch of common generation funcs or fragments that get copied from one report to the next, extracting them all to a common file would be a Good Thing™.

**Comment by christopherlam** [comment]
The named arg syntax can be changed from `${var}` to `{var}` to match c++ fmt if desired.

**Comment by jralls** [comment]
> The named arg syntax can be changed from ${var} to {var} to match c++ fmt if desired.

 I don't think that's terribly important and requiring `${` as an intro makes it much less likely that you'd ever need to provide an escape like {fmt}'s provision of `{{` and `}}` to insert curly brace literals into the format string.

**Comment by jralls** [comment]
@christopherlam why did you decide to move this to master? It's not a major change.

**Comment by christopherlam** [comment]
Can't remember much-- may be because of string freeze. I haven't changed
the strings generally because I hadn't received any feedback about it.

**Comment by jralls** [comment]
There wasn't any string freeze on 18 August when you applied the `master` label nor on 6 Sept when you changed the branch. The latest version is fine and can go into maint immediately after the release.

**Comment by christopherlam** [comment]
Forgot about this PR. So should we apply this for final release, or into master?

**Comment by christopherlam** [comment]
merged in maint, 580efe091c

**Pull request closed without merging**
