### PR TITLE
Fix build on 32 bit arches

### PR DESCRIPTION
**Pull request by david-geiger**

### CODE REVIEW

**Comment by david-geiger** [comment]
Mageia Cauldron + GCC14:

On 32bit arches without this patch we got this following build issue:

`In file included from /home/iurt/rpmbuild/BUILD/gnucash-5.6/libgnucash/engine/qof.h:74,
                 from /home/iurt/rpmbuild/BUILD/gnucash-5.6/libgnucash/engine/gnc-engine.h:41,
                 from /home/iurt/rpmbuild/BUILD/gnucash-5.6/libgnucash/engine/gnc-commodity.h:55,
                 from /home/iurt/rpmbuild/BUILD/gnucash-5.6/libgnucash/engine/Transaction.h:93,
                 from /home/iurt/rpmbuild/BUILD/gnucash-5.6/gnucash/import-export/import-main-matcher.h:40,
                 from /home/iurt/rpmbuild/BUILD/gnucash-5.6/gnucash/import-export/import-main-matcher.cpp:45:
/home/iurt/rpmbuild/BUILD/gnucash-5.6/gnucash/import-export/import-main-matcher.cpp: In function 'void gnc_gen_trans_assign_transfer_account_to_selection_cb(GtkMenuItem*, GNCImportMainMatcher*)':
/home/iurt/rpmbuild/BUILD/gnucash-5.6/libgnucash/engine/qoflog.h:267:16: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'std::vector<std::unique_ptr<_GtkTreeRowReference, TreeRowRefDestructor> >::size_type' {aka 'unsigned int'} [-Werror=format=]
  267 |                "[%s] " format, PRETTY_FUNC_NAME , ## args);     \
/home/iurt/rpmbuild/BUILD/gnucash-5.6/gnucash/import-export/import-main-matcher.cpp:850:5: note: in expansion of macro 'DEBUG'
  850 |     DEBUG("Rows in selection = %ld", selected_refs.size());
      |     ^~~~~
/home/iurt/rpmbuild/BUILD/gnucash-5.6/gnucash/import-export/import-main-matcher.cpp:850:34: note: format string is defined here
  850 |     DEBUG("Rows in selection = %ld", selected_refs.size());
      |                                ~~^
      |                                  |
      |                                  long int
      |                                %d
cc1plus: all warnings being treated as errors`

**Comment by christopherlam** [comment]
Does `%zu` work?

**Comment by jralls** [comment]
> Does %zu work?

See #1904

**Comment by christopherlam** [comment]
Ok. Would it be an idea to including 32-bit builds on CI?

**Comment by jralls** [comment]
> Ok. Would it be an idea to including 32-bit builds on CI?

We do sort of with the Windows nightlies, but apparently MSYS2's version of gcc didn't flag up this parameter mismatch.

**Comment by madpilot78** [comment]
> > Does %zu work?
> 
> See #1904

I have tested my patch with %zu on FreeBSD, and it works fine there for compiling. I am not sure how to get that debug code to actually execute.

BTW I'm using my patch in the FreeBSD ports tree at present: https://github.com/freebsd/freebsd-ports/commit/3abcd80304e0e6536bd8208718d7844ad98c7a90

**Comment by jralls** [comment]
To execute the debug statement start GnuCash with --log gnc.import.main-matcher=debug and import a file.

`%zu` is more correct than casting the `size_t` to `long int` so we'll go with #1904.

**Pull request closed without merging**
