### PR TITLE
Allow Bayesian matching accounts to be found by Guid

### PR DESCRIPTION
**Pull request by Bob-IT**
Allow matching accounts to be found also by their Guid which will be used in newer versions. The default behaviour is still to create new entries under the account fullname.

### CODE REVIEW

**Comment by Bob-IT** [comment]
Not Required

**Comment by gjanssens** [comment]
Bob, I don't agree we don't need this.

Remember with new features:
1. master should be able to read-write
2. maint should be able to read (to the extent possible).

With the code you proposed for maint here, you are very close to the second goal. Dropping it would mean no 2.6.x version can be used in parallel with 2.8.x if users us the bayes importer. That would be a pity.

This PR will make sure gnucash 2.6.x never **introduces** any guid based bayes data, but will use it if already there. Only 2.8.x can ever **introduce** the guid based data. That's a close enough match to the base feature conditions to be acceptable.

There are a few minor kinks to iron out still though.

A quick recap of what we want to achieve compatibility wise:
- 2.8.x: will only work with guids internally, and will convert any name based data to guid at file opening
- 2.6.12 and more recent: understands guids, but will still default to name based data
- 2.6.11 and older: only understands name based data, and should be prevented from opening a data file that holds guids.
Considering 2.8.x will be released in 2018 (almost 2 years from now) this means most people will have upgraded to 2.6.12 or more recent and hitting the 3rd condition will be rare (which is what we want), but can still happen.

To prevent 2.6.11 and older from opening a data file with guid based bayesian data, you have introduced the feature code. However as you have currently only introduced it in master, 2.6.12+ won't know it either and will also refuse to open such file. To fix this, introduce the feature code in 2.6.12 already, but don't ever set it in 2.6.x. Only set it in master whenever you actually do write a guid based bayesian key (as explained in detail in the comment on your master PR).

Next, is the issue of working on the same data file in both 2.6.12+ and 2.8.x. Your current code in master will only run the conversion once, based on the absence of a kvp. However if a user imports new data in 2.6.12+ that may introduce new name based kvp's and hence to conversion should run again. The easiest way to achieve this is to delete the run_once kvp in 2.6.12+ each time a name based bayesian kvp gets added. A subsequent file load in 2.8.x will trigger the conversion again.

**Comment by Bob-IT** [comment]
Add feature to prevent earlier versions opening data file and also reset the run once kvp flag for the Bayesian conversion procedure.

**Comment by gjanssens** [comment]
Pushed to maint after a rebase and a few commit tweaks.

Thanks a lot!

**Pull request closed without merging**
