### PR TITLE
Change Baysian matching accounts to be saved by Guid

### PR DESCRIPTION
**Pull request by Bob-IT**
This pull request changes the way Bayesian matched accounts are saved in KVP, instead of using the account full name as part of the path it uses the account Guid.
As part of this there is a function to change all existing entries to that of Guids which is run when a file is opened. I have also added a KVP entry to the book so I can test for this and allow the conversion to be run once.
Not sure if this is correct but seems to work.

### CODE REVIEW

**Comment by gjanssens** [comment]
Robert, thanks for your work. I have added a number inline comments (see above).

The trickiest part is - as always - getting everything to work as smoothly as possible in two major releases (2.8.x and 2.6.x).

The basic principle is as John explained that master is capable of read-write, while current maint should only be able to read and parse the new data.

There is one more security measure we may have to take. Current maint will become 2.6.12. Any version before that will not be aware of the guid based bayes data at all. So if a user opens a data file with such data in say 2.6.11 and tries to import, it will appear as if the importers aren't trained at all.

We should decide which experience we want to give the users in this case and I see two options:

1. We just consider this to be acceptable and tell users to upgrade to at least 2.6.12 if they ask about it. Depending on how frequently the importers are used, this can quickly become a FAQ.
2. We prevent older gnucash versions from opening a data file that contains guid based bayesian data. (Older being anything older than 2.6.12).

I'm tempted to go for option 2. We have a feature mechanism in place for just such changes. I'm using it to prevent older gnucash versions from opening a data file if it contains credit notes for example.

And final comment/request: you are making changes in the engine code, but I don't see any unit tests together with it. I think such tests are very important to guarantee to quality of our code, particularly in the engine. Are you willing to write a test suite for the bayesian matching or at least make a start of one that covers your code ?

**Comment by Bob-IT** [comment]
I have added some more commits that fix some issues and take on your recommendations. When I started looking at the Bayesian changes, John asked if I could change the account Imap functions to c++ which I said I would have a go as a learning task so I can add unit tests as part of that.

**Comment by Bob-IT** [comment]
This has been more complicated than I first thought, moved feature setting to kvp use and added some functions to reduce duplication.

**Comment by gjanssens** [comment]
Thanks for the update. The logic is in place now and works correctly.

On rereading the result so far I still have a few smaller remarks to improve clarity in the code.

1. For the one-time conversion you have introduced an intermediate function called "get_account_imap_info". However that function does much more than just getting the account's imap info. It will start the conversion for for the account based on the imap info. To make future code studying easier, it would be better to give it a name that expresses that slightly better like for example "convert_imap_account".

2. You are passing the root account as a function parameter to get_account_imap_info, while that function is not using it directly. It only passes it on to convert_imap_entry. However convert_imap_entry can quite easily determine the root account itself via for example calling "gnc_account_get_root" on the account in the imap_entry. So don't pass a parameter you don't really need.

3. I'm happy you split of the "update_imap_entry" from "convert_imap_entry" as it makes both functions much easier to understand. I would like to see here as well though that the name conveys better it's about **conversion**. I know now because I am looking at it closely. However someone looking at the whole in a few years time won't have the same context as I do now. And finding and function called update_imap_entry may suggest it should be used to change the count. Only closer inspection would reveal otherwise. Conceptually you have split the code based on function: the first part checks whether the conversion is needed, the second part does the actual conversion when needed. So one proposal to reflect this in the function names (which you could compare to chapter titles in a book) and behaviour would be to
* change "convert_imap_entry" into "look_for_old_mapping" (similar to your "look_for_old_separator_descendants") and have it return a pointer to the map account in case conversion is needed (or NULL of no conversion is required)
* then rename update_imap_entry to convert_imap_entry and call it from get_account_imap_info (or whatever you eventually choose to call it) if look_for_old_mapping returned a account to convert.

4. Just a thought for optimisation: considering full_name is not const declared in look_for_old_separator_descendants, I'm not sure the g_strdup and subsequent g_free are really required. I would think you could simply point converted_name at full_name and work with that. AIUI constness it should even be ok to work on full_name directly.

That's it. A final cleanup round of your code so you're almost there...

**Comment by gjanssens** [comment]
Oh, one more general request: please make sure the first line of your commit message is a full sentence. Several tools take the first line as some kind of a title for the commit. If the first line ends somewhere halfway the sentence it makes it needlessly difficult to get what the commit is doing.

As an example from your commits on this branch:
"Improve old separator recognition by looking for"
won't help much where
"Improve old separator recognition by looking for the longest top level entry that matches the prefix"
does explain it completely. This particular example gets a little long so maybe the title can be shortenend and more details given in the body of the commit message. But I think you get the idea.

If the tool you are using to commit your work forces these line breaks on you, please figure out how to configure your tool, or train yourself in writing very concise titles with a more elaborate explanation starting on the next line.

**Comment by Bob-IT** [comment]
Made some more changes as requested and hopefully improved on the commit messages, did not notice that they were a problem, sorry.

**Comment by gjanssens** [comment]
Thanks for the quick update Bob. I **think** a small logic bug got introduced in your last commit (see previous comment). Can you confirm or explain why I may be wrong ? Other than that it looks fine and ready to merge.

You may have noticed github is complaining about merge conflicts with your most recent pull request. That's because I have already merged your changes on the maint branch into master. The commit that introduces the feature flag is conflicting now (due to me rewording the flag). If you feel like it you could rebase and resolve the conflict. If not don't worry, I know where the conflict is and can resolve it when I do the merge.

**Comment by Bob-IT** [comment]
Can I leave it to you to resolve the conflict but could you explain what steps you took to resolve it please.

**Comment by gjanssens** [comment]
Sure. Here it is:

1. I started by pulling your branch into my local repository:
    git checkout master
    git checkout -b bobit
    git pull https://github.com/Bob-IT/gnucash bayes2

2. At this point I have your work in my repository, under a branch named bobit (I could have used bayes2 as well, but didn't for no particular reason). Attempting to merge this branch will result in merge conflicts because maint already introduces the feature flag and I chose to rename/reword it. Should I not have done that, git would have discovered the identical changes in the two branches and just skip it. But the changes are there, so now we need some manual intervention to fix this. There are several ways to do this. One would be to run the merge anyway, go through al the conflict markers in the code, manually edit these spots to keep the correct solution and commit the merge. I didn't want to do that because I prefer to rebase your work instead, keeping the master branch as linear as possible. So instead I played a few rebase acts to remove the conflicting code from your branch before finally rebasing on master. This involves much more steps, but also results is a final commit history that's much easier to read. In more detail:

3. Start a new temporary branch (bobit1) on the commit introducing the merge conflict ("Add feature flag..."). I did this via the graphical tool gitk as that's easier than typing the commands. At this point you can consider branch bobit to branch off of bobit1.

4. Next I reset bobit1 to the previous commit ("Use GncImapInfo instead...")
    git reset HEAD^

5. Without any command line switches the reset command will default to a "mixed" reset. That means that all changes that were in the commit(s) to reset will now appear in your working directory as uncommitted changes. So the changes are not lost, just at your fingertips to modify. The only thing I want to do at this point is separating the conflicting changes from the non-conflicting ones. That means I'll commit the changes to gnc-features.* independently from the changes to Account.c:
    git add src/core-utils/gnc-features.*
    git commit --author "<your identification>" -m "Changes to drop later on"
    git add -u
    git commit --author "<your identification>" -m "Add feature flag..."

6. Due to the above actions the two branches bobit (with your unchanged original work) and bobit1 will have diverged. bobit1 now has two commits that are no longer on branch bobit. However because these two commits result in exactly the same code changes as the original "Add feature flag..." commit we can easily align them again with a rebase. git will detect that changes are already committed to bobit1 and will not apply them again during the rebase. Very important to remember here is that this only works when **identical** changes are in both branches. Change one character and you will have a conflict to resolve during rebase:
    git rebase bobit1 bobit

7. So at this point bobit is a child branch of bobit1 again (that is all commits in bobit1 are also in bobit). After this rebase, note that the bobit branch will be checked out. I'll drop the bobit1 branch for now. It will only lead to confusion in what follows.
    git branch -d bobit1 (or do it via gitk)
  
8. Next step is to drop the commit causing the conflict. I can do that in this situation because I want to keep the version that was already in master via the earlier merge of my changes from maint. The way to do that is running an interactive rebase. That requires a commit to start from though. To make it easy on myself, I used gitk again to create a new temporary branch "tmp" on the commit right before the commit to delete. That should still be "Use GncImapInfo instead...".  Be sure bobit is still checked out at this point and then run
    git rebase -i tmp

8. git will present you with a list of commits between the tmp branch and your bobit branch in a text editor. Delete the line for the commit "Changes to drop later on", save and close. git will reapply all changes starting from tmp, skipping the commit we wanted to delete. In the end you will now have an updated bobit branch.

9. With the conflicting commit removed, we are now ready to do the final rebase on master (in order to get the linear history I had in mind). First drop the tmp branch (to avoid confusion):
    git branch -d tmp

10. Next rebase:
    git rebase master bobit

11. If all went well, this rebase should now work without any conflicts. Trying to build though you will find it will fail to build Account.c, due to an unknown symbol GNC_FEATURE_CHANGE_BAYESIAN. That's because in maint I also changed this symbol to GNC_FEATURE_GUID_BAYESIAN as the latter is more detailed. And this change was already propagated to master before rebasing your branch and your commits are still referring to the old name. That has to get fixed as well. I could simply add a follow-up commit after finishing the import. However that would mean none of your individual commit would build, and we'd lose the bisect ability should we ever have to determine whether one of your commits introduces a bug. So instead I'll fix the changes in place. Again that takes a few steps. The first one is easy:

12. fix the current code by replacing the old symbol with the new one and commit it as a new commit. There is only one reference in the current code to the old symbol so this is a pretty trivial change. The symbol is currently still used in function "change_imap_entry", and it was introduced in commit "Change some functions to reduce code duplication". So while the code now builds, the older ones still don't (for a potential bisect). As the last change was introduced in "Change some functions..." and this fix is trivial, we can easily move the fixup higher up the history until right after the "Change some functions..." commit and then even merge it completely into that commit using an interactive rebase:
    git rebase -i master

13. In the list of commits that will be presented, move the commit line for the fixup (the last one) up until right after the "Change some functions..." commit and then change the work "pick" to "fixup" on the fixup commit's line. Save and close the editor. This should now rewrite the bobit branch once more. The fixup commit will be gone from the history, however the "Change some functions..." commit now inserts the correct symbol. This means we have 4 more commits that will build properly during a bisect.

14. At this point there is one more commit left that won't build: the "Add feature flag..." commit. That commit still uses the old symbol. This one is slightly more difficult to fix because the lines it introduces with the old symbol are removed again in the next commit, so the only way to alter them is to go back into history. Another temporary branch to the rescue! Using gitk I once again create a bobit1 branch on the "Add feature flag..." commit and check it out.

15. In this commit as well there's only one line referencing the old symbol. So again, fix the line and commit the change as a fixup. And this is the point to pay attention ! You may be tempted to do just as before and merge the fixup with the original commit and be done with it. However at some point we will want to add all the more recent commits on branch bobit on top of this one again to have a complete (and linear) history. Remember I said earlier a rebase will only work without conflicts if your new base is identical to your original base (a slight simplification but a safe assumption). At this point our new base (the code as represented by the bobit1 branch) however is no longer identical. It has one line that's different. And that's critical, because the next commit on bobit ("Change some functions...") will try to remove that very line (and replace it with other code in another spot). Because the line to remove is no longer identical, the rebase will fail. To get around this we need to make a sidestep and temporarily make our base identical again. To do so I'll do something rather unituitive: I'll **revert** the fixup commit. Note particularly I say **revert**, not **reset**. A revert action **adds** a commit undoing the changes where a reset action **removes** commits from a branch:
    git revert

16. The net result is that the code pointed to by bobit1 is again identical to the old base inside bobit, but we have two extra commits to play with:  the fixup and the fixup reverted. And so we can align bobit1 and bobit again with a simple rebase:
    git rebase bobit1 bobit

17. That should make bobit a child branch of bobit1 again, now also holding the two additional commits. bobit1 is no longer needed, so let's drop it once more:
    git branch -d bobit1

18. We're not really interested in these fixup commits on their own, we just want the code at each commit to build, so let's run a final cleanup round with another interactive rebase:
    git rebase -i master

19. In the list of changes we want to merge the fixup commit with the "Add feature flag..." commit and the reverted fixup with the "Change  some functions..." commit. For the first, we can simply change "pick" to "fixup" on the fixup commit's line.

20. We can't do that for the reverted fixup though because a fixup always merges with the previous commit (the fixup itself in this case), and due to the "fixup" action we already set that also means the reverted fixup would end up being merged with the "Add feature flag..." commit, effectively undoing everything we did so far. We could use the fixup action on the "Change some functions..." commit instead, in order to merge it with the reverted fixup commit. This would work and is almost what we want. The drawback is that the fixup action drops the commit message of the commit marked with the fixup action. In our case that means the "Change some functions..." message would be lost in favor of some meaningless "Revert commit..." message. To deal with that, we choose the "squash" action on "Change some functions..." instead. This will ask you for a commit message while merging the two commits - once the rebase is running that is. So save the list of commits and close the editor to get the rebase running. At some point you will be asked for a new commit message. The proposed commit message will be a merge of the separate commit messages. At this point you can remove the "Revert commit..." part of the proposed commit message and keep only the "Change some functions..." part. 

21. End result: all commits build (good for bisect) and we have a nice linear history.

This final history got pushed upstream now. Thanks for your work!

I hope my explanations will be useful.

**Comment by gjanssens** [comment]
For completeness let me add that all of the above could also be performed in one single rebase action and resolving conflicts as they pop up. That would have required the alertness to change the old GNC_FEATURE_CHANGE_BAYESIAN symbol at the same time as resolving the conflict while rebase attempts to recommit the "Add feature flag..." commit. If forgotten the steps as outlined starting from 12 should be performed anyway.

I use both options, depending on the complexity of the conflicts. In my experience it's sometimes tricky to fix conflicts as indicated  by conflict markers in the code and that needs a trained eye (and understanding of the changes). The detour of the long process above has the advantage of always having temporary branches available to fall back to whenever one step fails and splitting the conflict resolution in many smaller steps. So it's easier to go back one step if something goes wrong, or work iteratively. A single rebase is usually an all or nothing thing. It worked or you have to start all over again (especially true if one single commit has multiple conflicts to resolve). Feel free to experiment with both methods though. The one step rebase with conflict resolution is a very powerful method as well.

And lastly my focus on linear history may be completely misplaced (a sign of working too long with svn perhaps). And a merge with conflict resolution would have been just as fine. However also here conflict resolution is all or nothing. There is sometimes an advantage in being able to make small iterative changes.

**Comment by Bob-IT** [comment]
Thank you for the above text, will take several reads to make sure I
understand.

I have just pushed some changes to my bayes2 branch to update the existing
unit tests for import_map to reflect the changes to guid, can you still
pull them ?
Should I request a new pull on the branch or start another one with the
changes ?

Bob

**Comment by gjanssens** [comment]
On Sunday 13 March 2016 07:01:03 Bob-IT wrote:
> Thank you for the above text, will take several reads to make sure I
> understand.
> 
> I have just pushed some changes to my bayes2 branch to update the
> existing unit tests for import_map to reflect the changes to guid,
> can you still pull them ?
> Should I request a new pull on the branch or start another one with
> the changes ?
> 
> Bob

To simplify things it would probably be easier if you start a new branch  from the 
current master and cherry pick your most recent commits to that branch. If not we will 
continue to run into the merge conflict because your own bayes2 branch wasn't really 
merged. Only my local copy of it is.

Regards,

Geert

**Pull request closed without merging**
