### PR TITLE
Add a new line in About dialog. Update of all po. files.

### PR DESCRIPTION
**Pull request by DiMan**
**Add new line in About dialog:** 

#: ../src/gnome-utils/gnc-main-window.c:4370
msgid ""
"The GnuCash personal finance manager.**\n**"
"The GNU way to manage your money!"

**and update all .po files:**
* Update for msgid & msgstr: 
`as.po  bg.po  brx.po ca.po cs.po da.po de.po doi.po el.po en_GB.po es.po` 
`es_NI.po eu.po fi.po fr.po gu.po hi.po hu.po it.po kn.po ko.po kok.po `
`kok@latin.po ks.po lt.po lv.po mai.po mni.po mni@bengali.po mr.po `
`nb.po ne.po nl.po pl.po pt.po pt_BR.po ro.po` 
`ru.po sk.po sr.po sv.po ta.po tr.po uk.po vi.po `
* Update only for msgid, because originally no translation:
`az.po fa.po he.po rw.po   `
* Update only for msgid, because the language syntax is difficult or sentences are very short
`ar.po ja.po te.po ur.po zh_CN.po zh_TW.po `

**Additional changes for de.po file (German):**
1) "**GnuCash**: Ihr privater Finanzmanager." => "Ihr privater Finanzmanager **GnuCash**. "
2) msgstr `<b>_Kontofarbe</b>` => msgstr `<b>Kontofarbe</b>`

### CODE REVIEW

**Comment by jralls** [comment]
No, thank you. In spite of the name and the claims of the FSF GnuCash is not a GNU project.

**Comment by DiMan** [comment]
Hello jralls,

I sent this PR to improve displaying text in the about dialog:  please see comments of PR #211 for more information. Did I do something wrong? 

Thanks in advance!
DiMang

**Comment by gjanssens** [comment]
Op woensdag 18 oktober 2017 05:48:32 CEST schreef John Ralls:
> No, thank you. In spite of the name and the claims of the FSF GnuCash is not
> a GNU project.

I agree with your statement about GnuCash not being a GNU project. However I 
don't think it's relevant in this PR. @DiMan didn't *add* the GNU tagline, he 
only inserted a newline *character* to split this long text in two lines.

On the other hand since you pointed it out we could take this opportunity to 
fix the confusion while we're looking at it.
I see two options:
- we can simply choose to remove the GNU promo line altogether, no newline 
character needed any more.
- we could also just change "GNU" into "open source".

I'm fine with both options.

**Comment by jralls** [comment]
Ah, sorry, you're right. 

Considering the recent discussion on the user list about making GnuCash work like Quicken I think we should get rid of "manage your money" as well as "GNU".  I'd like something like "The Free/Libre Personal Accounting Solution". This PR is on maint, though, and it's not worth breaking the translation string so let's do that in a separate commit on unstable.

**Comment by gjanssens** [comment]
Ok on both your tag line proposal (I like it mentions both Free and Libre) and for doing it on unstable.

**Comment by DiMan** [comment]
thanks for your feedback on this point. If the description will changed in the new GnuCash version, it is really not necessary to add newline. Please ignore this PR.

**Comment by gjanssens** [comment]
The dialog has been reworked, so I'm closing this PR. Thanks for bringing this up in the first place.

**Pull request closed without merging**
