### PR TITLE
Hebrew Translation Update for ver 3.11

### PR DESCRIPTION
**Pull request by avma**

### CODE REVIEW

**Comment by jralls** [comment]
Sorry, you did the wrong branch. 3.11 was the last release of the 3.x stable series. Please translate 4.0 instead. You might want to hold off for a few days, though, as we'll be merging master onto maint for further 4.x development.

**Comment by avma** [comment]
will do...

**Comment by fellen** [comment]
@avma you create usually nice 100% translations, but submit them a few days to late for inclusion.
We release usually at the **last weekend of the quarter**. That means you should create  your PR _before saturday_. See https://wiki.gnucash.org/wiki/Release_Schedule for changes. 

It would really nice to have them in the corresponding release.

**Comment by jralls** [comment]
But note that 4.0 being a major release we'll be doing the initial bug fix release, 4.1, on 28 July. It would be great if you can manage to do the PR by the 26th.

**Comment by jralls** [comment]
Replaced with #757.

**Pull request closed without merging**
