### PR TITLE
Bug 798211 - Equity statement double calculates unrealized gain

### PR DESCRIPTION
**Pull request by xuhdev**
Fix Bug 798211 <https://bugs.gnucash.org/show_bug.cgi?id=798211>

### CODE REVIEW

**Comment by jralls** [comment]
You need to change the match string in [test-equity-statement.scm](https://github.com/Gnucash/gnucash/blob/maint/gnucash/report/reports/standard/test/test-equity-statement.scm#L102) to match your change here.

Please change the commit summary to be exactly the same as the bug summary, i.e. "Bug 798211 - Equity statement double calculates unrealized gain".

We won't be able to merge this until after the string freeze lifts Monday.

@christopherlam Are you OK with the change?

**Comment by xuhdev** [comment]
Done!

**Comment by christopherlam** [comment]
Looks good!

**Review by christopherlam — APPROVED** [review]

**Comment by xuhdev** [comment]
Can we merge this if this is all good? :)

**Comment by jralls** [comment]
Like I said, not till Monday because of string freeze.

**Comment by christopherlam** [comment]
Thanks!

**Pull request merged**
