### PR TITLE
[Master] Glade changes

### PR DESCRIPTION
**Pull request by Bob-IT**
I created these commits originally for maint but it was decided that they were more appropriate for master. Mainly they are changes to alignment, spacing and with some changes from gtk boxes to use gtk grids. There are also some text changes that will probably cause translation changes.

If no one has any concerns I will push these at the weekend.

### CODE REVIEW

**Comment by fellen** [comment]
Why do you think, it should go to master. I see mostly fixes of our 3.x GUI?
As a user I would prefer to have the fixes ASAP.
Or are you concerned of our translators? I prefer to review 100 messages/release over 1000/branch.

Something different would be a new sequence of the dialogs.

**Comment by Bob-IT** [comment]
At the time it was thought that there were too many strings changed that may need a new translation and the change of GtkBox widgets to GtkGrid was too much of a change for maint.

**Comment by fellen** [comment]
Please put the string changes in maint, else I could change them in another way.
While I review translations, I often mark "bad strings" and fix them.

**Comment by Bob-IT** [comment]
Closing as superseded by PR614

**Pull request closed without merging**
