### PR TITLE
test_gnc_setlocale: add missing whitespaces to diagnostic message

### PR DESCRIPTION
**Pull request by d-dittmann**

### CODE REVIEW

**Comment by jsoref** [comment]
https://github.com/Gnucash/gnucash/blob/bccd9c707e41925b523881e5b0e918c77b4aed11/libgnucash/engine/test/utest-Budget.c#L437 seems to indicate a preference for trailing whitespace over leading whitespace

**Comment by fellen** [comment]
> https://github.com/Gnucash/gnucash/blob/bccd9c707e41925b523881e5b0e918c77b4aed11/libgnucash/engine/test/utest-Budget.c#L437
> seems to indicate a preference for trailing whitespace over leading whitespace

I am not sure. In .po files trailing spaces are standard as they are produced by gettext. But in the sources, I believe the leading space is more common.

**Comment by d-dittmann** [comment]
In source code, there are matches for both.
But it seems to be a bit more matches for leading spaces.

**Comment by jsoref** [comment]
Sorry about the misleading advice.

**Comment by d-dittmann** [comment]
I changed back to first version using leading whitespaces.
Please merge to maint.
Thanks.

**Comment by d-dittmann** [comment]
merged into maint
see: c9998a8ad80b20601d238f1ad01b033045968b55
@jralls: Thanks, Daniel

**Pull request closed without merging**
