### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
Thanks!

@ltai0001 I get a few errors reported:
```
msgfmt -c --check-accelerators="_" --statistics po/ar.po 
po/ar.po:3481: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3489: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3516: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3524: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3532: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3557: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3585: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3602: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3606: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3639: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3781: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3790: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3799: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3809: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3843: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3851: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3860: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3868: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3905: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3913: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3930: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:3966: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4008: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4019: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4029: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4039: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4049: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4059: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4128: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4145: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4157: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4181: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4193: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4203: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4215: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4227: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4240: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4404: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4544: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4596: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:4604: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5111: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5119: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5127: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5147: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5163: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5253: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5268: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5280: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5285: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5290: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5295: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5302: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5364: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5396: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5416: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5431: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5436: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5440: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5452: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5483: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5511: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5553: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5565: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5574: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5584: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5594: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5606: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5844: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:5849: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:6067: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:6226: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:6238: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:6303: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:6536: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:6833: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:6837: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:6981: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:6989: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:7473: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:7626: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:7644: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8108: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8112: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8116: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8120: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8241: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8245: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8647: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8677: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8687: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8796: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8808: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8824: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8832: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8848: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8864: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8872: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8888: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8896: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8904: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8912: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8928: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:8936: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:9007: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:9217: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:9222: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:9227: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:9232: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:9305: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:9324: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:9354: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:13131: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:13151: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:13164: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:13168: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:13174: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:13180: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:13195: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:13654: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14098: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14217: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14495: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14510: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14514: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14548: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14552: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14608: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14682: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14726: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14738: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14751: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14755: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14768: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14839: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14844: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14885: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14894: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14912: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14954: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14962: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14975: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:14998: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15023: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15040: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15077: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15113: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15442: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15446: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15450: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15477: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15490: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15494: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:15503: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16340: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16344: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16348: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16374: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16378: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16386: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16390: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16434: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16442: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16612: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16622: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16640: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16648: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16660: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16676: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16693: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16751: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16756: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16769: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16816: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16824: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16847: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16855: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16880: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16896: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16904: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16912: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16920: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:16943: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17054: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17059: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17064: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17069: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17074: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17117: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17125: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17133: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17141: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17156: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17164: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17176: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17184: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17196: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17226: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17236: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17244: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17289: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17293: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17297: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17309: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17321: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17343: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17348: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17353: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17358: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17374: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17400: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17408: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17416: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17420: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17445: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17516: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17655: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17752: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17764: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17768: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17772: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17784: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17825: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17833: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17841: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17845: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:17849: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18042: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18077: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18081: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18171: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18175: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18187: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18195: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18199: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18207: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18289: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:18998: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19007: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19013: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19018: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19028: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19034: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19064: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19080: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19089: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19097: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19113: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19125: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19194: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19198: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19251: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19378: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19488: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19505: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:19737: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:20232: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:20244: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:20253: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:20317: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:20357: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:20822: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:20830: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:20945: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:20950: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:21365: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:21373: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:21709: msgstr lacks the keyboard accelerator mark '_'
po/ar.po:21987: msgstr lacks the keyboard accelerator mark '_'
msgfmt: found 269 fatal errors
3972 translated messages, 936 fuzzy translations, 482 untranslated messages.

```
Can you read https://wiki.gnucash.org/wiki/Translation#Special_characters_and_other_tips and fix them?

**Comment by ltai0001** [comment]
How do I find where the error is? Meaning how do I find the string in weblate? Newbie here

**Comment by fellen** [comment]
> How do I find where the error is? Meaning how do I find the string in weblate? Newbie here

One possibility:
https://hosted.weblate.org/projects/gnucash/gnucash/ar/
File->Download translation: gnucash-gnucash-ar.po
In the file goto the line number mentioned in the errormessage to see which message was meant.
Search and edit the message in weblate.

Perhaps it is also possible to jump to the message directly in Weblate, but I didn't find it, but you can search for  ` source:_`

**Comment by ltai0001** [comment]
ok I found the errors - these are all missing the "_" underscore character in the Arabic translation. Weird that Weblate doesn't indicate that as an error

**Comment by fellen** [comment]
See https://github.com/WeblateOrg/weblate/issues/5962

**Pull request merged**
