### PR TITLE
Updated pt.po

### PR DESCRIPTION
**Pull request by pmraps**
Sorry for the inconvenience.

### CODE REVIEW

**Comment by fellen** [comment]
NP. ;-)

Because there was this strange merge commit in your PR, I cherrypicked your real commit, added the statistics to the commit message and pushed it as commit a777666.

You could have avoided the merge commit by using `git rebase` instead of `git merge`. As long as you are working locally rebase is the better choice.

Thanks!

**Comment by gjanssens** [comment]
Thanks for the update. @fellen apparently did handle it before I finished writing my comments. I agree with how he handled it.

I'll focus instead on the the merge commit that should not have been in there. I suspect you got into this situation because
1. You did your work on the maint branch instead of a temporary feature branch
2. @fellen committed msgmerge on top of your PR
3. You used github to update your maint branch

Unfortunately this won't work. Github is not capable of doing a proper pull from a remote repo. It insists on adding a merge commit when trying to do so. Even the more hidden option of "Rebase and merge" messes with the original history.

As @fellen handled merging the PR properly, what is left to do is cleaning up your repos to realign it with the main repo.

I will assume
1. you have set up your fork and local clone on your PC following [our wiki instructions](https://wiki.gnucash.org/wiki/Setup_for_Pull_Requests) and in particular that you are using "**upstream**" and "**origin**" for the remote repositories as explained on that page. If not, adjust the instructions below accordingly.
1. you have access to a shell for running commands (bash, sh, or msys on windows).
1. all the work on your maint branch has been added into our upstream repo.

So with all that, open a shell and execute the following commands, replacing anything in <> with the appropriate values:

```
cd <path-to-your-gnucash-repo-clone>
git checkout maint
git fetch --all
git reset --hard upstream maint
git push -f origin maint
```

Please let me know how it goes or if there are issues.

For future changes I do encourage you to follow our workflow using working (or feature) branches. That will make it much easier to keep your repos aligned with the upstream one.

And finally: congratulations, you have completed the Portuguese translation! I'm very impressed and happy with this.

**Comment by pmraps** [comment]
Thank you both for your trouble and comments. But I don't understand much of this.
I did a fork of gnucash repos (website, docs and ui) translated and made the pr. This latter (ui), after @fellen's comment, I made something I saw online, which is "[compare, switching base, create pr, merge pr](https://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381)", more or less. All within github.
Locally, when I cannot git push because of errors, I just delete the folder, clone again and paste my files. Quite dumb of me, I know.
Usually, when the work is done, I delete the forks and, when needed, create new ones.
@gjanssens when I tried _git reset --hard upstream maint_ it says _revision or path not found...._
I don't think I'll ever understand git... :(
Again, thank you very much.

**Comment by christopherlam** [comment]
> _git reset --hard upstream maint_

just a @gjanssens typo -- `git reset --hard upstream/maint` should do the trick

**Comment by pmraps** [comment]
No, same result. But I'll try again. Since everything is complete and commited, I'll start over, by deleting the current fork and begin a new setup from scratch.
Thank you all.

**Comment by gjanssens** [comment]
Ah indeed a typo. Sorry about that.

@pmraps The fact the commands don't work probably mean you haven't set up your local repo as described in [Setup for Pull Requests](https://wiki.gnucash.org/wiki/Setup_for_Pull_Requests), the link I added in my previous comment. No worries.

I sympathize with your struggle to grasp git. It is a powerful but very complex tool. Especially if you're not using it frequently.

I have now read the link to SO you followed. It's unfortunately exactly via that method you would get the unwanted merge commits. It's also mentioned in the comments of the accepted solution.

If you don't mind removing forks and clones each time, I'm fine with with you doing so as there would be no need for the more complex git commands directly. However in that case I would recommend to delete everything after each merged PR. So in this case a clean restart cycle in between the PR's would have avoided these merge oddities. It means more time is spent on the fresh starts, but it avoids confusion and saves time in the end.

**Comment by pmraps** [comment]
Ok, will delete and start over. That I can understand. Thanks a lot for all your trouble.

**Pull request closed without merging**
