### PR TITLE
[gnc-plugin-page-sx-list] enable popup for sx editor

### PR DESCRIPTION
**Pull request by christopherlam**
Enable right-click menu for SX editor.

### CODE REVIEW

**Comment by jralls** [comment]
Use-case?

**Comment by christopherlam** [comment]
Just to harmonise UI. A treeview begs to be R-clicked. And the toolbar seems far away.

**Comment by jralls** [comment]
OK for master, it's time to stabilize maint, it's less than 9 months to releasing 5.0.

**Comment by christopherlam** [comment]
into master.

**Pull request closed without merging**
