### PR TITLE
Reinstate budget editor summaries

### PR DESCRIPTION
**Pull request by christopherlam**
Reinstate Income/Expense/Transfer/Total, but rename to:

* Inflow from Income
* Outflow to Expense
* Outflow to Asset/Liability/Equity
* Remaining to budget

Behavior should be identical to previous release v3.7

### CODE REVIEW

**Comment by gregwalters** [comment]
Running GNC 3.900 Build ID git 2.6.17b-5264-gc77e19757+(2020-01-24)

If I'm running the wrong version for this test then I apologize!

I've opened an existing account file and an existing budget. I added $1000 to the "Income" bucket and see the change reflected in the Income total at the bottom of the screen. I don't see anything indicating the budget isn't balanced. I see the following fields:

Income
Expense
Assets
Liabilities
Equity

I also opened a new budget and added to the Income bucket. I see the Income total at the bottom of the screen but nothing indicating that the budget is unbalanced or there's unallocated income available.

**Comment by christopherlam** [comment]
Summary, Liabilities on a0dd4ec9b should be negated?

**Comment by fellen** [comment]
@gregwalters You have a very strange build ID starting with "git 2.6.17b".

I have currently (without this PR) Build ID: git 3.8b-110-g2adaf692b+(2020-01-29)

**Comment by gregwalters** [comment]
Running build ID git 2.6.17b-5038-gfb6451b8d+(2020-01-31) this time.

On the empty budget:

    Added $4k to Income, Remaining to Budget looks good
    Added $2k to Expense, Remaining to Budget looks good
    Added $1k to Liabilities, Remaining to Budget went up instead of down. Shows $3k, should be $1k.
    Removed the previous entry
    Added $1800 to Assets, Remaining to Budget looks good ($200), Outflow to A/E/L shows -$1,800 and I think that's backward.
    Added $200 to Liabilities, Remaining shows $400 but should actually be $0, Outflow to A/E/L shows -$2,000 instead of the $2,000 I think it should show.

**Comment by christopherlam** [comment]
Thanks try this one?

**Comment by gregwalters** [comment]
Running build ID git 2.6.17b-5039-gbdbb58375+(2020-02-01) this time.

Repeated the test procedure as previously described and all fields showed the expected values at all times.

Added $4k to Income, Remaining to Budget looks good
Added $2k to Expense, Remaining to Budget looks good
Added $1k to Liabilities, Remaining to Budget looks good ($1k)
Removed the previous entry
Added $1800 to Assets, Remaining to Budget looks good ($200), Outflow to A/E/L shows $1,800 as expected.
Added $200 to Liabilities, Remaining looks good ($0), Outflow to A/E/L shows $2,000 as expected.

Thumbs up!

**Comment by christopherlam** [comment]
Ok I think this will be safe to merge for more widespread testing.

**Pull request merged**
