### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [GnuCash/Program](https://hosted.weblate.org/projects/gnucash/gnucash/).

It also includes following components:

* [GnuCash/Glossary](https://hosted.weblate.org/projects/gnucash/glossary/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by fellen** [comment]
Thanks!

@SziaTomi Unrelated to your contribution I got a few warnings:
```
msgfmt -c --check-accelerators="_" --statistics po/hu.po 
po/hu.po:3594: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:3610: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:3629: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:3655: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:3685: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:3705: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:3718: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:3746: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:3754: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:3836: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:4117: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:4229: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:4306: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:4316: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:4547: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:4558: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:4704: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:4712: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5391: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5403: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5434: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5494: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5501: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5515: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5569: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5609: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5619: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5743: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5806: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:5986: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:6220: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:6355: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:6441: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:7045: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:7080: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:7097: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:7588: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:7859: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:7869: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:7895: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8223: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8235: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8302: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8689: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8739: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8836: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8840: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8844: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8848: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8852: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8860: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8900: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8917: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8941: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8949: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8965: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:8973: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:9251: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:9358: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:9734: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:10052: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:13106: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:13509: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:14258: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:14344: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:14545: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:14549: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:15015: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:15025: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:15045: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:15382: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:15395: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:15423: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:15440: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16273: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16619: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16636: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16695: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16700: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16790: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16798: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16824: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16848: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:16856: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17019: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17024: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17137: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17258: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17270: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17321: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17364: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17368: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17688: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17765: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17777: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17781: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17785: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17789: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17833: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:17851: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:18028: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:18032: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:18134: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:18244: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:18256: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:18261: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:19477: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:19494: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:19697: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:19725: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:20308: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:21588: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:23199: msgstr lacks the keyboard accelerator mark '_'
po/hu.po:23218: msgstr lacks the keyboard accelerator mark '_'
msgfmt: found 114 fatal errors
3018 translated messages, 1397 fuzzy translations, 975 untranslated messages.
```
Can you read https://wiki.gnucash.org/wiki/Translation#Special_characters_and_other_tips and try to fix them?

**Comment by SziaTomi** [comment]
Dear mr. Ellenberger.
Thank you for the letter. The link to wiki.gnucash.org will be useful to
me. I started the Hungarian translation of Gnucash only a few days ago and
I intend to do GnuCash Glossary for the first time. After that, I intend to
tackle the other elements of the localization as well. The task is big and
I have little free time to spend on it, so it will take a long time to
complete the translation.
When I am done with the translation, I will notify the project owner or the
developers. (I have done this for all my completed work and will continue
to do so in the future.)
Best regards, SziaTomi.

Frank H. Ellenberger ***@***.***> ezt írta (időpont: 2022.
jún. 20., H 22:27):

**Comment by fellen** [comment]
> Dear mr. Ellenberger.

I understand, but because of the release this weekend, you might consider to review the program component for easily fixable untranslated and fuzzy messages before.

**Comment by SziaTomi** [comment]
Dear mr. Ellenberger.
Unfortunately I just have so much time to correct these 114 errors. I can
do more for translation on weekends.
A question about hotkey. During the translation of Nicotine+ I saw that the
German language localization contributor translated _copy to
_kopieren. Nicotine+ was written in Python and GTK based.
My question is that:
The keyboard accelerator can be changed during localization?

Best regards, TomiSzia.

**Comment by fellen** [comment]
> The keyboard accelerator can be changed during localization?

No, AFAIK it depends on the platform. Others like KDE are using `&`.

**Pull request merged**
