### PR TITLE
Updated fi translation

### PR DESCRIPTION
**Pull request by harski**
Even though the translation file is nowhere near ready, I think my progress so far is significant enough that it should be included in the next release. Much of the main interface and functionality is now translated (1858 vs. 511 translated strings).

### CODE REVIEW

**Comment by gjanssens** [comment]
Thank you for your contribution. You have indeed made a significant improvement to the Finnish translation! We plan to include your work in this weekend's release.
There is one issue with your PR though. As explained on [our translation wiki page](http://wiki.gnucash.org/wiki/Translation#Translating_the_Program), all translations should happen on the maint branch while you are working on the master branch. Do you know how to rebase your work to maint ? If so it would be helpful if you did so and submitted a new PR.

**Comment by gjanssens** [comment]
Eh oops. The release is planned for the weekend of March 26th only. So that gives you some more time. Sorry for the confusion.

**Comment by jralls** [comment]
@harski, where did you get the template file for your update?

**Comment by harski** [comment]
@gjanssens Oh, sorry. I totally overlooked that bit. I'll rebase to maint tonight.

@jralls I updated it with msgmerge (`msgmerge -o fi.new.po fi.po gnucash.pot; mv fi.new.po fi.po`) as instructed on the the [wiki page](https://wiki.gnucash.org/wiki/Translation#Updating_an_existing_.po_file). Is there someting wrong with the template?

**Comment by jralls** [comment]
@harski, the question was "where did you get the template file", not how did you do the merge. If you followed the instructions on the wiki to {{{make pot}}} then your translation is based on the master branch msgids, some of which will be different from the maint branch ones.

Do **not** rebase master onto maint. That will make a huge mess. Instead, do the following in your fi-translation branch:
{{{
git reset --hard maint
make pot
msgmerge -o fi.new.po fi.po gnucash.pot
mv fi.new.po fi.po
git add po/fi.po
git commit -m "Merge updated po template in fi.po"
git cherry-pick 5fc4251
}}}

Once you've done that you'll probably have some cleanup in fi.po because of the differences in the templates. Fix it up and do
{{{
git commit -a --amend
}}}
to rewrite the second commit, then force-push the result here.

**Comment by harski** [comment]
@jralls right, right. I of course got the template file from the particular branch I rebased my changes on.

**Comment by harski** [comment]
PR rebased on maint branch.

**Pull request closed without merging**
