### PR TITLE
[guile-3] change _ to G_

### PR DESCRIPTION
**Pull request by christopherlam**
In guile-3 _ is a reserved symbol. Change to G_ for gettext by guile convention.

### CODE REVIEW

**Comment by christopherlam** [comment]
From my understanding the `G_` must be added somewhere to be recognised as translatable? Not sure where.

**Comment by jralls** [comment]
You did that at line 44 of core-utils.scm.

**Comment by christopherlam** [comment]
> You did that at line 44 of core-utils.scm.

I'm referring to `gnucash-pot.cmake:24` need to add `--keyword=G_`?

**Comment by jralls** [comment]
Ah, different meaning of "recognized". That's correct.

**Pull request merged**
