### PR TITLE
Little refactor of account.c

### PR DESCRIPTION
**Pull request by CarwynNelson**
Based on a comment from pr #219 

My first open source pull request with a code change. Any more refactoring suggestions / small changes that are beginner friendly are very welcome.

Thanks :)

### CODE REVIEW

**Comment by gjanssens** [comment]
The code in itself is good. But unfortunately you worked from master instead of unstable and your code doesn't apply to unstable.

I realize this is probably not mentioned in the wiki pages you have been reading. As we are in our final effort to release 2.8, we have created a separate branch "unstable" in which all commits should go that need to be included in 2.8. Master is now targeted at longer term new features/improvements for what will eventually become 2.10 (or 3.0?).

In that light I have merged PR #219 into unstable and your code should be working on top of that. However your commits start from scratch on master instead. Can you rebase your PR on unstable and resolve the merge conflicts it has? You can force-push your result back to CarwynNelson:little-account-c-refactor on github to update this PR. Thanks!

**Comment by CarwynNelson** [comment]
Hi @gjanssens 

No problem. Thanks for letting me know. I have made this change and I am just waiting for the build to complete.

Once 2.8 has been released will the `unstable` branch continue to be used for short term contributions or will we go back to using `master` until the next push for a release?

**Comment by gjanssens** [comment]
When 2.8 is released we will do a branch dance. Current maint will be discontinued, current unstable will become the new maint (which stands for 'maintenance') and will accept bugfixes and smaller feature improvements targetted at the stable 2.8 series. master will remain master and will continue to accept major feature changes and refactorings for the future 2.10/3.0. Even further away in the future when we get closer to 2.10, we'll create a new unstable branch to release the 2.9 development series. It will be branched from whatever master points to at that point.

**Comment by gjanssens** [comment]
When you rebased, it seems your local repo was not completely in sync with our primary repo, as your branch was not branched off of unstable's head commit. Not really a problem, I have merged your work after a rebase. Thanks!

In the future, please pull from the Gnucash/gnucash repo before rebasing. That reduces the number of merge commits that end up in the main repo :)

**Comment by gjanssens** [comment]
Oh, and congrats on your first accepted PR :D

**Comment by CarwynNelson** [comment]
Thanks! On to the next thing :)

**Pull request closed without merging**
