### PR TITLE
Hebrew translation update v3.10

### PR DESCRIPTION
**Pull request by avma**
hope this is the proper brunch to submit this...

### CODE REVIEW

**Comment by fellen** [comment]
Avi, you have been working on the wrong branch.

- maint is 3.10
- master is 3.900

You can try to merge your changes back.

**Comment by avma** [comment]
ok thanks...

**Comment by avma** [comment]
I ended up creating a new pr in 'maint', do i need to revert somehow the pr from 'master'?

**Comment by fellen** [comment]
No, the new approach is in PR #699. I will close this.
Only in your local repo, you should reset & rebase your master branch.

**Pull request closed without merging**
