### PR TITLE
Revision and extension of accounts for the Russian language.

### PR DESCRIPTION
**Pull request by DiMan**
Revision and extension of accounts for the Russian language.
In addition, replacing of commodity: USD => RUB.

### CODE REVIEW

**Comment by fellen** [comment]
Hi,

why didn't you base it on maint. So I had more work.

You should consider to insert the namespace section from
https://wiki.gnucash.org/wiki/Account_Hierarchy_Template#Adjust_the_Header then you can run xmllint to check the syntax of the files.

I saw a few categories, which were not marked as placeholder. Was that intended?

Cherrypicked with commit fc5bdfa into maint.

**Comment by DiMan** [comment]
Hi,

Sorry for inconvenience. I have worked on the translation on unstable branch and have adapted / expanded the accounts. Unfortunately I forgot to switch to maint branch. 

I will look at the other points that you have addressed and adapt them. 
I will commit the new changes on **maint** branch per PR.

Thanks

**Comment by DiMan** [comment]
Hi fellen,

I'm done with mentioned changes. Do I have to commit it to "maint" branch? Or directly to "unstable" branch? If I understand correctly, "maint" will soon be replaced by "unstable" (see commentary by gjanssens in PR # 295)?

Thanks

**Comment by DiMan** [comment]
Hi fellen,

I just commited it on **maint** - see PR #300. 

Thanks

**Pull request merged**
